### ISSUE TITLE
Run peerjs client in a node.js application?

### ISSUE THREAD

**Issue by josdejong** [peers/peerjs#103]
Would it possible run a peer.js client in a node.js application instead of the browser? 

I'm creating a peer-to-peer network consisting of (programmatic) peers living both in browsers and in node.js applications. They have to send data to each other, no video/audio. WebRTC would be a great solution to resolve the routing and communication between the peers without the need for a centralistic client/server structure. But WebRTC seems to be supported only in the browser.

See also this question: http://stackoverflow.com/questions/18872712/node-js-webrtc-client

**Comment by FredrikNoren** [comment]
:+1:

**Comment by pavelvasev** [comment]
+2^56 for the feature!

**Comment by cbyte** [comment]
:+1:

**Comment by xDarkShadowKnightx** [comment]
:+1:

**Comment by vadzim** [comment]
:+1:

**Comment by remaininlight** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by lewiseason** [comment]
+1

The hack posted by @piyushranjan doesn't seem to work with the current stable version, as it doesn't export anything globally (and all the modules are in one file).

The workaround for this seems to be to use the non "compiled"/concatenated version.

Thus, clone the repository, and then do something like this:

``` javascript
window = global;
location = {protocol: 'http'};

XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var wrtc = require("wrtc");
RTCPeerConnection = wrtc.RTCPeerConnection;
RTCSessionDescription = wrtc.RTCSessionDescription;
RTCIceCandidate = wrtc.RTCIceCandidate;

WebSocket = require('ws');

require('./peerjs/lib/exports.js');

var peer = new window.Peer({
  // snip...
});
```

Pay special attention to the require line near the bottom, which handles loading all the separate parts for you, into the window object.

Still a nasty hack, but it seems to work, at least for very basic tests.

**Comment by josdejong** [comment]
@lewiseason Did you actually got a connection up and running and be able to send some data for example? 

I didn't succeed in this so far. It looks like I can open a connection, but there is no data channel created.

This is what I tried:

1. Installation

  ```
  sudo apt-get install libnss3-dev libexpat1-dev
  npm install peerjs BlobBuilder binary-pack ws xmlhttprequest wrtc
  ```

2. Create an html file **peer1.html** connecting a client peer with id `'peer1'`:

  ```html
  <!DOCTYPE html>
  <html>
  <head>
    <title>peer1</title>
    <script src="node_modules/peerjs/dist/peer.js"></script>
  </head>
  <body>
  <script>
    var peer = new Peer('peer1', {key: 'lwjd5qra8257b9', debug: true});
  
    peer.on('connection', function (conn) {
      console.log('new connection');
  
      conn.on('data', function(data) {
        console.log('Received', data);
      });
  
      conn.on('error', function (err) {
        console.log('Error', err);
      });
  
      conn.on('open', function () {
        conn.send('Hello from ' + peer.id + '!');
      });
    });
  </script>
  </body>
  </html>
  ```

3. Create a node.js script **peer3.js**:

  ```js
window = global;
  window.BlobBuilder = require("BlobBuilder");
  location = {protocol: 'http'};
  
  BinaryPack = require("binary-pack");
  XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
  
  var wrtc = require("wrtc");
  RTCPeerConnection = wrtc.RTCPeerConnection;
  RTCSessionDescription = wrtc.RTCSessionDescription;
  RTCIceCandidate = wrtc.RTCIceCandidate;
  
  WebSocket = require('ws');
  
  require('peerjs/lib/exports.js');
  
  var peer = new Peer('peer3', {key: 'lwjd5qra8257b9', debug: true});
  
  peer.on('open', function () {
    console.log('peer open');
    var conn = peer.connect('peer1');
  
    conn.on('data', function(data) {
      console.log('Received', data);
    });
  
    conn.on('error', function (err) {
      console.log('Error', err);
    });
  
    conn.on('open', function () {
      console.log('connection open');
      conn.send('Hello from ' + peer.id + '!');
    });
  });
  ```
4. Open the file **peer1.html** in your browser
5. Run the node.js script **peer3.js**

Looking at the debug output, it looks like peer3 is succesfully connected to peer1, but it does not establish a data channel: peer1 outputs "new connection to peer3", but there are no messages received.

**Comment by lewiseason** [comment]
I'm afraid I didn't get very far with testing it - seemed a bit to Frankenstein to use in production, so I ended up leaving it. Sorry :(

**Comment by SamWarmuth** [comment]
:+1:

**Comment by kompsale** [comment]
:+1:

**Comment by kanaka** [comment]
Any update on this?

**Comment by recap** [comment]
@josdejong the issue lies with the signalling data. It seems no STUN data is being attached to the offer/answer. Without this data no actual connection can be made. The following does make a connection between browser and node but without peerjs signaling. 

https://github.com/cjb/serverless-webrtc

**Comment by Lev09** [comment]
+1

**Comment by FeepingCreature** [comment]
+1

**Comment by neopostmodern** [comment]
As this has been open for more than two years: Is there any (other) known package that works P2P in browser & node?

**Comment by josdejong** [comment]
I haven't had time to check it out, but https://github.com/feross/simple-peer says it works in both node.js and the browser.

**Comment by bfishman** [comment]
Is this what you're looking for?  https://github.com/socketio/socket.io-p2p

from the readme:  

"This module provides an easy and reliable way to setup a WebRTC connection between peers and communicate using events (the socket.io-protocol).

Socket.IO is used to transport signalling data and as a fallback for clients where WebRTC PeerConnection is not supported."

**Comment by neopostmodern** [comment]
As far as I am concerned, it doesn't work on Node. That's why I ran into this thread.

**Comment by bfishman** [comment]
Hmm. Could you be more specific? I'm using it right now, using a node server to connect peers which then establish webRTC connections to each other and/or the node server's machine.

**Comment by neopostmodern** [comment]
> using a node server to connect peers which then establish webRTC connections to each other

So, you're *not* running it as a client. You're running it on a server that connects *other* clients (which you don't mention to be node apps - if they are, I'd be interested how you set them up).  
This thread is about using peerjs (or potentially anything else) as a peer (client) in a node application.

**Comment by maritz** [comment]
> webRTC connections to each other and/or the node server's machine

The second part of that seems like exactly what is being discussing here. Can anyone else confirm this?

**Comment by FeepingCreature** [comment]
No, the issue is using NodeJS as a WebRTC **client**. Ie. connect from a NodeJS instance that is not necessarily the server.

**Comment by bfishman** [comment]
Oh, apologies. SimplePeer will do that. But it requires the server platform to have certain webrtc capabilities installed. The 'wrtc' module provides this on most machines. Notably *not* on a raspberry pi right now, in case that matters to you (it does to me!)

snippet from their readme.md:

in node

To use this library in node, pass in opts.wrtc as a parameter:

var SimplePeer = require('simple-peer')
var wrtc = require('wrtc')

var peer1 = new SimplePeer({ initiator: true, wrtc: wrtc })
var peer2 = new SimplePeer({ wrtc: wrtc })

**Comment by marcb1** [comment]
+1 this would be a nice feature

**Comment by bfishman** [comment]
Check out electron-webrtc, or webrtc-native. I use electron-webrtc for my node.js instance to connect with browsers (using the datachannel specifically)

**Comment by jeryfast** [comment]
Hi, I see this is old, but you or anyone might need this. I am working on my thesis and I have made some steps forward. I have tried many things and simplepeer has no signalling implemented.  Sending messages over datachannel (nodejs peerjs webrtc) - over network on Raspberry Pi 2 (ARM, Raspbian Jessie, but should work everywhere) using deployed signalling server (peerserver) is now working. The other client is the a firefox browser in windows enviroment. I wouldn`t have made it without your discussion here, so I am giving back to the community.

Key things about what (not) to do:
-dont use selenium, its not fast enough, at least for my application
-xvfb didnt work out for me, well it did 
-you must not require peerjs module
-on Raspberry at least - use electron-webrtc, as wrtc isn`t available for arm anyway
-dont use serialization

**Having to you everything by yourself is hard, so here is the code:**
window = global
window.BlobBuilder = require("BlobBuilder")
location = {protocol: 'http'}

BinaryPack = require("binary-pack")
XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var wrtc = require('electron-webrtc')()
//var Peer = require('peerjs')

RTCPeerConnection = wrtc.RTCPeerConnection;
RTCSessionDescription = wrtc.RTCSessionDescription;
RTCIceCandidate = wrtc.RTCIceCandidate;

WebSocket = require('ws')
require('/home/pi/node_modules/peerjs/lib/exports.js');

var peer = new Peer(
	... 
})

var conn=peer.connect('id')
conn.serialization='none'
conn.send('hello from nodejs!')

That`s it, regards, JP

**Comment by nuno-nlfsoftware** [comment]
Hi @jeryfast , thanks for your solutions, I was looking for something like that 👍 

I test it on a mac (not on the raspberry yet) and was getting the error "Failed to set the 'binary Type' property on 'RTCDataChannel': Blob support not implemented yet"

After some search, found that on file utils, on path node_modules/peerjs/lib around line 116:

```
try {
        dc.binaryType = 'blob';
        binaryBlob = true;
      } catch (e) {
      }
```
that is causing the error and the app to crash.

If the code is commented the app works and it behaves as a browser client, just beautiful. But is a dirty hack, so I was looking a way to "configure" or do something that don't be change code from the lib, but until now I don't found any.

The challenge resides in when that piece of code is executed, that is on the module Load process, when the require of the exports is done:

`require('./node_modules/peerjs/lib/exports.js');`

Any one has and ideia or suggestion on how to correct this?

Regards

**Comment by jeryfast** [comment]
Nice, if you use 'none' serialization, it works also, without changing anythings in a library. Regards

**Comment by crosofg** [comment]
Hello
I am getting this error.
```
  global.postMessage(messageName, '*');
             ^

TypeError: global.postMessage is not a function
    at Object.setZeroTimeoutPostMessage [as setZeroTimeout] (

**Comment by ethan2-0** [comment]
@crosogf, that error looks to me like a symptom of a larger problem. It appears that the only place postMessage is used is in error-handling code. My guess would be that it has something to do with binary blob support detection in lib/util.js (the code @nuno-nlfsoftware says to comment out). I noticed that there are two places that code is present, in dist/peer.js or dist/peer.min.js, and in lib/util.js. For me, only modifications to the latter were effectual (due to @jeryfast's hack of requiring lib/exports.js).

**Comment by web-mech** [comment]
I'm just gonna leave this here https://www.npmjs.com/package/peerjs-nodejs

**Comment by web-mech** [comment]
Also, the connection serialization doesn't have to be set to `none`. You can use any other option besides `binary`, you just need to set it since binary is the default. I set it to `json` which works just fine.

**Comment by afrokick** [comment]
> I'm just gonna leave this here https://www.npmjs.com/package/peerjs-nodejs

Thanks, I think it should be a part of PeerJS.

**Comment by vegalou** [comment]
here is my code after test `jeryfast` & `peerjs-nodejs`

```
const peerJs = require('peerjs-nodejs');
const peer = peerJs("myPeerId", {
host: '192.168.137.231',
port: 9000,
pingInterval: 5000,
path: '/myapp',
debug: 3, 
iceTransportPolicy: 'relay',
config: {
'iceServers': [
	{ urls: "stun:stun.l.google.com:19302" },
	{
		urls: "turn:34.192.149.24:5678?transport=udp",
		username: "USER", credential: "PASS"
	}
]
}
});

let conn = peer.connect('myPeerJS', {
	reliable: true
});


setTimeout(()=>{
 // NOT JSON
 // conn.serialization='none';
 // conn.send('hello from nodejs!');  

 // JSON WAY
 conn.serialization = 'json';
 conn.send({ value: 'hello from nodejs!' });

}, 3000);

setTimeout(()=>{
  conn.close();
  console.log("CONN CLOSE");
  process.exit();
}, 10000);
```

**Comment by federico-dondi** [comment]
Hello, I'm getting this error, as soon as I create a Peer instance (using `peerjs-nodejs`) on the NodeJS server. Does somebody has solved it?

**server.js**
```
const Peer = require('peerjs-nodejs')

...

this.peer = Peer('webRTC-webinar-plugin', {
      host: '/',
      path: 'peer-js',
      port: (useHTTPS) ? 8443 : 8080,
      secure: (useHTTPS) ? true : false
})
```

```
/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/peerjs/lib/util.js:234

      global.postMessage(messageName, '*');
             ^
TypeError: global.postMessage is not a function
    at Object.setZeroTimeoutPostMessage [as setZeroTimeout] (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/peerjs/lib/util.js:234:14)
    at Peer.disconnect (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/peerjs/lib/peer.js:420:8)
    at Socket.<anonymous> (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/peerjs/lib/peer.js:120:12)
    at Socket.emit (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/eventemitter3/index.js:71:35)
    at exports.XMLHttpRequest._http.onerror (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/peerjs-nodejs/node_modules/peerjs/lib/socket.js:91:12)
    at exports.XMLHttpRequest.dispatchEvent (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at exports.XMLHttpRequest.handleError (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:533:10)
    at ClientRequest.errorHandler (/Users/federico/Documents/webRTC-webinar-plugin/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
```

Can somebody help?

**Comment by aamin3189** [comment]
Same issue here, not sure if the package is managed

**Comment by jsProj** [comment]
https://www.npmjs.com/package/peerjs-on-node

**Comment by jonasgloning** [comment]
Hey @stefanpl,

you could try the [beta release](https://www.npmjs.com/package/peerjs/v/2.0.0-beta.3). It supports PeerJS on the server using `wrtc`. Documentation is sparse, have a look at the [PR](https://github.com/peers/peerjs/pull/928) and the [diff](https://github.com/peers/peerjs/compare/master...releases/2.0.0).

Unfortunately, `wrtc` seems to have stalled a bit---there haven’t been any commits since June last year, and I had some trouble both at buildtime and at runtime with more recent node versions. So thanks for the pointer to `node-datachannel`, that might be a good replacement.



Just out of curiosity, what are you planning to do with PeerJS on the server?

**Comment by stefanpl** [comment]
Thanks for the quick reply @jonasgloning 🎉

Glad to see node support on the roadmap (well, even in the beta) for v2.

I'm currently checking options for implementing a realtime multiplayer game. I might very well start the prototype without an authorative server, but this will definitely be needed at some point. Well, if I get that far … 😬

**Comment by MarkusPint** [comment]
Seems like calling a peer from a Node-based client using peerjs@beta is possible, but once the remote peer answers the "stream" event never gets fired on the Node side.
