### ISSUE TITLE
Can this library be used for a Nodejs <> Browser connection?

### ISSUE THREAD

**Issue by markg85** [peers/peerjs#1066]
Hi,

I was trying to implement PeerJS in a pet project of mine with the main goal to connect a nodejs console based application to a website though WebRTC. 

Initially i thought PeerJS to be the one capable of doing this. While i didn't see that explicitly, i just assumed it because i saw `npm install peerjs` command.  I now assume that this is intended to be used when one creates a website and uses NPM for that.

Trying to use peerjs in nodejs gives me:
`ReferenceError: navigator is not defined`

Is there a way to get peerjs working on nodejs?

If this isn't possible in peerjs yet, would it be possible to add support for this? This project for example: https://github.com/node-webrtc/node-webrtc does make webrtc possible within nodejs

Best regards,
Mark

**Comment by markmarijnissen** [comment]
Check out peer beta, see https://github.com/peers/peerjs/pull/928

**Comment by markg85** [comment]
That solve the request, i'll wait for that to be released. Thanx for the pointer!
