### ISSUE TITLE
Connection doesn't work ( peer.connect(...) ). HELP PLEASE! ='(

### ISSUE THREAD

**Issue by Alazib** [peers/peerjs#1068]
Hi every one. 

I am using Vue3 and trying to run this code in order to send 'HI' from peerLocal to peerRemoto, but it doesn't work. I've tried countless ways but it still doesn't work.
I suppose that the problem is that the connection between the two peers is not made because the console.log of line 57 should display 'true' (but throws 'false') and the  console.log of line 61  should be displayed but it doesn't.

Any hint or advice? 

Thanks for your help.
![Captura de pantalla (442)](https://user-images.githubusercontent.com/99830132/229872314-0171963f-80b0-49fd-92d2-af42d2ca8271.png)

**Comment by tmathews** [comment]
Can confirm, not working on my application either. Also had reports of the examples not working.

**Comment by PankajFB** [comment]
hi @Alazib u can refer to my code 
I hope it will help u
https://github.com/PankajFB/PeerJs
