### ISSUE TITLE
Call answer for a stream coming from screen share on peer which does not have a webcam shows nothing

### ISSUE THREAD

**Issue by gianisimone** [peers/peerjs#1171]
Why is it mandatory to have a webcam and to allow permissions to it in the peer receiver who just need to show the media stream coming from the screen share coming from another peer? Is it possible to avoid having a webcam and asking permissions to it in the receiving peer?

**Comment by dingavinga1** [comment]
If I understand you correctly, you want to share a user A's screen with a user B, without having to obtain webcam permissions from user B, right? In that case, you can use `call.answer()` without the optional sender stream argument. This way, you won't need to get user/display media permissions from user B for them to be able to stream user A's screen. Hope this helps😀

**Comment by gianisimone** [comment]
Yes, the solution is very simple. Since just calling the _call.answer()_ did not show the incoming streaming I thought that it was mandatory to allow webcam permissions. Actually, the reason that the streaming was not showing in the _<video>_ tag is that autoplay does not work if no interaction has happened on the document
