### ISSUE TITLE
Add Support for different signaling servers

### ISSUE THREAD

**Issue by richardanaya** [peers/peerjs#118]
I really like this project, but the thought of having to run my own backend server for a massively scalable p2p app is a bit daunting.  Is there anyway we can use easily us a thirdparty of our choice for the non-webrtc communication?  Where would be a good place to start on this?

**Comment by QuantumInformation** [comment]
I thought peerJs run their own servers for you as an option?

**Comment by frankrobert-ls** [comment]
Not sure why this was closed - Are there any plans on supporting alternative signaling servers other than PeerJS server? As it is today PeerJS server is not enterprise-ready and is a blocker for us to move forward with PeerJS effectively in production.

• Having an internal data structure to keep all ids in-memory prevents us from horizontally scaling or load-balancing the server.
• We don't have granular control over distributing or relinquishing keys.
• We can't monitor the internals of the server nor handle errors effectively.
• We would prefer something that we can offload to a SaaS or possibly different technologies such as a message queue or pub/sub system

It would be great if this was reconsidered.
