### ISSUE TITLE
Memory leak when sending large binary chunks through data channel

### ISSUE THREAD

**Issue by sbalko** [peers/peerjs#134]
Hi, 

I found a massive memory leak, when recurrently and frequently sending large (10 MBs) ArrayBuffers through a reliable binary connection (but throwing the data away immediately on the receiver side). The memory use rapidly goes through the roof, crashing Chrome at ~3 GB. First suspecting a Chrome issue, I could meanwhile reproduce the issue in Firefox as well. This _may_ hint at an issue in peer.js itself. Will drill deeper tomorrow and also attach a test case to reproduce the issue.

Soeren

**Comment by Tulga** [comment]
is this fixed ?

**Comment by maxpavlov** [comment]
Can be closed now I assume.

**Comment by afrokick** [comment]
@maxpavlov did you try to send large file?

**Comment by afrokick** [comment]
Fixed in https://github.com/peers/peerjs/commit/718e16b736cf5dda9563ec4bc70fba35db3812b9
