### ISSUE TITLE
Peer.Call without stream

### ISSUE THREAD

**Issue by choudeshell** [peers/peerjs#158]
It seems that it impossible to utilize Peer.Call without passing in a user media stream. Peer.Call should be able to call any peer even if the caller decides to not give the browser access to their webcam/mic.

**Comment by thomasverleye** [comment]
@grabbou can you paste some example code?

**Comment by jhogoforbroke** [comment]
+1

**Comment by doppio** [comment]
@michelle, I don't suppose you have any thoughts on how this could be implemented? I know very little about WebRTC, but it would be enormously helpful to me to be able to make calls as a user without a stream.

**Comment by Rastopyr** [comment]
+1

**Comment by ndac-todoroki** [comment]
+1 too

**Comment by mahmed0715** [comment]
+1

**Comment by demogoran** [comment]
Not sure, if it's still actual, but got able to bypass it using this trick:

const audioCtx = new AudioContext();
const dest = audioCtx.createMediaStreamDestination();
var call = peer.call('testid', dest.stream);

**Comment by yunusberateke** [comment]
> Not sure, if it's still actual, but got able to bypass it using this trick:
> 
> const audioCtx = new AudioContext();
> const dest = audioCtx.createMediaStreamDestination();
> var call = peer.call('testid', dest.stream);

it's not working

can anyone solve this problem?

**Comment by wilywork** [comment]
@yunusberateke  it's work
```
const createMediaStreamFake = () => {
      return new MediaStream([createEmptyAudioTrack(), createEmptyVideoTrack({ width:640, height:480 })]);
}

const createEmptyAudioTrack = () => {
    const ctx = new AudioContext();
    const oscillator = ctx.createOscillator();
    const dst = oscillator.connect(ctx.createMediaStreamDestination());
    oscillator.start();
    const track = dst.stream.getAudioTracks()[0];
    return Object.assign(track, { enabled: false });
}

const createEmptyVideoTrack = ({ width, height }) => {
    const canvas = Object.assign(document.createElement('canvas'), { width, height });
    canvas.getContext('2d').fillRect(0, 0, width, height);
  
    const stream = canvas.captureStream();
    const track = stream.getVideoTracks()[0];
  
    return Object.assign(track, { enabled: false });
};

**Comment by mind0bender** [comment]
@wilywork
Thanks for that
It does work but only for answering the call
It would be great if it worked for calling too.

In my case I want the student to call the teacher but not share his media.

**Comment by aschenkuttel** [comment]
any updates?

**Comment by BadTripp** [comment]
`
const createMediaStreamFake = (): MediaStream => {
  return new MediaStream([createEmptyAudioTrack(), createEmptyVideoTrack({ width: 640, height: 480 })]);
}


const createEmptyAudioTrack = (): MediaStreamTrack => {
  const ctx = new AudioContext();
  const oscillator = ctx.createOscillator();
  const destination = ctx.createMediaStreamDestination();
  oscillator.connect(destination);
  oscillator.start();
  const track = destination.stream.getAudioTracks()[0];
  return Object.assign(track, { enabled: false }) as MediaStreamTrack;
}


const createEmptyVideoTrack = ({ width, height }): MediaStreamTrack => {
  const canvas = Object.assign(document.createElement('canvas'), { width, height });
  canvas.getContext('2d').fillRect(0, 0, width, height);
  const stream = canvas.captureStream();
  const track = stream.getVideoTracks()[0];
  return Object.assign(track, { enabled: false }) as MediaStreamTrack;
};`
