### ISSUE TITLE
Document listAllPeers()

### ISSUE THREAD

**Issue by kenianbei** [peers/peerjs#173]
I'm not quite clear on how listAllPeers() is used, it seems to expect a callback rather than just returning a list. Can you post an example of usage?

**Comment by eugenio** [comment]
is the method listAllPeers implemented on the server yet? if so what's the correct way to use it?
Please forgive me, I'm a newbie...

**Comment by thisconnect** [comment]
start your own server with the option `allow_discovery: true`, I am using express, that is something like:

```js
var server = app.listen(8080);

app.use('/peer', ExpressPeerServer(server, {
    allow_discovery: true,
    debug: !!process.env.DEBUG
}));
```

**Comment by eugenio** [comment]
i'm doing that:


> var ExpressPeerServer = require('peer').ExpressPeerServer;
>
>var options = {
>    debug: true,
>    allow_discovery: true
>}
>
>
>
>
>// create a http server instance to listen to request
>var server = require('http').createServer(app);
>
>// peerjs is the path that the peerjs server will be connected to.
>app.use('/peerjs', ExpressPeerServer(server, options));
>// Now listen to your ip and port.
>server.listen(9000, "localhost");
>
>var idList = server.listAllPeers;
>
>
>app.get('/peerjs/ids', function (req, res) {
>  return res.send(idList);
>}); 

this is my code.

But  even when the app is running I get "undefined" object when i try to "console.log(idList)"

What am I doing wrong?

**Comment by thisconnect** [comment]
Haven't fully tested it myself, but listAllPeers is a method in the client library not on the server. AFAIK set allow_discovery: true on the server and try calling listAllPeers on the client
https://github.com/peers/peerjs/blob/master/lib/peer.js#L457

**Comment by eugenio** [comment]
thanks!!!!
