### ISSUE TITLE
?transport=udp on TURN server - unreliable video connections

### ISSUE THREAD

**Issue by redannick** [peers/peerjs#174]
This may not be a peerjs issue, but it may help others who are experiencing similar problems.

I'm using peerjs with latest chrome (33) and [rfc5766-turn-server](https://code.google.com/p/rfc5766-turn-server/) for STUN/TURN and I was getting intermittent issues with peers connecting ok for data, but having intermittent issues with video links. According to all the events and callbacks there was no issue, a connection is made, however all I see is a black rectangle  instead of the feed.

While trying to work around connection issues for strict firewalls I noticed that when using 
`{ url: 'turn:user@xxx.xxx.xxx.xxx:443?transport=tcp', credential: 'password' }`
only - so **no udp option**, I never saw this happen.

Any suggestions as to what is really going on with the issue? In the meantime this works around the problem just fine.

**Comment by enrique-ramirez** [comment]
Sorry to bring an old issue back from the dead, but I'm encountering this issue and wanted to know if I'm getting it right:

I have a STUN and a TURN server up and running, and am getting pretty good connections all around, but some people are unable to join. Rather, I get the behaviour @redannick has been experiencing: a black square where the video should be.

So everything is working fine: websockets, the offers, the answers. All but the streaming of audio/video.

After some research, it seems that the people who have these issues are under a firewall with UDP blocked.

Solution, then, is to enable tunneling through TCP on my TURN server.

So far, so good. But I'm wondering if there's a way of leaving TCP as a last, last resource and use UDP where it works? And more importantly, is there an advantage on doing so (or rather, a disadvantage on using TCP every time my TURN is used)?

**Comment by redannick** [comment]
Trouble is, you're not exactly informed that UDP isn't working, at least in my experience. Everything appeared to work fine apart from the lack of video.
