### ISSUE TITLE
Android performance

### ISSUE THREAD

**Issue by alioguzhan** [peers/peerjs#177]
Hi all,

There is almost no clean sound when talking over 2 android devices. there is no problem with between 2 desktop app. At first i thought this is some kind of bug about **webrtc** . But apparently it is **not** :

[apprtc.appspot.com](htpp://apprtc.appspot.com)

this is working **perfectly** on almost each device and platform. [mac os, nexus 7, galaxy s3 mini]
no echo, no noise or no annoying electronic sounds.

Is this a known bug?

**Comment by afrokick** [comment]
https://github.com/peers/peerjs/commit/14ff7f80ad62adb031c55ab5a1b75e6e3ca0fd64
