### ISSUE TITLE
Questions about multi-user chat

### ISSUE THREAD

**Issue by daGrevis** [peers/peerjs#179]
Currently I have implemented a chat that allows two people to speak with each other. It's pretty basic and resembles chat that you have in your examples.

Now I would like to add option to add more people to the same chat. Something like multi-user chat or conference.

I would like to hear what do you think about current architecture I have in mind. I am interested in suggestions on how to improve it and weak points in it.

So here it goes!

Each user is a peer that's connected to broker server. It has active connections to each peer in chat. So if there are users X, Y and Z, X will have connections to Y and Z, Y will have to X and Y and finally Z will be connected to X and Y.

When a message is sent, I call `connection.send` to each connection the peer knows is in chat except himself. So for chat with 3 people in it, it will call send twice.

When a new user joins the chat, it connects to founder peer and gets all current connections. Then it connect to them all of them (except founder because he has connected already) and sends his connection to each connection. At the end, all peers know about each other.

Is it too heavy? I mean, I have N \* (N - 1) connections where N is user count in chat.

How can I deal with a case when founder connection is dropped? A link to chat contains it's peer ID and if it is dropped, new people can't connect to existing chat.

As you can see, it's all a little fuzzy in my head and sorry about that. :blush: Any help would be much appreciated!

**Comment by Goatic** [comment]
does this mean multi-user conferences isn't possible without a mesh topology in peerjs? I've looked at the API, and it does look very limited in terms of this kind of conferencing.

**Comment by mertkahyaoglu** [comment]
@daGrevis Thanks for sharing the code. Can you explain the if parts (who == "x" and who != x) ?

**Comment by daGrevis** [comment]
@mertkahyaoglu I believe it was just a dummy mechanism for separating master from slaves. When link contains "x", you're a master and you're responsible for sharing data about active connections with slaves.

Here are two repos that might be useful to you:

https://github.com/daGrevis/Hendrix
https://github.com/daGrevis/hndrx

**Comment by mertkahyaoglu** [comment]
@daGrevis Thanks :+1:

**Comment by AngeSohone** [comment]
Hi, i just implemented peerjs for multi-conference. i got some problems. when more than 3 users are connected, the next can't receive remote stream. Haven't error message on console log. just that they can't get streams. want to know if is due of limit of mesh architecture (Can’t scale to a large number of participants) or if i did something wrong. Thanks

**Comment by RohanNavlakhe2** [comment]
I am also getting the same problem as @AngeSohone .
I am implementing a video conferencing solution and when more than 3 peers will connect then new connections will not get the streams of the existing people in the conference.

**Comment by liquidvisual** [comment]
@RohanNavlakhe2 Did you ever figure this out?
