### ISSUE TITLE
Emit error event on failed/disconnected ICE status

### ISSUE THREAD

**Issue by szimek** [peers/peerjs#181]
Currently when ICE connection state is `failed` or `disconnected` PeerJS tries to close `DataConnection` connection [dist/peer.js#L2305-L2309](https://github.com/peers/peerjs/blob/7ad9494c9e9d2b40ba075b715cf3acf1320d1951/dist/peer.js#L2305-L2309). However, in case of `failed` state, the connection has never been opened and thus `DataConnection#close` doesn't really do anything [dist/peer.js#L1954-L1956](https://github.com/peers/peerjs/blob/7ad9494c9e9d2b40ba075b715cf3acf1320d1951/dist/peer.js#L1954-L1956). There's no way to clean up `DataConnection` connection on the receiving side, which already received the connection via `connection` event.

Unfortunately, my app doesn't use TURN server and according to WebRTC specs, ICE connection state is `failed` when data connection can't be established due to network issues (e.g. lack of STUN/TURN server). 

It would be great if PeerJS emitted an error event with type `failed` or `disconnected`, so that apps can clean up connections properly on both ends.

**Comment by whatvn** [comment]
Hello, I faced the same problem when using peerjs.
My question: is there any any way we can do a fallback, when `'iceConnectionState is disconnected, closing connections to peer_id` or `iceConnectionState is failed, closing connections to peer_id` happen, we can re-init connection to peer or ignore and by pass that peer to connect to another peer? Or mark fail peer as broken peer and establish connection to others peer?

**Comment by RaulTsc** [comment]
Hi. I'd like to take this on but I'll probably need some help. Will follow up with a PR and we'll go from there :)

**Comment by afrokick** [comment]
Fixed in https://github.com/peers/peerjs/commit/ed4012447ecfb476d0ae5d9be039339a973bec8d
