### ISSUE TITLE
Do not receive data after reconnection to the same peer

### ISSUE THREAD

**Issue by itdea** [peers/peerjs#190]
First of all - thanks for peerjs, it makes things very easy...

My issue:

I was playing around with peerjs in a video-chat app with included text chat, file sharing and an ability to turn video, chat and file sharing on and off. With the video connection every thing is working well - the user can reconnect to the same peer and the conversation continues. 
I tried this with the data connection. During the first data connection between the two peers every thing works well. When I disable the chat the data connection is closed (this is also shown in the log). 
After a reconnection to the same peer the data connection itself succeeds but it is not possible to send any data between the peers. Even the connection log is the same as in the first data connection and I do not get any error. 

I use nearly the same code like the example chat - just with the ability to close and reconnect connections with the following commands:

close connection: 

window.existingChat.close();

reconnect: 

chat=peer.connect(...);
window.existingChat = chat;

I tried this in Firefox 29 and Chrom 34 on MacOSX in all possible ways - every time the same. Does anyone have an idea why this happens?

Thanks Michael

**Comment by d-knafo** [comment]
+1

**Comment by afrokick** [comment]
Please reopen it if still exists
