### ISSUE TITLE
Cannot send after receiving

### ISSUE THREAD

**Issue by jure** [peers/peerjs#199]
I'm trying to wrap my head around this. Is there any reason why this shouldn't work:

```
peer.on('connection', function (conn) {
  conn.on('data', function(data) {
    response = manipulate(data);
    conn.send(response);
  }
}
```

Upon receiving the data (which works fine), I would like to transform the data a bit and send it back with .send, but this doesn't do anything. Looks like a no-op. Why would that be? I noticed that your test use the same paradigm, so I'm really lost here:
https://github.com/peers/peerjs-test/blob/master/public/js/testData.js#L35-L47

Using Chrome 37.0.2023.2 canary.

**Comment by tellnobody1** [comment]
```js
peer.on("connection", conn => {
  conn.on("open", () => {
    conn.on("data", data => {
      let conn1 = peer.connect(conn.peer)
      conn1.on("open", () => conn1.send("echo"))
    })
  })
})
```
