### ISSUE TITLE
How to catch MediaStream stopped?

### ISSUE THREAD

**Issue by hnq90** [peers/peerjs#212]
Hello,
I'm implementing 2-way sharing video connection, but I don't know how to know when MediaStream stopped.

Currently, I can't not use mediaConnection.close() because it will close the stream to other peers. So I just use stream.stop() to end the stream. But peerjs don't have any api like peer.call.on("close").

Thanks in advance.

**Comment by 9thQuadrant** [comment]
conn.on(‘close’,function(){});
is working as said by <strong>luongnv89</strong>
but, how to invoke the "close" event ourselves,
like <strong>rejecting</strong> an incoming call?

**Comment by 9thQuadrant** [comment]
conn.on(‘close’,function(){});
is working as said by <strong>luongnv89</strong>
but to create that event ourselves?
i've used
	<strong>cut.addEventListener('click',peer.close(stream));</strong>
but <strong>close</strong> is taking as <strong>keyword</strong> by cordova.js

**Comment by DrakenZA** [comment]
http://cdn.peerjs.com/demo/chat.html

Why does this seem to have firefox detecting and firing leaving the 'close' event, yet i cant get it to work, nor anyone here ?

They using the same peer.js, and doing it the same way ?
