### ISSUE TITLE
Temasys Plugin

### ISSUE THREAD

**Issue by HughIsaacs2** [peers/peerjs#216]
The people at Temasys made a WebRTC plugin for Windows and Mac OS X (working in both Internet Explorer and Safari), would you guys ever consider supporting it?

https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins

**Comment by needitfast** [comment]
Well i tried running adapter.js and peer.js together, but couldnt get it to work. Is there any more information out there what exactly is needed to make them play nice and stop crashing each other?

**Comment by luongnv89** [comment]
Hello, 
It seems PeerJS does not work with Temasys plugin. This is my test on Safari, Mac OS X Yosemite 10.10.2. The error was 'browser-incompatible'.
![screen shot 2015-03-13 at 14 41 08](https://cloud.githubusercontent.com/assets/3288457/6639351/23ea8e42-c98f-11e4-9f45-487cffdaa40a.png)

**Comment by fyyyyy** [comment]
Try changing these lines in peer.js

if (!util.supports.audioVideo && !util.supports.data ) {
    this._delayedAbort('browser-incompatible', 'The current browser does not support WebRTC');
    return;
  }

**Comment by luongnv89** [comment]
@fyyyyy  Thank you for your reply.
After ignoring 'browser-incompatible' error. I could create a Peer object:
![screen shot 2015-03-13 at 15 58 49](https://cloud.githubusercontent.com/assets/3288457/6640791/e345c252-c999-11e4-80d0-01ad4d386843.png)
But still could not connect with other peer. The error I got:
![screen shot 2015-03-13 at 15 55 35](https://cloud.githubusercontent.com/assets/3288457/6640804/019fd5e4-c99a-11e4-8328-f1ad9049acc3.png)
Any more help? Thanks!

**Comment by agouaillard** [comment]
https://github.com/Temasys/AdapterJS/issues/55

**Comment by serrynaimo** [comment]
You can always use http://skylink.io/web instead of PeerJS, too ;) *hint* *hint* :)
</shameless-plug>

**Comment by ulifigueroa** [comment]
Any updates on this? Has anyone been working on this?

**Comment by agouaillard** [comment]
We haven't started yet on our side.

On Tue, Apr 21, 2015 at 3:09 AM, Ulises Figueroa <notifications@github.com>
wrote:

> Any updates on this? Has anyone been working on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peers/peerjs/issues/216#issuecomment-94543880>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by needitfast** [comment]
Working yes, got it to work properly, no :)

**Comment by ulifigueroa** [comment]
Do you have any branch or fork I can take a look at? how far have you gone?

**Comment by agouaillard** [comment]
Hi everyone,  We did a first integration. Leticia just pushed three commits yesterday about it, and open the ticket #285 for some items that might need to be addressed on peerJS side.

You should have everything there to use Temasys plugin with peerJs ;-)

Cheers.

**Comment by antonioaguilar** [comment]
Can anyone point me on the best way to start investigating some of the issues with the temasys plugin and peerjs? I'm still familiarising with peerjs ... I would like to know if some of the issues are specific to the plugin or peerjs? thanks.

**Comment by agouaillard** [comment]
It should be pretty much working right now.
You can contact temasys there:
http://skylink.io/plugin/

On Sun, Oct 18, 2015 at 5:48 AM, Antonio Aguilar <notifications@github.com>
wrote:

> Can anyone point me on the best way to start investigating some of the
> issues with the temasys plugin and peerjs? I'm still familiarising with
> peerjs ... I would like to know if some of the issues are specific to the
> plugin or peerjs? thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peers/peerjs/issues/216#issuecomment-148954200>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -
