### ISSUE TITLE
Works on home network, not on work network, even with TURN server

### ISSUE THREAD

**Issue by smorty** [peers/peerjs#219]
I have yet to deploy this on the actual web, but when serving the static files on my local ip with node, I have gotten the data channel to work great on my home network, along with the network of a development bootcamp I'm currently attending, but not at my work network. I've tried to install a fallback TURN server from XirSys (recommended by the SimpleWebRTC folks), and that seemed to be working on those networks as well, but still not on my work network. This may be a dumb question, but any thoughts on possible solutions?

Later addition: Turns out it works just fine when I'm right next to the other guy; it just doesn't work across the office. I'm thinking the only difference there would be connecting from a separate access point, which might mean having to pass through a firewall. My hypothesis is that my TURN server isn't actually working as a fallback.

**Comment by peveuve** [comment]
I can tell you one thing: I first tried to use a free Turn server from Viagenie, but it didn't solve the home connection issues for Firefox, and the mobile connections (3G) were failing as well.
Then I installed a Coturn server, which implements the latest RFC, and everything was fixed.

Coturn seems to be the reference implementation for STUN/TURN/ICE, the most up to date.
