### ISSUE TITLE
Cross-Origin Request Blocked for firefox 

### ISSUE THREAD

**Issue by SameerRathod** [peers/peerjs#220]
Hi,

I am using a self signed certificate with peerjs custom server.
It is giving me following error in firefox browser

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://111.118.237.23:9009/peerjs/112/r0c2854bevh/id?i=0. This can be fixed by moving the resource to the same domain or enabling CORS.

please help me resolving this issue 

Also if anyone can upload more detailed api documentation like 
I need some server side control over calls and who is connect and also sever can disconnect a single peer if possible please help me

**Comment by alfred-zaki** [comment]
this keeps happening to all my codepen.io pens
while it works fine in IE !
