### ISSUE TITLE
Error: Connection is not open. You should listen for the `open` event before sending messages

### ISSUE THREAD

**Issue by SameerRathod** [peers/peerjs#222]
Hi, 
I am getting this issue 
"Error: Connection is not open. You should listen for the `open` event before sending messages".

steps to regenerate is 
client A and B there are two terminals 
1) connect the chat form A to B
2) refresh the B client page 
3) Then without refreshing A reconnect to B from A 
4) Send message form A to B 
It will display the same error

Can any one give me the solution for this or please explain me why this is happening ?

**Comment by ThorsenRune** [comment]
Same problem here
