### ISSUE TITLE
Call audio  receive video 

### ISSUE THREAD

**Issue by Vahanerevan** [peers/peerjs#231]
Hi you got super api. But I cant found solution for next:
I am want to call only audio and receive video steam.
    //Caller
navigator.getUserMedia({
    audio: true
}, function(stream) {
    $('#me').prop('src', URL.createObjectURL(stream));
    var userId = $('#tid').val();
    var call = peer.call(userId, stream);
    window.existingCall = call;
    call.on('stream', function(stream) {
        $('#you').prop('src', URL.createObjectURL(stream));
    });

});
//Respondent

peer.on('call', function(call) {
    navigator.getUserMedia({
        audio: true,
        video: true
    }, function(stream) {
        call.answer(stream);
        $('#me').prop('src', URL.createObjectURL(stream));
        window.existingCall = call;
        call.on('stream', function(stream) {
            $('#you').prop('src', URL.createObjectURL(stream));
        });
    }, function(error) {
        //...
    });
});

Thank you .

**Comment by hisayan** [comment]
I have tested this problem and solved.

See the link below for further details.
https://github.com/peers/peerjs/issues/147
