### ISSUE TITLE
Serialization methods other than `binary` are not chunked, so large JSON/strings are truncated when sent over Chrome data channels.

### ISSUE THREAD

**Issue by swestwood** [peers/peerjs#234]
Repro: Use a version of http://cdn.peerjs.com/demo/chat.html with the input tag switched to a textarea (otherwise, an input tag will cause the text to be cut off when you copy-paste it in due to max char counts). Sending jquery.min.js via the textarea gets cut off on the other side when in Chrome 36 talking to Chrome 36, or Chrome 36 sending to Firefox 31. (Firefox 31 to Firefox 31 works fine, and I haven't tested other combinations.) 

The truncation of the JSON causes an error in peer.js on the receiving end, where JSON.parse() throws "Uncaught SyntaxError: Unexpected end of input." It also seems that the app then attempts to send over the second part of the JSON, which causes "Uncaught SyntaxError: Unexpected token L" (or some other character) during the parsing. The issue seems to be that large JSON needs to be fully received then recombined before attempting to parse it on the receiving end. Small JSON messages still work as expected.

**Comment by afrokick** [comment]
Workaround: using binary type to transfer large objects.

Please, open new issue if any problem will occur
