### ISSUE TITLE
Chrome Mobile / Firefox Desktop freezing video

### ISSUE THREAD

**Issue by dnish** [peers/peerjs#237]
Hello everybody,
got a problem with peerJS and Chrome Mobile (latest version 36.0.1985.135 - Android 4.4.2) and FireFox (version 31.0 - Windows 8.1). After connecting to each other, the videos on Chrome Mobile freeze (both -  local camera and streamed one). On Firefox, the local camera video works fine, but the streamed video of Chrome Mobile stops working (picture is frozen).

I've tested it with your demo (Simple Videochat) and my own application. Are there any fixes/workarounds for that issue?!

**Comment by minusplusminus** [comment]
Hi, I have the same issue with nw.js ( current release version) .  Sometimes the screen becomes green and it sometimes freezes. I'm checking the framerate of the video. When it drops to zero I close, disconnect and destroy to get things working again. Is there a quick tweak for this?
