### ISSUE TITLE
conn.open flag remains false even for open connections

### ISSUE THREAD

**Issue by Tomas-M** [peers/peerjs#240]
When I test things locally in multiple tabs, everything seems to work just fine. But when I test with friend who is in different network, I noticed a problem. When my computer is the original peer (server) and connection is opened (received) from my friends computer (client), it looks OK on my side, but the conn.open flag remains false on my friends computer (client) even if the connection was successful. The problem is that in this state the conn.on('open') is never called on the client.

It is probably something related to network, since if we try it in opposite direction (my friend is initial peer and I am client peer), then it works just fine and conn.on('open') gets called properly.

FYI, the on('error') shows nothing neither for conn nor for peer (is never called).
Maybe a bug...

**Comment by rafael-sobek** [comment]
@michelle Do you have any updates on this issue?

I have the same situation. The connection is on both sides open. But the open function wasn't triggered on one browser.

**Comment by abardik** [comment]
The same in 2017. You need to play with kind of flags/timeouts/negotiation to avoid a data flow before the connection is established.

**Comment by afrokick** [comment]
i think it's already fixed. Let me know if it happens again.

**Comment by lagcamgc** [comment]
Hello, i'm facing a similar issue

**Comment by afrokick** [comment]
@lagcamgc are you using the latest version 1.0.0?

**Comment by pcvengros** [comment]
same here.....

**Comment by lagcamgc** [comment]
> @lagcamgc are you using the latest version 1.0.0?
> Do you mean peer's event or mediaConnection's event?

mediaConnection open status for one of the sides is false and the other one true, also one of the sides is not entering on the peer.on('connection'...

**Comment by afrokick** [comment]
There is no 'open' event for mediaConnection https://peerjs.com/docs.html#mediaconnection-on
initiator side: open = true after create a call
another side: open = true after answer the call

But we can add it

peer.on('connection') (and peer.on('call')) executes on callee's side only.

**Comment by lagcamgc** [comment]
> There is no 'open' event for mediaConnection https://peerjs.com/docs.html#mediaconnection-on
> initiator side: open = true after create a call
> another side: open = true after answer the call
> 
> But we can add it
> 
> `peer.on('connection')` (and `peer.on('call')`) executes on callee's side only.

Sorry the actual piece of code is this one, i was thinking on another name when i wrote it on the previous post:

``` 
Object.keys(members).forEach(memberUid => {
        connections.push(peer.connect(memberUid))
        peer.on('connection', (conn) => {
          console.log('Connection done...')
          connectionsOpened.push(conn)
          // here we can receive data from each connection
          conn.on('data', (data) => {
            // actualizar store
            console.log('Data comming...')
            console.log(data)
          })
      })
    }) 
``` 

Also when you say
> executes on callee's side only.

You mean only one side detects the connection?
Also i tried this:
``` 
Object.keys(members).forEach(memberUid => {
      let conn = peer.connect(memberUid)
      connections.push(conn)
        connectionsOpened.push(conn)
        // here we can receive data from each connection
        conn.on('data', (data) => {
          // actualizar store
          console.log('Data comming...')
          console.log(data)
        })
    }) 
``` 
And it also does not get there

**Comment by afrokick** [comment]
Could you please check my example https://gist.github.com/afrokick/06f30a550008132c4aa5cf3fe987238d

Is it work for you?

**Comment by lagcamgc** [comment]
> Could you please check my example https://gist.github.com/afrokick/06f30a550008132c4aa5cf3fe987238d
> 
> Is it work for you?

Actually no, it's weird, i make work my code putting more listeners

```
    // block 1
    connection.on('open', () => {   
      console.log('Connection done...')
      // here we can receive data from each connection
      connection.on('data', (data) => {
        console.log('Data comming...')
        console.log(data)
        console.log(data.url)
        avatarImage[data.uid] = data.url
      })
    })
    // block 2
    peer.on('connection', (conn) => {
      connections.push(conn)
      console.log('Connection 2 done...')
      // here we can receive data from each connection
      conn.on('data', (data) => {
        console.log('Data 2 comming...')
        console.log(data.url)
        avatarImage[data.uid] = data.url
      })
    })
```

Is entering in the on data of the second block but if i remove block one it does not work

**Comment by afrokick** [comment]
Could you please provide a test repo with your code? I'll review it and give you a more precision answer.

**Comment by lagcamgc** [comment]
> Could you please provide a test repo with your code? I'll review it and give you a more precision answer.

Hello sorry fot the delay i have been working and actually it was a flow problem
Thanks for your help

Also i'm wondering something, just a quick question: if i need multiple instances of peerjs server do someone already handle that because if i'm going to manage thousands of users i think that just one peerjs server can not handle it, is there someone that designed an orchestrator or a gateway to communicate the servers or do you have a suggestion about it?

**Comment by kidandcat** [comment]
You are ok with just one instance. PeerServer is in charge of establish the communication only, then everything is Peer to Peer (server does nothing after the initial communication setup)

**Comment by maxpavlov** [comment]
@lagcamgc can you please describe what kind of flow problem that was? I am fighting the same problem right now, it used to work flawlessly with pre v1, but now on fast networks connection works perfectly but on remote a bit slower ones, a connection is fired on one peer, but "open" isn't being fired on the other, the one that has connected.

**Comment by lagcamgc** [comment]
@maxpavlov hello sorry for not replying in a lot of time, you still having the issue?if so please let me know to look at my previous code

**Comment by afrokick** [comment]
Please open new issue if it still exists in 1.0.4+ version

**Comment by siddhantkushwaha** [comment]
Been stuck with this issue. 

call.open remains false

`    console.log(`New peer [${userId}].`)
    const conn = peer.connect(userId)

    setTimeout(() => {
        console.log('Tried to connect to', userId, conn.open)
    }, 5000)

    conn.on('open', () => {
        console.log(`Connection established with peer [${userId}].`)
       
        allPeers.add(userId)

        conn.send({'event': 'init', 'userId': myUserId})

    })`
