### ISSUE TITLE
disable Socket xhr in client

### ISSUE THREAD

**Issue by simon-weber** [peers/peerjs#248]
I'm looking to use peer.js with my own custom backend, and I'd like to rely only on websockets for the initial signaling.

It looks like the Peer will disconnect immediately if the long-poll endpoint 404s (through `onerror`). If I comment out the call to `_startXhrStream`, though, everything works fine.

Would it be reasonable to either:
- have the client handle a 404 on the endpoint gracefully (ie, fall back to the websocket), or
- let the use of xhr/websockets be configurable from the Peer

If one/both of these options sound good I can work on a PR, but fair warning that my javascript chops are pretty weak =)

**Comment by afrokick** [comment]
xhr was removed
