### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by ericz** [peers/peerjs#26]
See discussion in #23 
- [ ] Tokens are generated with Math.random() and thus have poor entropy
- [ ] Server deletes `client`s immediately upon disconnect, preventing possibility of reconnection under same id/token.
- [ ] HTTPS support needs to be deployed due to possible snooping of id/token in request URIs

**Comment by D1plo1d** [comment]
https://github.com/d1plo1d/graphql-things resolves these security issues by using a cryptographic handshake to establish new connections.

I've created an issue to look into merging the two projects here: https://github.com/peers/peerjs/issues/547
