### ISSUE TITLE
TypeError: undefined is not a function on peer.connect

### ISSUE THREAD

**Issue by DanieleSassoli** [peers/peerjs#263]
Hy,
it's my first experience with peerjs. 
this is my code 
    var peer = new Peer({key: myKey}); 
    var conn = peer.connect('editor-vaComeVibraEEE');
    conn.on('open', function(){
        conn.send('hi!');
    });

the problem is that when I get to call peer.connect I get a TypeError: undefinined is not a function, with further investigation I found out that the error comes from Object.Negotiator._startPeerConnection and I can't understand what I'm getting wrong. Somebody knows why this error is fired?
thank's in advice

**Comment by luongnv89** [comment]
Could you post the code with the error log?

**Comment by DanieleSassoli** [comment]
Hy,seems the problem has nothing to do with PeerJs, I was using it with Adobe InDesign, wich has no WebRTC support, solved migrating to fayejs, thank's for the reply and sorry that I didn't close the issue.
