### ISSUE TITLE
disconnect on browser crash

### ISSUE THREAD

**Issue by sherwud** [peers/peerjs#268]
Hi, there is one not pretty obvious issue with your PeerServer.
How can connected user get a response about disconnecting of his peer?
Is there any observing methods to listen to peer disconnect, in other words?

server:

var PeerServer = require('peer').PeerServer;
var server = PeerServer({port: 9002, path: '/myapp', proxied: true});

server.on('connection', function(id) {
   console.log('connect ' + id)
});
server.on('disconnect', function(id) {
   //When the browser crash happens, this event fires on server side, but on client side the event isn't     //fired.When the browser crash happens, this event fires on server side, but on client side the event //isn't fired.
   console.log('disconnect ' + id);
});

client:

var peer = new Peer(userId, {host: 'localhost', port: 9002, path: '/myapp'});

```
  peer.on('open', function(id) {
     console.log('My peer ID is: ' + id);
  });
  peer.on('connection', function(conn) {
     console.log("peer " + conn.peer + " connected for me!");
  });
  peer.on('disconnected', function() {
     console.log("peer disconnect from me!");
  });
  peer.on('close', function() {
     console.log("connection was closed!");
  });
  peer.on('error', function(err) {
     console.log("ups.. something wrong!");
     console.log(err);
  });

  var conn = peer.connect(adversaryId);

  conn.on('open', function() {

     conn.on('data', function(data) {
        console.log('Received', data);
     });
  });
```

**Comment by luongnv89** [comment]
I think it will be better to listen the "DataConnection" event: http://peerjs.com/docs/#dataconnection-on and "MediaConnection" event: http://peerjs.com/docs/#mediaconnection-on rather than listen the peer event in your case.

**Comment by fyyyyy** [comment]
That doesnt fire either when the browser is closed or crashes
