### ISSUE TITLE
Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDINITIATE

### ISSUE THREAD

**Issue by fyyyyy** [peers/peerjs#269]
I guess this is just a warning and can be ignored, peen.on('error'). It probably happens if the caller disconnects, and then the called person tries to call back.

``` js
 step3 MediaConnection {options: Object, open: true, type: "media", peer: "nQN66DkJpQZkwl-tAAAA", provider: Peer…}
peer.js:1476 PeerJS:  ERROR Error: Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDINITIATE
Video.js:43 Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDINITIATEVideo.js:43 (anonymous function)peer.js:1802 emitpeer.js:1073 Peer.emitErrorpeer.js:626 (anonymous function)
```

**Comment by allenfantasy** [comment]
We have been using peerjs for a while and found this issue too. Actually when this error occurs, both side of clients are still working good.

**Comment by luongnv89** [comment]
+1 for fixing this issue

**Comment by temporafugiunt** [comment]
+1 for fixing this, we see it too but it doesn't affect establishing a valid connection.

**Comment by afrokick** [comment]
reopen it please if still exists
