### ISSUE TITLE
Single offer for media and data connections

### ISSUE THREAD

**Issue by ignasbernotas** [peers/peerjs#270]
We're having issues with Android/iOS due to multiple offers sent for media and data conenctions. We basically can use either one, but when trying to send the second offer the SDP cannot be parsed by Android/iOS clients (I'm not sure about the internals of Java/ObjC, but that's what they told me).

Is it possible to merge the offers into one? If so, how?

**Comment by fyyyyy** [comment]
is there actually a way to make webrtc work on ios ?

**Comment by ignasbernotas** [comment]
We managed to do it using Apprtc examples. Though video quality sucks (there seems to be an internal bandwidth limit set, so we're trying to bypass that).
