### ISSUE TITLE
addIceCandidate called without success/failure callbacks. This is deprecated, and will be an error in the future. 

### ISSUE THREAD

**Issue by fyyyyy** [peers/peerjs#271]
Just letting you know, firefox soon expects callbacks.

`addIceCandidate()`

addIceCandidate (RTCIceCandidate candidate, Function successCallback, RTCPeerConnectionErrorCallback failureCallback);

> The addIceCandidate() method provides a remote candidate to the ICE Agent. In addition to being added to the remote description, connectivity checks will be sent to the new candidates as long as the "IceTransports" constraint is not set to "none". This call will result in a change to the connection state of the ICE Agent, and may result in a change to media state if it results in different connectivity being established.

**Comment by afrokick** [comment]
works via promise
