### ISSUE TITLE
XHR signalling fails on newer browsers

### ISSUE THREAD

**Issue by alanmshelly** [peers/peerjs#273]
We noticed this bug when working in an environment that doesn't allow websockets. An update to browsers (libjingle?) seems to have killed the peerjs implementation of xhr signalling. I tested xhr signalling about a year ago so I know it used to work. Also confirmed it was working in Firefox ESR 31.5.0.

If anyone has any ideas of the cause, please let me know!

Steps to reproduce:
1. comment out the line `this._startWebSocket();` in `Socket.prototype.start()`
2. open examples/videochat in 2 tabs
3. call one tab from the other

Result:
- signalling occurs (candidates/offers/answers being sent/received) but peerConnection isn't established
- the error `Failed to set local offer sdp: Called in wrong state: STATE_RECEIVEDINITIATE` is occasionally thrown (Chrome only)
- sometimes the PC is established and the video is displayed as normal (timing problem?)

Tested on:
- All tests done on OSX Yosemite
  - Chrome 40.0.2214.115
  - Firefox 35.0.1, 36.0
  - Firefox ESR 31.5.0 (Bug not present)

**Comment by michelle** [comment]
Thanks for the detailed report.

Michelle

**Comment by alanmshelly** [comment]
This seems to have been fixed in chrome 41 so I'm thinking it was a browser bug.
I'm watching Firefox currently to see if it gets fixed there as well.

**Comment by prophittcorey** [comment]
This seems to still be an issue. It happens randomly even on Chrome 46.
