### ISSUE TITLE
Change the default Codec

### ISSUE THREAD

**Issue by wowpatrick** [peers/peerjs#276]
Is there any way to force a specific codec (in my case PCMA) in PeerJS as described in [this Stackoverflow answer](http://stackoverflow.com/a/26932385/461992). I'm sure this is possible, I'm just not quite sure where in the PeerJS code these changes have to be made.

**Comment by nadavami** [comment]
This would be incredibly useful to have.

**Comment by afrokick** [comment]
You can use sdpTransform option to execute any mutator of sdp before create offer. https://github.com/peers/peerjs/commit/14ff7f80ad62adb031c55ab5a1b75e6e3ca0fd64
