### ISSUE TITLE
Failed to construct 'RTCIceCandidate' on Chrome 43 (Canary)

### ISSUE THREAD

**Issue by mccxiv** [peers/peerjs#277]
Hi friends, seems like peerjs isn't working at all on the newest version of Chrome for me.

Same error in my project and using the simple chat demo at http://cdn.peerjs.com/demo/chat-old.html

```
PeerJS:  Socket open
PeerJS:  Creating RTCPeerConnection
PeerJS:  Listening for ICE candidates.
PeerJS:  Listening for `negotiationneeded`
PeerJS:  Listening for data channel
PeerJS:  Failed to setRemoteDescription,  Failed to parse SessionDescription.  
Uncaught TypeMismatchError: Failed to construct 'RTCIceCandidate': The 'candidate' property is not a string, or is empty.
```

screenshot
![ss](http://i.imgur.com/I0uNAcU.png)

I'm on Windows 8.1, Chrome 43.0.2347.0 canary (64-bit)
Wish I could be of help but I don't know much about the webrtc internals

**Comment by fyyyyy** [comment]
maybe see #271
