### ISSUE TITLE
Issue of video playing when running peerJs in internet

### ISSUE THREAD

**Issue by rebhisaid** [peers/peerjs#283]
I started looking ad playing with peerjs and I tried to make a simple video calling application.

I tested it locally and it works.. then I deployed it to an url over internet to make a test.. when I use two different tabs in Chrome it works.. BUT when I tell a friend who is in another network to connect with me in video calling, I can see that there is a connection established between us but the video is not playing. There is black box instead of the video and there is no error message..

What can be the problem please?

**Comment by luongnv89** [comment]
Hello @rebhisaid 
I think you're facing the problem with NAT. You can read more about NAT/ICE and TURN/STURN server here: http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/?redirect_from_locale=fr .
Hope this help.

**Comment by needitfast** [comment]
AS luingnv89 said, im assuming you just didnt add any stun servers like so:

config: {'iceServers': [
				{ url: 'stun:stun.ekiga.net' },
				{ url: 'stun:stun1.l.google.com:19302' },
				{ url: 'stun:stun2.l.google.com:19302' },
				{ url: 'stun:stun3.l.google.com:19302' },
				{ url: 'stun:stun4.l.google.com:19302' },
				{ url: 'stun:stun01.sipphone.com' },
				{ url: 'stun:stun.l.google.com:19302' }
				]}

**Comment by ulifigueroa** [comment]
Also there are some networks that even using STUN and TURN servers you will face problems streaming the media. This might be cause because UDP is blocked in some way, there are some third parties like `xirsys.com` that support TCP for TURN protocol as a fallback mechanism for those networks.
