### ISSUE TITLE
Communication doesn't work in every 4G network

### ISSUE THREAD

**Issue by QuentinVolant** [peers/peerjs#284]
Hi,
for my project, a computer (with classic wifi) have to communicate with another user who is with a mobile. The mobile uses 4G network to establish the connection. The problem is that the communication works with an operator (supplier of 4G) but with another, that doesn't function. So why peerjs works or doesn't work according to the operator ? 
When it doesn't work, the communication is stopped at the establishment of the Data Channel connection. Currently I haven't Turn server, it's the problem ?

**Comment by dhaltmayer** [comment]
Most likely, your problem is lack of turn server.

**Comment by QuentinVolant** [comment]
Ok, I will try to install a turn server and I will see if that works.
Thanks

**Comment by ulifigueroa** [comment]
Or try using some third party TURN server that are ready to use like: http://xirsys.com or https://www.twilio.com/stun-turn

**Comment by ncri** [comment]
@ulifigueroa How would one use a sercvice like http://xirsys.com with peer.js?

**Comment by ncri** [comment]
Ah, never mind, found this: "You can pass a TURN server into the Peer object options."

**Comment by ncri** [comment]
In case anyone else is interested: http://xirsys.com/peerjs/

**Comment by QuentinVolant** [comment]
It works in every 4G network with the Turn server provided by http://xirsys.com.
Thanks
