### ISSUE TITLE
media + data type connection between peers?

### ISSUE THREAD

**Issue by boynet** [peers/peerjs#287]
I want to open video chat between peers + sending data. if I open 2 diffrents connections sometimes the second connection fail with error of:

```
PeerJS:  onnegotiationneeded triggered when not stable. Is another connection being established?
```

**Comment by fortinmike** [comment]
No answer? I'm also interested in knowing more about this (e.g. what's the recommended approach?).

From the peerjs website it seems that data and media connections are two completely separate things.

I had assumed that a media connection also allowed sending arbitrary data without having to maintain another completely separate connection.
