### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hermanocabral** [peers/peerjs#290]
subject says it all.

**Comment by madwill** [comment]
Yeah i think it is...

We just launche a refactoring for rtcMultiConnection. 

Damn i wish i had looked at latest commit 2 months ago. But peerJs sugar api was so fine i drank the cool aid...

**Comment by madwill** [comment]
If you find any other self hosted worth while lib out there, Please share them.

**Comment by madwill** [comment]
Could it be that is has been absorbed by skyway ?

https://github.com/nttcom/peerjs

**Comment by hermanocabral** [comment]
I think they're doing what I've seen most people do: fork this and move on.

**Comment by EvandroZanatta** [comment]
Anyone except the @nttcom has a fork where it contributes to the project

**Comment by kanaka** [comment]
I've asked the authors via a [different channel](https://twitter.com/bus_kanaka/status/641077490899750912) to confirm the status of peer/peerjs

**Comment by kanaka** [comment]
Hi @michelle, I saw you merged in https://github.com/peers/peerjs/pull/308 an hour ago. Would you mind commenting on the official status of PeerJS? There hasn't been much activity for a while and https://github.com/nttcom/peerjs seems to be the main working fork right now. Thanks!

**Comment by michelle** [comment]
I've been looking to find time to rewrite large portions of this project,
given with the current state of WebRTC a lot of the hacks we had in place
are no longer necessary.

Michelle

**Comment by khankuan** [comment]
+1

**Comment by EvandroZanatta** [comment]
:+1:

**Comment by ISNIT0** [comment]
+1

**Comment by madwill** [comment]
+1 !

**Comment by doppio** [comment]
+1 :)

**Comment by jure** [comment]
This is an exceptional project, @michelle and @ericz, and I wholeheartedly encourage you to continue supporting it. Let us know what we can do to help!

**Comment by cesconix** [comment]
+1

**Comment by sequoiar** [comment]
+1

**Comment by mattvleming** [comment]
@michelle Any chance you have time to open an issue detailing the hacks that could use refactoring so perhaps others can step in?

**Comment by madwill** [comment]
I think they moved on, i made some changes to add vp9 and bitrate control to peerjs but we are planning on moving to another lirabry like simpleRTC or appRTC

**Comment by marcusreese** [comment]
Thanks @kidandcat for starting to revive this! (And thanks to previous maintainers for their work, too.)
https://github.com/peers/peerjs/issues/427https://github.com/peers/peerjs/issues/427
https://github.com/peers/peerjs/commits?author=kidandcat

**Comment by kidandcat** [comment]
Thank you too! I'm doing it because I saw this amazing community hasn't surrender even after 2 years aimlessly. Also I couldn't do it without all your support.

I'm gathering few people to help with website, twitter, etc. And I want to do a re-launch with a fresh website and start moving everything again. Meanwhile I'm preparing everything (merging PRs, fixing bugs and so on).
