### ISSUE TITLE
Connection.on("open") never gets called while Peer.on("connect") gets called

### ISSUE THREAD

**Issue by senegalo** [peers/peerjs#293]
Okay ... here is how to reproduce this on the official peer.js chat app "http://cdn.peerjs.com/demo/chat.html"

Open 2 chat windows on different browsers...

1) in the first window insert a breakpoint on line 47 which is the first line in the connect function that will be called once Peer.on("connection") is called.

2) connect from the second window to the first "the one with the breakpoint".

3) one you're stopped at the breakpoint hit resume on the first window and the second window will never have the Connection.on("open") fired ! while the first would have a connection opened !

i am not sure why this happens ! any help ?

**Comment by senegalo** [comment]
it's a bug in chrome ... am sorry :)

seems like if you open a datachannel from one browser to the other ... if there is a callback on the other side that takes too long to execute the datachannel readyState gets stuck on connecting... didn't find any work around yet to that ... 

Using Chrome 43.0.2357.81 (64-bit) linux

**Comment by maxpavlov** [comment]
I experience exactly the same thing as described with 1.0.0.0
