### ISSUE TITLE
Error: ID is taken: when internet is disconnected and reconnected again.

### ISSUE THREAD

**Issue by pratikraj26** [peers/peerjs#294]
I got following error message when i try to connect to the peer server when the internet is reconnected after disconnection. I am using a custom peer id for the peer connection.

PeerJS: Socket open
PeerJS: ERROR Aborting!
PeerJS: ERROR Error: ID `323` is taken
PeerJS: Socket closed.
PeerJS: ERROR Error: Lost connection to server.

I think the server keeps the id for too long. Is there any way to forcefully destroy the connection with specific peer id ?

**Comment by prophittcorey** [comment]
I would investigate the `peer.destroy()` method.

**Comment by forrana** [comment]
looks like dub of [224](https://github.com/peers/peerjs/issues/224)

**Comment by LucaColombi** [comment]
Same problem after 4 years, I suppose there is a maintainance problem :|

Is there a id timeout or a way to stimulate the real taken status of an ID?

**Comment by kidandcat** [comment]
duplicate of #224
