### ISSUE TITLE
Get Lost Connection using Heroku

### ISSUE THREAD

**Issue by nofpowells** [peers/peerjs#295]
Hello, i'm using heroku for my app.

But i get disconnect all time.

Try : http://estagiopeerjs.herokuapp.com/

Can help me plz?

**Comment by yadavdev** [comment]
Check logs of the application from heroku. If you have command line tool from heroku installed on your system use "heroku logs -t" from the the app repository folder. The common reason on heroku and which I faced was ###"error: H15 idle timeout"### in which heroku stops a keep-alive connection if idle for 15 seconds and hence the above error.

**Comment by Masterxilo** [comment]
And what do we do to fix this? Can peerjs send a keepalive ping/signal? Does it help to use a data connection simultaneously?

**Comment by Masterxilo** [comment]
Can we ignore the error of losing connection to the websocket of the signaling server?

**Comment by kidandcat** [comment]
PeerJS automatically send a websocket ping, but for this use case where is heroku who kills the app, you will need to implement your own kind of keep alive using a setInterval or similar

**Comment by Masterxilo** [comment]
Well our router seems to kill the websocket connection after 1 min as well,
no heroku... The ping/keepalive fixed this.

Jairooo <notifications@github.com> schrieb am Do., 4. Okt. 2018, 16:18:

**Comment by sameernafdey** [comment]
> PeerJS automatically send a websocket ping, but for this use case where is heroku who kills the app, you will need to implement your own kind of keep alive using a setInterval or similar

This is true, and I did the same few weeks back.

Don't remember where I got this inspiration from but here is how I achieved it in Angular app deployed on Heroku.

```
class PeerJSHeartbeater {
  private timeoutID: any;
  private self: PeerJSHeartbeater;
  constructor(private peer: any) {
    this.start();
  }
  start() {
    if (this.timeoutID === undefined) {
      this.beat();
    }
  }
  stop() {
    clearTimeout(this.timeoutID);
    this.timeoutID = undefined;
  }
  beat() {
    this.timeoutID = setTimeout(() => {
      this.beat();
    }, 20000);
    if (this.peer.socket._wsOpen()) {
      this.peer.socket.send({ type: 'HEARTBEAT' });
    }
  }
}
```
elsewhere..

```
this.peer = new Peer({
      host: location.hostname,
      port: location.port || (location.protocol === 'https:' ? 443 : 80),
      path: 'peer-server',
      config: {
        iceServers: [
          { url: 'stun:stun.l.google.com:19302' },
          { url: 'stun:stun1.l.google.com:19302' },
          { url: 'stun:stun2.l.google.com:19302' },
          { url: 'stun:stun3.l.google.com:19302' },
          { url: 'stun:stun4.l.google.com:19302' }
        ]
      }
    });
this.peer.on('open', id => {
      if (this.peerServerHeartbeater === undefined) {
        this.peerServerHeartbeater = new PeerJSHeartbeater(this.peer);
        this.peerServerHeartbeater.start();
      }
    });
```

**Comment by kidandcat** [comment]
Heroku has a timeout, you will need to implement your own "ping-pong":
https://stackoverflow.com/questions/22847581/heroku-websocket-connection-timeout

**Comment by jamalhassouni** [comment]
@kidandcat 
In fact, I do not understand, I found this [Connection pinging](https://github.com/peers/peerjs/issues/278)
but I did not understand where I should modify my code
