### ISSUE TITLE
Does it have network limitation？ seems only work within LAN

### ISSUE THREAD

**Issue by zy532410321** [peers/peerjs#298]
Hi, I found that running the demo http://cdn.peerjs.com/demo/chat.html
If I open two link on LAN, they can connect and chat with each other
But if A connect somebody else B, A's status is "disconnect" and B's status is connecting. 
Even A exit, B still displays the connection.
So does this have network limitations?
Thanks.

**Comment by luongnv89** [comment]
Probably you are facing the problem with **NAT/STUN/TURN**. 

To answer your question: `peerjs` does not have network limitation.

You can read more about **NAT/STUN/TURN** here: [WebRTC in the real world: STUN, TURN and signaling](http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/)

**Comment by dhaltmayer** [comment]
That was my thought, too, but the demo makes use of a stun/turn server,
right?

**Comment by luongnv89** [comment]
Yes, the demo is using a simple default configuration for STUN:
```javascript
 { 'iceServers': [{ 'url': 'stun:stun.l.google.com:19302' }] }
```
But there are some cases we need more complex configuration. Again you can have more information in the post I have referenced.

Hope this help!

**Comment by 9thQuadrant** [comment]
is there a TURN server for windows right now..
please specify a link if exists
