### ISSUE TITLE
FireFox version 40

### ISSUE THREAD

**Issue by jigarrdesai** [peers/peerjs#299]
Does it support firefox 40

**Comment by botto** [comment]
Any reason it shouldn't?

**Comment by pculka** [comment]
yes, there is a reason, peer connection object is undefined in the client lib on FF40 onwards
but there should be a fix in the latest merge I think, need to test it out

**Comment by pculka** [comment]
the fork in nttcom of peerjs has working FF40 merge btw.

**Comment by sjovanovic** [comment]
This worked for me:

Around line 555 of peer.js	
replace:
```
Negotiator._makeOffer(connection);

```

with:
```
setTimeout(function(ev){ Negotiator._makeOffer(connection); }, 1);

```

**Comment by hoanvuso** [comment]
good job @sjovanovic . Thanks for your helo

**Comment by goks** [comment]
Thanks for the help :) @sjovanovic

**Comment by NerdsvilleCEO** [comment]
What is the process to get this merged into the npm module?
