### ISSUE TITLE
Websocket Invalid frame header Error with local PeerJS Server

### ISSUE THREAD

**Issue by jhclaura** [peers/peerjs#300]
Hi, 

I succeed in using PeerJS with cloud server to make video conference thing, along with the websocket library [ws](https://github.com/websockets/ws). Now I tried to setup a local PeerJS Server, following the instruction from "Combining with existing express app" [here](https://github.com/peers/peerjs-server), but It didn't work and things acted weirdly. Below are my codes:

-- Server --
```javascript
//SET_UP
var express = require('express');
var app = express();
var ExpressPeerServer = require('peer').ExpressPeerServer;
var options = {
    debug: true
};
var http = require('http');
var server = http.createServer(app);
var port = process.env.PORT || 9000;

app.get('*', function(req, res){
	res.sendFile(__dirname + req.url);
});
app.use('/peerjs', ExpressPeerServer(server, options));

server.listen(port);

//Websocket
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer( {'server': server} );

wss.on('connection', function(ws){
	ws.on('message', function(data){
		// ...
	});

	ws.on('close', function(){
		// ...
	});

});
```

-- Client --
```javascript
peer = new Peer('123abc', { host: 'localhost', port: 9000, path:'/peerjs', debug:true});

// Get an ID from the PeerJS server		
peer.on('open', function(id) {
	console.log('My peer ID is: ' + id);
 
	// Then connect to the socket server						
	connectSocket();
});
```

And this is what I got when I open webpage http://localhost:9000/index.html.
```
PeerJS:  Socket open
WebSocket connection to 'ws://localhost:9000/peerjs/peerjs?key=peerjs&id=123abc&token=i1nay3ueh3tprpb9' failed: Invalid frame header
PeerJS:  Socket closed.
PeerJS:  ERROR Error: Lost connection to server.
```

It seems the PeerJS socket was connected once but shortly disconnect after. I guess it's something with *localhost* but I don't know what's wrong. And it still happened if though I comment out my websocket server. Couldn't figure out why. Please advice with any ideas and feedback. Thanks!

**Comment by jhclaura** [comment]
Solved it! Should create two servers for each websocket with different port.

**Comment by Maykonn** [comment]
I'm having the same issue. But I not understant your solution. Can you explain better?

**Comment by jhclaura** [comment]
What caused the problem, in my case, was that I used two servers with one port - 9000.
That made PeerJS socket connected once but shortly disconnect after.

So the solution, in my case, is assigning different ports for different servers: port 7000 for main server, port 9000 for PeerJS server.

**Comment by Maykonn** [comment]
Thanks for your reply.
My problem is another: WSS connection not working.

**Comment by shivarajnaidu** [comment]
Mee to having same issue .. wss not connecting

**Comment by perymerdeka** [comment]
if using typescript, does it has the same solution?

**Comment by VisaAksnes** [comment]
My problem is that I can't use different door, heroku doesn't allow :X
