### ISSUE TITLE
Accessing http://cdn.peerjs.com/0.3/peer.js gives 404

### ISSUE THREAD

**Issue by looopTools** [peers/peerjs#302]
Not exactly a bug with PeerJS, but I get a 404 error, when trying to include as script or downloading the script 

http://cdn.peerjs.com/0.3/peer.js

**Comment by jvlobo** [comment]
I've just realized of that too. I hope they can fix it soon :/

**Comment by thewheat** [comment]
I'd suggest using the fork at https://github.com/nttcom/peerjs 
Things seem to work out of the box from their site.

**Comment by KensakuKOMATSU** [comment]
Yep, our branched peerjs works( https://skyway.io/dist/0.3/peer.min.js ). It is now independent with github.com/peerjs, for example, Adapter.js works well with ;-)

Not fully tested yet, I guess our branch-code works with peerjs-server. I hope it'll help you all.

For more detail, check our web website ( skyway: http://nttcom.github.io/skyway/en/ )

**Comment by MichalPaszkiewicz** [comment]
Would be good to update the guide

**Comment by jvlobo** [comment]
Is the main peerjs project dead???

**Comment by KensakuKOMATSU** [comment]
I'm not sure. Only info is that there're no commit since 11th Jan.

https://github.com/peers/peerjs/graphs/commit-activity

**Comment by monaka** [comment]
It's just an workaround. But works well.
https://cdn.rawgit.com/peers/peerjs/master/dist/peer.min.js

**Comment by abioneperhobby** [comment]
original peer.js still broken.
i tried to use @KensakuKOMATSU fork but api registration is totally japanese.
so i'm using the link given by @monaka and seems to works.

**Comment by yusuke84** [comment]
@abioneperhobby 

> i tried to use @KensakuKOMATSU fork but api registration is totally japanese.

I'm a skyway development team member.
In around mid-December, we plan to prepare registration site in English.

**Comment by MichalPaszkiewicz** [comment]
+1 Nice!
