### ISSUE TITLE
Peer.js via https

### ISSUE THREAD

**Issue by SandeepSagar577** [peers/peerjs#307]
Good morning i used peer.js in my application.

then i hosted in http it worked fine.
but when i hosted the same application in https its not working i changed all http:// to https://
still I'm getting this error please help.

https://0.peerjs.com:9000/lwjd5qra8257b9/id?ts=14422229464520.08810925693251193 
Failed to load resource: net::ERR_CONNECTION_CLOSED
VM99:1510 PeerJS:  ERROR Error retrieving ID undefined
VM99:1510 PeerJS:  ERROR Aborting!
VM99:1510 PeerJS:  ERROR Error: Could not get an ID from the server.
VM99:1510 PeerJS:  ERROR Error retrieving ID XMLHttpRequestProgressEvent
VM99:1510 PeerJS:  ERROR Aborting!
VM99:1510 PeerJS:  ERROR Error: Could not get an ID from the server.

then i loaded the peer.js from this site then i'm getting this error

<script src="https://cdn.rawgit.com/peers/peerjs/master/dist/peer.min.js"></script>

Mixed Content: The page at 'https://example.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://0.peerjs.com:9000/lwjd5qra8257b9/id?ts=14422252934050.2791964877396822'. This request has been blocked; the content must be served over HTTPS.

**Comment by prophittcorey** [comment]
I am unsure about peerjs.com, but you cannot mix http and https. If you run peerjs-server on your own machine on port 443 you can then use it over https.
