### ISSUE TITLE
Unauthorized POST requests during signalling!

### ISSUE THREAD

**Issue by cggaurav** [peers/peerjs#31]
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1
POST http://0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate 401 (Unauthorized) 0.peerjs.com:9000/byuxn9ec1r4fgvi/sender/cn8n9tcwppop3nmi/candidate:1

**Comment by RamyaAshika** [comment]
Any update on this? Facing same issue?

**Comment by RamyaAshika** [comment]
How to do that @laike9m Please let me know.I'm facing so much of struggle because of this. Can you please help me on this?

**Comment by laike9m** [comment]
> How to do that @laike9m Please let me know.I'm facing so much of struggle because of this. Can you please help me on this?

It's been a long time since I used peerjs last time. Sorry I'm not able to help you.

**Comment by HanustaviraGA** [comment]
Still have the same issue, any updates ?

**Comment by jonasgloning** [comment]
This issue was opened in 2013. A lot has changed since then, and you probably  do not have the same issue @HanustaviraGA. If you have problems, open a new issue with a detailed description.
