### ISSUE TITLE
CDN links are inactive

### ISSUE THREAD

**Issue by zhirzh** [peers/peerjs#312]
CDN links listed on http://peerjs.com/ give 404
http://cdn.peerjs.com/0.3/peer.js
http://cdn.peerjs.com/0.3.14/peer.min.js

**Comment by jimaek** [comment]
You can use http://www.jsdelivr.com/projects/peerjs

**Comment by zhirzh** [comment]
Well, I simply downloaded the raw files from github, but acquiring the files is not the issue. The problem is dead links on website, which need to be replaced.

**Comment by abrkn** [comment]
:+1:

**Comment by bFraley** [comment]
There's numerous 'dead' links on the website right now. I'd like to help if no one has time or...?
-Thanks
