### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by tsl143** [peers/peerjs#314]
All the demos and downloads lead to 404

Eg: 
![screenshot from 2015-11-05 17 38 58](https://cloud.githubusercontent.com/assets/5318732/10967934/2065b5b6-83e4-11e5-80b0-cdf2a8026e25.png)

**Comment by AkirAssasin** [comment]
Is the peer.min.js located in /dist/ folder usable?

**Comment by tennisonchan** [comment]
It is fine  and can close now. It is probably caused by the failure of the cdn endpoint.
