### ISSUE TITLE
Is this project dead? What are recommended alternative services?

### ISSUE THREAD

**Issue by jameshfisher** [peers/peerjs#318]
It's hard to tell - the CDN links are all dead, and have apparently been dead for a long time. Most of the examples are 404s, and the externally hosted ones are broken due to the CDN. When I download the peer.js library manually and use it, it does nothing (does not call my `peer.on` callback, or make any web requests). Should I use peerjs or find an equivalent service?

**Comment by MichaelJCole** [comment]
https://github.com/andyet/SimpleWebRTC/pulse
https://github.com/priologic/easyrtc/pulse

**Comment by r3wt** [comment]
@jameshfisher it works for me. only thing is chrome blocks getUserMedia on insecure origins, and firefox and chrome don't support calling getUserMedia in the way they constructed their shim. this however works as an alternative for me:

```js

function webrtc(onMedia,onError)
{
	function notSupported(){};

	var which = (navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || notSupported).name;

	var args = {video: true, audio: true};

	if(which !== 'notSupported'){
		navigator[which](args,onMedia,onError);
	}else{
		onError('webrtc not supported');
	}
}

```

just pass in your onMedia and onError callbacks. easy damn peasy.

**Comment by RationalCoding** [comment]
After trying several libraries, [simple-peer](https://github.com/feross/simple-peer) is the best alternative and used in production by several new applications. Actively maintained and unlikely to become abandonware.

**Comment by MichaelJCole** [comment]
Time marches on, thanks for a great project!

**Comment by afrokick** [comment]
> Time marches on, thanks for a great project!

The project is not dead)

We just started to upgrade a codebase to typescript, remove old stuff.

I hope we'll be able to revive it

**Comment by Manan07** [comment]
> > Time marches on, thanks for a great project!
> 
> The project is not dead)
> 
> We just started to upgrade a codebase to typescript, remove old stuff.
> 
> I hope we'll be able to revive it

so uhh it is it dead or not ?

**Comment by Alexufo** [comment]
@afrokick Please report the situation about peoject! :-)

<details><summary>.</summary>Живе Белаусь!</details>
