### ISSUE TITLE
pc undefined.....

### ISSUE THREAD

**Issue by pinkencryption** [peers/peerjs#319]
On peer.js ( line 602 )

TypeError: pc is undefined
pc.createOffer(function(offer) {

I am getting the above when trying to make a call connection.

Thanks

**Comment by madwill** [comment]
I've commented on this in a pull request #306

**Comment by bradisbell** [comment]
@madwill Your fix and branch work great for me.  Do you know of an updated Peer.JS fork which incorporates your fixes and others?  I saw that you intended your fork and subsequent NPM package to be temporary, but I wonder if PeerJS is still being maintained at this original repo...

**Comment by Simplici** [comment]
i think peerjs is not maintained.
I have just created a fork which works for firefox and also safari11. 
You could have a try:
https://github.com/Simplici/pearjs

**Comment by kidandcat** [comment]
Fixed with #419
