### ISSUE TITLE
PeerJS Video Chat isn't working

### ISSUE THREAD

**Issue by helloncanella** [peers/peerjs#322]
I'm trying to test de video chat example with my smartphone, but I can't.

I'm receiving the following message:

> PeerJS Video Chat
> 
> Please click `allow` on the top of the screen so we can access your webcam and microphone for calls.
> 
> Failed to access the webcam and microphone. Make sure to run this demo on an http server and click allow when asked for permission by the browser.

**Comment by luongnv89** [comment]
Could you please try it on Firefox/Opera browser. Chrome browser now requires https to access camera and microphone

**Comment by 2n2n** [comment]
Same problem here. Not working on chrome, havent tried Fireforx tho.. I used the peerjs-server over https.

**Comment by jimver04** [comment]
Same here "Could not get access to microphone & camera"
Ubuntu 16.04, Https
Only text works

**Comment by shanu13** [comment]
remote video is not appearing on screen
