### ISSUE TITLE
incomplete information about peer IDs and metadata in docs

### ISSUE THREAD

**Issue by teo1978** [peers/peerjs#325]
At http://peerjs.com/docs/#api

In the API reference, this is said about the `id` parameter of the constructor:

> [id]STRING
> Other peers can connect to this peer using the provided ID. If no ID is given, one will be generated by the brokering server.
> **It's not recommended that you use this ID** to identify peers, as it's meant to be used for brokering connections only. **You're recommended to set the metadata option** to send other identifying information.

_You're recommended to set the metadata option_: **HOW?** The docs of the `metadata` option say nothing about how you are supposed to use it to "send other identifying information" (whatever that means, which by the way is unclear too).

**Comment by ndac-todoroki** [comment]
> Metadata is "data that provides information about other data".
[Wikipedia | Metadata] (https://en.wikipedia.org/wiki/Metadata)

So I've thought anything is okay, like objects:
```javascript
peer.connect(id, {
    metadata: {
        username: "ndac-todoroki",
        userid: "3cauilj1vbcsor"
    }
});
```

so you want to decide your own metadata key or something to identify one peer from another (at least this is how _I_ use it).

But still yes, I agree with you. The documentation surely needs at least some kind of examples.
