### ISSUE TITLE
WSS error on EC2

### ISSUE THREAD

**Issue by Maykonn** [peers/peerjs#327]
Hi,

I'm using the PeerJS lib, but Chrome requires https and wss. Chrome gives a warning when try to connect via websocket using insecure connection.

In this url you can see the error on google chrome console and see the code too:
[https://dev.messenger.zuk.plus/](url)

This call not works and returns **ERR_DISALLOWED_URL_SCHEME**:
[wss://dev.presence.zuk.plus/peerjs?key=peerjs&id=p1tbkvtso1jrlik9&token=e1bxlzqaztulerk9](url)

I'm trying this way:

```
var peer = new Peer({
    host: 'dev.presence.zuk.plus', 
    port: 443, 
    debug: 3, 
    secure: true, 
    proxied: true
});
```

I'm using proxied because the backend is running in a AWS EC2 instance with Apache. The JS client app is running from AWS S3 and AWS CloudFront as CDN.

Do you know what happens?

**Comment by Maykonn** [comment]
This project is dead?

**Comment by abioneperhobby** [comment]
@Maykonn same problem in cloud9 free istance : i can setup the server but client cannot connect due to wss connection fails.

if i use cloud peerjs i cannot use chrome because chrome needs https page in order to obtain webcam but opening the page in https i need to call peerj in secure mode and cloud version of peerjs will not serve https calls.

so i tried to install myself but this way client cannot connect due to wss .

can you suggests me something?

thanks

**Comment by Maykonn** [comment]
@afrokick why closing the issues without providing any assistance? The question is valid.

**Comment by afrokick** [comment]
> @afrokick why closing the issues without providing any assistance? The question is valid.
Sorry, we are cleaning old issues which don't have fresh updates.

1) In your example you create Peer - it is client side? because 'proxied' property exists only on server.
2) If you have proxy - it should be run on 443 port and forward all incoming requests to PeerServer instance.

**Comment by Maykonn** [comment]
Oh, sorry @afrokick, my bad. I don't paid attention to the issue date.
Thanks for your help.

**Comment by afrokick** [comment]
> Oh, sorry @afrokick, my bad. I don't paid attention to the issue date.
> Thanks for your help.

Don't worry)

This this my configs.

**Client:**
```
    this.peer = new peerjs.Peer({
      key: 'peerjs',
      host: 'some-app.com',
      port: 443,
      path: '/myapp',
      debug: 3
    });
```

**Server:**
```
const server = PeerServer({
  port: 9000,
  path: "/myapp",
  proxied: true,
  debug: true
});
```

**nginx**(sorry, i think apache has similar config):
```
upstream vchat {
  hash $remote_addr;
  server 127.0.0.1:9000;
}

map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

server {
    listen [::]:443 default_server ssl ipv6only=on;
    listen 443 default_server ssl;
    
    root /var/www/html;
    
    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;
    
    server_name some-app.com;
    
    location /myapp {
        proxy_pass http://vchat;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
        proxy_max_temp_file_size 0;
    }
    
    ssl_certificate /etc/letsencrypt/live/some-app.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/some-app.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

hope that it helps you:)

**Comment by Maykonn** [comment]
Thanks! It will be helpful.
