### ISSUE TITLE
Cannot dataConnection.send(); from Firefox to Chrome

### ISSUE THREAD

**Issue by ndac-todoroki** [peers/peerjs#330]
I cannot send data from FF to Chrome using the DataChannel's `.send(data)` method.

Tried in the sample chat application too
[http://cdn.peerjs.com/demo/chat.html](http://cdn.peerjs.com/demo/chat.html)

and the chat results are

| chat to → | Firefox46 | Chrome48 | Opera35 |
| --- | --- | --- | --- |
| Firefox | ○ | × | × |
| Chrome | ○ | ○ | ○ |
| Opera | ○ | ○ | ○ |

(Chrome and Opera are both V8, so it might be obvious)

By the way, when I look in at the web console when I connected to the other user in the sample chat,
I see several methods are deprecated in Firefox 44 (The stable one), 
`Use of getPreventDefault() is not reccomended. Use defaultPrevented instead. jquery.min.js:2:40351`
`RTCIceServer.url is deprecated! Use urls instead. <Unknown>`

and one additionally on Firefox 46 (I'm using Firefox DeveloperEdition 46.0a2).
`onaddstream is deprecated! Use peerConnection.ontrack instead.`
(information [here](https://hg.mozilla.org/integration/mozilla-inbound/rev/81a339251da3))

I see these errors/warnings in my own applications too, which neither works.

Is this affecting the problem?

No errors are raised in Chrome 48.0.2564.82 (64bit) / Opera 35
If someone can test in mac will be appreciated too (want to know if it works in Safari/Nitro)

**Comment by ciwolsey** [comment]
Same problem. Is this project dead?

**Comment by kasimmm** [comment]
Same problem.
It seems that onaddstream is used in MediaConnection, but the deprecated warning popup while trying to use DataConnection (send text message)

**Comment by brickgale** [comment]
i also get `onaddstream is deprecated! Use peerConnection.ontrack instead.` on firefox. my media/video stream won't load up...

**Comment by afrokick** [comment]
let me know if it still exists

**Comment by danielverissimo** [comment]
2011 and I still getting this error. Someone have some news?
