### ISSUE TITLE
No way to remove listeners for events??

### ISSUE THREAD

**Issue by teo1978** [peers/peerjs#331]
`Peer`, `DataConnection` and the like all have an `on` method for attaching event listeners to them.

But I don't see any documented method to remove such listeners. 

Usually, other decent frameworks and APIs (including native standard JavaScript DOM event handling and such) have things like `addEventListener` and `removeEventListener`.

1) How are you supposed to stop listening for an event? 

2) How are you supposed to remove a listener in order to guarantee that a (`Peer`, `DataConnection` or whatever) object will be garbage-collected when deleting any reference to it?

If (2) is not needed (because of some behind-the-sceen magics that take care of that), that needs to be thoroughly documented. And even if that is the case, that does not provide a solution for (1). 

Is this stuff just undoumented or does it really not exist?!

A couple of stupid-simple use cases that easily come to my mind (but one can think of a thousand more):

I) I want to construct a Peer that will listen for connections. I assume that one single peer will connect to "me". If anything goes wrong at any stage, be it because the Peer gets destroyed or disconnected from the signaling server, or after the other peer has already established the connection and this connection is closed or lost, in all these cases (that is, as a single response to several different events), I want to start over from the beginning, just to keep stuff simple, by creating a new Peer from scratch and re-attaching the listeners to it. So, I need to do cleanup to make sure I don't "leak" dead or half-dead Peers that I have no more references to (both to avoid leaking memory and in case some of them triggers an event I don't care about anymore).
II) Within this same scenario, there may be a moment where I want to call `mypeer.destroy()` just as part of the cleanup, but I previously started listening for the `close` event, and I don't want it to be fired now, so I need to remove the listener before destroying the Peer.

**Comment by afrokick** [comment]
Peer, MediaConnection, DataConnection extend EventEmitter, so, you can use 'off' method to unsubscribe from event

**Comment by sahilrajput03** [comment]
FYI: It works like

```
myPeer.off('call')
```

**Comment by hayelom123** [comment]
> )

mayPeer.off("call") doesn't work i tested it. still i am getting all unreferenced call event when come back to that page.
FYI: i also tried to use it with disconnect .and it doesn't reconnect
