### ISSUE TITLE
[DOCUMENTATION] error event for DataConnection lacks documentation

### ISSUE THREAD

**Issue by teo1978** [peers/peerjs#332]
I mentioned it in #329 but since that's a separate issue and a real one, this should be tracked separately.

The documentation says nothing about the error event of DataConnection (except for the fact that it exists). It only says:

> `'error'EVENTdataConnection.on('error', function(err) { ... });`

What kind of errors does it detect? What does the `err` variable contain (an object, I guess)? Does it have a `err.type` property like `Peer`'s errors, and if so what are its possible values?

One extremely important thing to be documented (among others) is whether or not an error means that the connection is lost, or put the other way round, whether or not it may occur that a connection triggers errors (e.g. in the case of lost messages in unreliable connections) but keeps functioning. Can it be assumed that the `close` event is always triggered even if the connection is closed because of an error, or should one also listen for the `error` event? Etc. etc.

As the documentation is now, we now NOTHING about `DataConnection` errors and it is impossible to develop a decently solid script that makes use of it.

**Comment by afrokick** [comment]
err has type of Error
