### ISSUE TITLE
TypeError: pc is undefined

### ISSUE THREAD

**Issue by abioneperhobby** [peers/peerjs#336]
on firefox,
cloud peerjs,
making new Peer('myid', {key: 'XXXXXXXX', debug: 3});

i obtain

TypeError: pc is undefined

there

Negotiator._makeOffer = function(connection) {
  var pc = connection.pc;
  pc.createOffer(function(offer) {
    util.log('Created offer.');

using a breakpoint, i see that connection doesn't have pc properties.

**Comment by PaulMaly** [comment]
Have the same error.

**Comment by nileshlets** [comment]
Try this js : https://github.com/madwill/peerjs/blob/master/dist/peer.js

**Comment by RobinHSanner** [comment]
See https://github.com/peers/peerjs/issues/355

**Comment by kidandcat** [comment]
Fixed with #419
