### ISSUE TITLE
Support iOS Safari

### ISSUE THREAD

**Issue by nileshlets** [peers/peerjs#339]
I am trying to connect my web app with iOS .
How can I connect iOS mobile peer to my web browser peer and perform video call?
Is there any limitation?

**Comment by mikkelking** [comment]
webrtc is currently not supported in Safari on IOS. It seems you might need to write some xcode to interface to the webrtc libraries yourself

**Comment by danielpox** [comment]
Safari 11 in iOS 11 sure does support WebRTC, so PeerJS needs to update accordingly

**Comment by hevyhomie** [comment]
Any updates on this?

**Comment by maxpavlov** [comment]
Can anyone confirm they are able to actually send data back and forth between a desktop chrome and a mobile Safari? All of the declared browser combinations work well for me, but when it comes to exchanging data with iOS Safari, a connection is made, but no data is actually sent from mobile Safari.

**Comment by kidandcat** [comment]
http://iswebrtcreadyyet.com/

**Comment by afrokick** [comment]
I tested with iOS 12.4 - it works with simple case like p2p dataConnection.
