### ISSUE TITLE
Cannot take video calls on Firefox 45.0.2

### ISSUE THREAD

**Issue by shehantissera** [peers/peerjs#341]
I can receive calls but it disconnects automatically.
When I try to take a call this is the issue I get.

peernew.js is the same file as http://cdn.peerjs.com/0.3.14/peer.js

TypeError: pc is undefined
[5]</Negotiator._makeOffer()
 peernew.js:602
[5]</Negotiator._setupListeners/pc.onnegotiationneeded()
 peernew.js:555
RTCPeerConnection.prototype.dispatchEvent()
 PeerConnection.js:611
PeerConnectionObserver.prototype.dispatchEvent()
 PeerConnection.js:1228
PeerConnectionObserver.prototype.onNegotiationNeeded()
 PeerConnection.js:1288
RTCPeerConnection.prototype.addTrack()
 PeerConnection.js:1003
RTCPeerConnection.prototype.addStream/<()
 PeerConnection.js:974
forEach()
 self-hosted:208
RTCPeerConnection.prototype.addStream()
 PeerConnection.js:974
[5]</Negotiator.startConnection()
 peernew.js:413
MediaConnection()
 peernew.js:313
[6]</Peer.prototype.call()
 peernew.js:1017
$scope.call()
 chat.js:182
anonymous/fn()
 angular.js line 13628 > Function:2
expensiveCheckFn()
 angular.js:14610
ngEventHandler/</callback()
 angular.js:24071
$RootScopeProvider/this.$get</Scope.prototype.$eval()
 angular.js:16359
$RootScopeProvider/this.$get</Scope.prototype.$apply()
 angular.js:16459
ngEventHandler/<()
 angular.js:24076
n.event.dispatch()
 jquery.min.js:3
n.event.add/r.handle()
 jquery.min.js:3

Has anybody already faced this issue?

**Comment by codebazz** [comment]
I have faced the same problem in latest FF and chrome . Is there any solution please?

**Comment by lemurio** [comment]
Try this https://github.com/lemurio/peerjs/blob/master/dist/peer.js

**Comment by RobinHSanner** [comment]
See https://github.com/peers/peerjs/issues/355 for more info on this

**Comment by kidandcat** [comment]
Fixed with #419
