### ISSUE TITLE
PeerJS server keeps dying automatically after some time. 

### ISSUE THREAD

**Issue by kernelfreak** [peers/peerjs#344]
Hello friends,

I am working on integrating PeerJS into my project. For that I am running PeerJS server on our servers. The problem is, the server automatically shutsdown after some time. Also the time is so random, no behaviour we know. No log file locations available are known after looking on net.

The server is running Debian Linux X64. Any more information if you require, I am happy to provide. Thank you.

**Comment by mikkelking** [comment]
I may not be able to help, but more information would be helpful - was there an error message on the console, was there something in the system logs to tell you why a process just vanished ? Were you ssh'ed into the box, and when your ssh session timed out the PeerJS server was killed as well?

**Comment by RamyaAshika** [comment]
Any updates on this? I'm also facing the same problem? @kernelfreak

**Comment by kidandcat** [comment]
The server process shutdown? No logs even with log level at max?
I'm sorry but I'm very busy now to investigate this issue, there is no info at all, so it will take a long time probably to find the cause.

You can use an utility like PM2 https://github.com/Unitech/pm2 to restart it after shutting down.

**Comment by RamyaAshika** [comment]
What is this PM2?? @kidandcat

**Comment by kidandcat** [comment]
https://medium.com/@riyadhalnur/managing-and-deploying-nodejs-apps-with-pm2-173fbc7d3f95
