### ISSUE TITLE
Error: The current browser does not support WebRTC

### ISSUE THREAD

**Issue by stevedekorte** [peers/peerjs#346]
I just started getting this on:
peerjs v0.3.14 on
electron v0.36.1 with chrome v 47.0.2526.73 on
OSX 10.11.4 (15E65)

It was working fine yesterday. 
Any thoughts?
Anyone else seeing this?

**Comment by stevedekorte** [comment]
Commenting out the check:

if (!util.supports.audioVideo && !util.supports.data ) {
this._delayedAbort('browser-incompatible', 'The current browser does not support WebRTC');
return;
}

solved the problem but I don't know why this check started failing. util.supports.audioVideo and util.supports.data are both false.

**Comment by sandros87** [comment]
It just solves the "message". Firefox just won't work with peerjs and I don't understand what we have to do to fix it. The doc says 27+ is supported but that is not true.

**Comment by afrokick** [comment]
Should works now
