### ISSUE TITLE
Cloud server become useless in latest chrome

### ISSUE THREAD

**Issue by euglv** [peers/peerjs#348]
From one side - cloud server does not support https:

```
if (options.secure && options.host === '0.peerjs.com') {
    this._delayedAbort('ssl-unavailable',
      'The cloud server currently does not support HTTPS. Please run your own PeerServer to use HTTPS.');
    return;
}
```

From the other side - chrome does not supports WebRTC over insecure pages.
`getUserMedia` does not work from http pages: https://goo.gl/rStTGz 
Also Chrome does not allow XMLHTTPRequest to load insecure pages, if main page was https:

```
peer.js:1298 Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://0.peerjs.com:9000/fb7446equvyxecdi/ACWQ77nDdJYgsixQyoicx9XiKwd2/ccdzk7pdri6rrw6ek67sqbyb9/id?i=0'. This request has been blocked; the content must be served over HTTPS.
```

So no way to use peerjs cloud server in latest chrome, unsure how it is in other browsers.

**Comment by RobinHSanner** [comment]
[script.zip](https://github.com/peers/peerjs/files/448395/script.zip)

[peer-server.zip](https://github.com/peers/peerjs/files/448393/peer-server.zip)


Modify peer-server.js as attached making sure to reference the correct cert info (.key and .crt), then on the client side in script.js make sure you add the secure: true option when creating Peer.  See attached .zips for more info.

**Comment by mikkelking** [comment]
It is still useful for testing using localhost, admittedly it would be better if it was available in https as well, but the sensei appears to have departed :(
