### ISSUE TITLE
This project is still active ?

### ISSUE THREAD

**Issue by l2aelba** [peers/peerjs#349]
Seems like 9 months without update
and... there is stable to use their own "PeerServer Cloud service" ?

**Comment by hermanfransen** [comment]
I have the same question, since no answer after 20 days I guess not?

**Comment by christopherfowers** [comment]
Lol. I think the silence has become your answer?

**Comment by l2aelba** [comment]
@christopherfowers that is a answer :D

**Comment by venomlust** [comment]
The peerjs developers dont have any activity in months, maybe something happen to them?

**Comment by venomlust** [comment]
@michelle @ericz any of you is planning to update PeerJS? cause the browsers keep updating and the issues here keep growing.

**Comment by stevedekorte** [comment]
+1
