### ISSUE TITLE
Peer Losing Connection to Peer Server in Chrome

### ISSUE THREAD

**Issue by arjunmitrareddy** [peers/peerjs#350]
The peer keeps losing connection to the peer server every 1-2minutes in Chrome latest version and sometimes in Firefox. Re-connecting fails as the server is getting destroyed

**Comment by lemurio** [comment]
Maybe server process died? Try to start with forever
`npm install forever -g`
`npm install forever-monitor`

**Comment by arjunmitrareddy** [comment]
@lemurio 
No thats not the problem. Its even happening with the default cloud based one

**Comment by madwed** [comment]
Did you ever figure this out @arjunmitrareddy? I'm having the same problem

**Comment by madwed** [comment]
Could this be related to https://github.com/peers/peerjs/issues/291?

**Comment by madwed** [comment]
Update: tried that fix, but it didn't solve the issue

**Comment by DannySofftie** [comment]
A quick fix to this..... when starting Node, don't use nodemon. Use npm start if you have configured it in your package.json file, or simply use node server.js(server.js is your server script). I ran into the same problems then I realised nodemon restarts the server every time a websocket makes a request and thus you get disconnected as the connection is lost

**Comment by afrokick** [comment]
I think 'heartbeat' will fix it. It's in master already, but not released. You can try it.

**Comment by RamyaAshika** [comment]
Can you please do that as soon as possible because I'm using your peerjs version 3.20 @afrokick

**Comment by afrokick** [comment]
@RamyaAshika you can try our 'beta' version from master - npm install peers/peerjs#master

**Comment by RamyaAshika** [comment]
Sure, Thank you. @afrokick
