### ISSUE TITLE
js error in demo

### ISSUE THREAD

**Issue by GrosSacASac** [peers/peerjs#351]
cdn.peerjs.com/demo/videochat/

pc is undefined

**Comment by knoxcard** [comment]
The demos require SSL https urls,  ssl certs needed.

**Comment by mikkelking** [comment]
I've seen that too in Firefox. Chrome doesn't have that problem

**Comment by RobinHSanner** [comment]
See https://github.com/peers/peerjs/issues/355 for a fix although after I updated to the latest Firefox I didn't have the problem any more.

**Comment by casualuser** [comment]
this demo not working in Chrome in case of this changes - https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
