### ISSUE TITLE
PeerJS Error: Invalid key provided.

### ISSUE THREAD

**Issue by adonis1116** [peers/peerjs#354]
I have downloaded & installed peerjs server.
Also I could run the server without error (:))
But while connecting to server (javascript), I see error "PeerJS: ERROR Error: Invalid key provided" in Chrome browser console.

I changed CLOUD_HOST from **0.peerjs.com** to '192.168.1.100', my local address.

What could be the problem?

Please help me.

**Comment by akilude** [comment]
You should not change CLOUD_HOST, if you want to use your own peer server, then you can install it from [https://github.com/peers/peerjs-server](here). then run the peer server and then change "host", "port" and "path" parameters while creating a new peer, also do not use the "key" attribute

**Comment by Lovinity** [comment]
This issue needs fixed. I located the problem in the peer.js compiled source (unminified).

Line 576 defines options.key = "peerjs". This means whatever you provide in options as key, it always gets changed back to peerjs. This is a problem for servers using custom keys. This line should be removed, and instead in the "options = util_1.util.extend" object, a key: "peerjs" is added. This way, the default key value is peerjs, but if one is provided in the Peer constructor options, it will use that instead.

**Comment by Lovinity** [comment]
Could I have an explanation as to why this issue was closed please?

**Comment by afrokick** [comment]
> Could I have an explanation as to why this issue was closed please?

Of course.

We fixed it in master branch, 

```
    options = {
      debug: 0, // 1: Errors, 2: Warnings, 3: All logs
      host: util.CLOUD_HOST,
      port: util.CLOUD_PORT,
      path: "/",
      key: Peer.DEFAULT_KEY,
      token: util.randomToken(),
      config: util.defaultConfig,
      ...options
    };
    this._options = options;
```
Sorry that didn't provide the explanation before

**Comment by Lovinity** [comment]
Okay thanks for updating us!
