### ISSUE TITLE
PeerJs client errors with pc undefined when call button is pressed

### ISSUE THREAD

**Issue by RobinHSanner** [peers/peerjs#355]
In the Negotiator.startConnection function I had to move the line:
    connection.pc = connection.peerConnection = pc;
before the 'if' statement that adds the options stream to the pc.
The reason is that as soon as the stream is added to the pc the
Negotiator._makeOffer function fires but at that point in time pc is not defined on connection.
Line 601 is where the pc undefined error occurs:
  var pc = connection.pc;

I'm running the local PeerJsServer with https and two PeerJs clients in Firefox 44.0, all on the same machine.

**Comment by RobinHSanner** [comment]
I noticed on writing this that my Firefox was out of date.  I updated to v48.0.2 and the problem hasn't reoccurred.

**Comment by MyWek** [comment]
Happens to me too in firefox 49

**Comment by NickolasBoyer** [comment]
Met to @ 58
