### ISSUE TITLE
Nothing works over HTTPS

### ISSUE THREAD

**Issue by anasik** [peers/peerjs#356]
I guess it's common knowledge that you can't load content using HTTP when using HTTPS.

Now the thing is, that the getUserMedia() cannot be run without HTTPS for obvious security reasons.
So, I hosted the example files on a HTTPS enabled server but when I tried to run it, a handful of errors prevented it from working because every now and then, request are made over http instead of https. 

If you choose to load unsafe scripts, the chat works. But the videochat example still shows no inclination to work.

**Comment by snuggs** [comment]
@anasik double leading slash perhaps? At least will get you to the root of the problem much quicker. 
Considering that the first RFC to describe it, RFC 1808, was written 15 years ago, and URL references are key to website functionality, I think it is safe to say that pretty much all major browsers do support it by now. But the only way to know for sure is to simply try it yourself and see what happens.

1. https://tools.ietf.org/html/rfc1808#section-4
2. https://tools.ietf.org/html/rfc2396#section-5.2
/cc @michelle @ericz

**Comment by anasik** [comment]
You misunderstood. Look, let me explain it.
* WebRTC doesn't really allow for calls without HTTPS (See how your [example](http://cdn.peerjs.com/demo/videochat/) doesn't work? )
* Loading a page in HTTPS means that the page cant load content over HTTP.
* Naturally, that means that all the linked scripts must also be loaded using https.. i.e. peerjs and JQquery. 
* Take a look at [this](https://wordo.co/apprtc/peer/peerjs/examples/videochat/) HTTPS is enabled, AND the peerjs and JQ are loaded via https and yet it fails to work.. it never asks for permission to use the microphone and the camera.

**Comment by transonly** [comment]
Put the peer.js somewhere inside the webfolder and link to that?
