### ISSUE TITLE
Error when using PeerJS Peer Cloud Server

### ISSUE THREAD

**Issue by leonardovilarinho** [peers/peerjs#359]
I'm trying to make an example of video calling, but it's an error in the console saying not connected on the Peer Server for it be HTTP, and my hosting does not accept to install the Peer Server, so I have this problem of having to use an external Peer Server HTTPS. Because if I put my hosting in HTTP won't be able to gain access to the webcam.

How can I solve?

My example: https://selfmarket.com.br/videochat/

**Comment by digitalgarage** [comment]
Hi @legionlab  ... If you haven't already solved this you will need to look at hosting your own peerjs server.  It fixed the problems for me.

You'll find a deploy to heroku button if you go to the peerjs repo: https://github.com/peers/peerjs-server

It was dead simple to deploy and connect. I've used it a couple of times now.

Eric.

**Comment by legionlab** [comment]
The problem is really the hosting, I always use in my projects do not support the PeerJS Server, the cost is great to have a dedicated server. Not no PeerJS Server public with HTTPS

**Comment by digitalgarage** [comment]
Check out Heroku's free tier.  It may be all you need, particularly if you're only running a low traffic site.

**Comment by saintthor** [comment]
http://cdn.peerjs.com/demo/chat.html

this demo works. it is using peerjs cloud server.
