### ISSUE TITLE
stream video file(local) trough peer connection

### ISSUE THREAD

**Issue by IvRRimum** [peers/peerjs#362]
How would one do this? i want to stream .mp4 file to my peers using peer connection(not data channels).

Thanks!

**Comment by krazyjakee** [comment]
I would also like to know this.

**Comment by MakersHeaven** [comment]
have a look at this documentation: 
https://webrtc.github.io/samples/
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API#WebRTC_concepts_and_usage

This is something i'm trying to achieve as well. Basically you have to combine these two. WebRTC creates the stream, peerjs transports it.

**Comment by mze01** [comment]
This can be done with calls - peer.call to be more precise. According to [PeerJS documentation](https://peerjs.com/docs.html#api), a call can be started with:

`var call = peer.call('dest-peer-id',
  mediaStream);`

Where 'dest-peer-id' is the destination ID, and mediaStream is a stream of your mp4 file. Keep in mind that the destination peer will also have to answer the call. I am not sure as to how you would convert your mp4 to a mediaStream, but apparently a solution exists on [stackoverflow](https://stackoverflow.com/questions/21225187/how-to-create-mediastream-from-videofile).

Then, your destination ID can listen to the stream and present it in an html video canvas. From the official documentation:

`call.on('stream', function(stream) {
      // `stream` is the MediaStream of the remote peer.
      // Here you'd add it to an HTML video/canvas element.
    });`
