### ISSUE TITLE
Dealing with More than 50 Connections

### ISSUE THREAD

**Issue by imerkle** [peers/peerjs#363]
I want to implement a chat site but the limit is only 50 connection per API. 
What if there are thousands of users chatting INDIVIDUALLY with each other.

I have a workaround solution. I just want a review 

User **Alice** - API KEY 1 (Its full)
User **Bob**  -  API KEY 2
User **Carol** - API KEY 3 (Its full)

Now User **Alice** _cannot_ connect User **Bob** . So User **Alice** has to create a peer in **API KEY 2**.

Also User **Alice** cannot connect User **Carol**  and **API KEY 3** is full , so **Alice** creates a peer in **API KEY 4** and tells Carol to create a peer in **API KEY 4** and they connect.

Is there an easy way around this solution ? Enlighten Me!

**Comment by digitalgarage** [comment]
You can setup a dedicate peerjs server. https://github.com/peers/peerjs-server.  I've used that successfully.

Eric.

**Comment by DannySofftie** [comment]
@digitalgarage how did you achieve that? I am working on a similar project but after sending mediastream to remote peer, I cannot get that data

**Comment by afrokick** [comment]
It's just server side logic to control how many users can connect to server using specific key
