### ISSUE TITLE
Https server problem.

### ISSUE THREAD

**Issue by amrendrakumaramar** [peers/peerjs#365]
![Uploading Capture.PNG…]()
Hi,
I am new in webRTC. I am trying a peer to peer video chat. When I try to connect to the cloud through key it shows a message that peerjs cloud do not have secured connection. When I use it locally I am able to access. But need two servers to run as it is in nodejs and my application runs in IIS. Is there any way by which I can use either cloud or both in the same server (IIS).
Thanks in advance.
Amrendra

**Comment by polyzer** [comment]
[Try this!](https://groups.google.com/forum/?fromgroups#!topic/peerjs/XEyeA7HSczU)
