### ISSUE TITLE
Way to know if connection is peer2peer or a TURN server is being used?

### ISSUE THREAD

**Issue by andrelevi** [peers/peerjs#366]
Hi,

Does anyone know if this possible via the debug mode? I have looked at the default debug output when connecting to a peer, but I'm unable to identify which if a TURN server was used.

Thanks!

**Comment by d-knafo** [comment]
+1

**Comment by doganmurat** [comment]
+1

**Comment by afrokick** [comment]
https://testrtc.com/webrtc-internals-documentation/
