### ISSUE TITLE
Firefox 52.0.1 (64-bit) not working when TURN server is provided

### ISSUE THREAD

**Issue by arcifius** [peers/peerjs#371]
Well its a browser compatibility problem... Its very simple to reproduce, just add a TURN server:

`
this.peer = new Peer(this.state.identificacao, {
            host: 'localhost',
            port: 9000,
            path: '/myapp',
            config: {
                'iceServers': [
                    { url: 'stun:stun.l.google.com:19302' },
                    { url: 'turn:user@someip', 'username':'user', 'credential':'somecreds' }
                ]
            }
        });
`
Then try to establish a call either calling or answering it...

Chrome to Chrome **Works**
Firefox to Firefox **Fails**
Firefox to Chrome & Vice versa **Fails**

**Comment by RamyaAshika** [comment]
Whether you got any solution for this @arcifius

**Comment by afrokick** [comment]
Please, check it again in new release 1.0.0. Leave a comment if it still exists
