### ISSUE TITLE
Record or take snapshot

### ISSUE THREAD

**Issue by Moradnejad** [peers/peerjs#372]
Is there any way to record or take snapshot during a live session? hopefully from JS and not the server-side?

**Comment by Kitanga** [comment]
You can take a snapshot using canvas on client side, convert that snapshot to dataURI (string representation of the image), and send it over as text. Voila! you have yourself a snapshot taking application. I'm sure you can easily find an example showing you how to convert a canvas' data to dataURI

More technical stuff:

- Draw video once onto the canvas. This means you just invoke a draw function with the video element as source.
- You then take the canvas and covert it to dataURI
- You now send that dataURI to the receiving user

**Comment by Moradnejad** [comment]
Thanks. I'll check
