### ISSUE TITLE
Use own id

### ISSUE THREAD

**Issue by essteffan** [peers/peerjs#374]
Hy All.
I'm using peer js for video streaming and i need to make it without the user to share there generated id.

For that i've done:
var peer = new Peer('EYu5Xe8uHTK371_'+current,{  ...
current is the id off the user like EYu5Xe8uHTK371_1. (last 1 is the user id)
The other connection has his own id like EYu5Xe8uHTK371_13

The issue is that when i make the connection i have the folowing error: 
PeerJS:  WARNING You received a malformed message from undefined of type HTTP-ERROR
VM473:1 PeerJS:  Socket open
VM473:1 PeerJS:  ERROR Aborting!
VM473:1 PeerJS:  ERROR Error: ID `EYu5Xe8uHTK371_1` is taken
VM473:1 PeerJS:  Socket closed.
VM473:1 PeerJS:  ERROR Error: Lost connection to server.

How can i archive this using automatically id?

Thank you!

**Comment by essteffan** [comment]
No one?, Come on guys?

**Comment by LucaColombi** [comment]
Hello @essteffan , I discovered from sources that you must use alphanumeric, for instance an id containing '_' is not accepted

PeerJS team, please document this ;)

**Comment by pReya** [comment]
Added this in https://github.com/peers/peerjs/pull/509

**Comment by afrokick** [comment]
#511
