### ISSUE TITLE
issues with the dynamic  Id creation

### ISSUE THREAD

**Issue by KumailHussain** [peers/peerjs#376]
tthis.peer = new Peer({key: 'csq3bdb0e6mbzkt9'});
            setTimeout(() => {
                this.mypeerid = this.peer.id;
}
creates new id every time when  i navigate to any page as there are two connections i.e the caller and the one who answers the call, but i don't want to create the new id again even  if i assigned the same id again ,  the web cam doesn't works how can i keep the same id even navigating doesn't effect the video call?
as i am working in components explaining it further:
1. (home-Page)i loaded the header, footer, body and webcam component(id is generated)
2. ( CallUs)-now another user comes in this page(callus) and connect to the above user it will working fine
3. now the homepage user navigates to another page it  has different component header, footer not webcam and comes again to same page a new id will be generated hence no more connection is alive but the id must remain same 
even i kept the same id but it doesn't work on loading the home page

**Comment by afrokick** [comment]
Let me know if it is still relevant to you
