### ISSUE TITLE
Firefox - XML Parsing Error: no root element found Location: http://0.peerjs.com:9000

### ISSUE THREAD

**Issue by deceivingrakesh** [peers/peerjs#377]
Works fine on chrome , but in Firefox i get the error "XML Parsing Error: no root element found
Location: http://0.peerjs.com:9000/x/xxx/xxx/offer" , and doesn't connect to other peer  . on removing "http" protocol in peer.js , the error doesn't appear , but unable to establish a connection.

**Comment by wahabdevvv** [comment]
mauka mauka hanjeee @deceivingrakesh  kaisa diya phir inida ko humne ................. no issue le lo tissue
acha mazak k ilawa is point ko mai bhi dhoondh rha bc kch mil hi ni rha ..................\
mauka mauka mauka mauka

**Comment by ali-hassan** [comment]
hahahhaha bc yh issue mgy b agyaaa ha
