### ISSUE TITLE
Switch Camera During Call

### ISSUE THREAD

**Issue by RikdeVos** [peers/peerjs#380]
I want to switch camera stream while in a call, without closing the connection to the other peer. Is this possible?

Currently doing something like this:
```
navigator.webkitGetUserMedia({video: true, audio: true}, (stream) => {
  peer.call(key, stream);
});
```

**Comment by soulpcbr** [comment]
It is not possible.

**Comment by Mrsevic** [comment]
It is possible. Take a look at skyway examples or this example:
https://github.com/muaz-khan/WebRTC-Experiment/blob/master/demos/switch-streams.html

**Comment by FelipeMiranda** [comment]
Really??? that's not possible?

**Comment by manhpham** [comment]
Hi, any one can switch camera during call?

**Comment by kidandcat** [comment]
You need to establish a new connection, this is because of how WebRTC works.

**Comment by afrokick** [comment]
You can use replaceTrack of RTCRtpSender.

 this.call.peerConnection.getSenders()[0].replaceTrack()
