### ISSUE TITLE
Is there any API by which peerjs server can close any of it's connected client.

### ISSUE THREAD

**Issue by vivekkumar27june88** [peers/peerjs#382]
I want to modify the peerjs server code so that if a connection event come for existing client id then I first close the existing client, clean up entries from `_clients` and `_ips` and then call the `_configureWS` for this new socket.

Question:
1.  Is there any API available in PeerJs server code or in ws npm package for closing the client socket.
2. What are required steps for cleaning up the entries of client maintained by the peerjs server.

**Comment by kidandcat** [comment]
Why do you want to do that? You cannot know if the new connection comes from an existing client or not, if you do what you say, I can close A connection by connecting from B with same ID.

**Comment by vivekkumar27june88** [comment]
Hi @kidandcat, Thanks for your response. You can close this issue.

I had posted this question long back. That time I had managed to change the code locally for our purpose.T
