### ISSUE TITLE
Typescript definitions 

### ISSUE THREAD

**Issue by vincaslt** [peers/peerjs#386]
There are some typescript definitions on DefinitelyTyped, but they are very hard to use.
They declare a namespace and Peer constructor. They never export a module or the functions, so you can't really import them as required. There is also this problem, that typescript tries to import from type definitions, rather than from module directly, but the definitions don't describe an exported module, so it fails with: `[ts] File 'c:/Users/Vincas/Desktop/language-exchange/node_modules/@types/peerjs/index.d.ts' is not a module.`

So really the only way I see I can use it is with: `const Peer = require('peerjs')` which is not exactly how it should be in TS.

**Comment by chak774** [comment]
Sorry, I am still don't understand how to use typescript to import Peer. Can provide some example? thanks

**Comment by shivarajnaidu** [comment]
+1

**Comment by aneeshdurg** [comment]
You should be able to do `import Peer from 'peerjs'`. You can install peerjs with `npm install --save peerjs` and then use webpack or something to resolve the import.
