### ISSUE TITLE
Cannot close connection

### ISSUE THREAD

**Issue by vincaslt** [peers/peerjs#390]
For some reason I cannot close connection. After geting MediaConnection from `.answer` or `.call`, I call `connection.close()`, but it says the connection is closed on one end - the same I've just closed in. Recipient still has his connection open:

The one I've closed in: https://puu.sh/x4Zwr/40c1d27733.png
The one waiting for onClose: https://puu.sh/x4Zzr/1d4860b551.png

 ```
call.on('close', () => {
      console.log('closed')
})
```

This code never gets executed on the receiving end.

**Comment by RamyaAshika** [comment]
How you fixed it. I'm also facing the same problem @vincaslt
