### ISSUE TITLE
Cancel the already initialized call

### ISSUE THREAD

**Issue by Mrsevic** [peers/peerjs#391]
Is there any chance to cancel the already initialized call request towards other peer?

I have the problem when I call someone and then cancel that call the other peer is still able to receive the call?

Thanks

**Comment by capripio** [comment]
@Mrsevic found any solution for that yet?

**Comment by kidandcat** [comment]
Let me have a look

**Comment by capripio** [comment]
@kidandcat  so?

**Comment by kidandcat** [comment]
Did you tried destroying the peer?

**Comment by capripio** [comment]
@kidandcat I am using single peer on whole application. so I can't destroy it

**Comment by kidandcat** [comment]
Then you will need to relie on your own signaling, right now there is no way for a call initiator to reject the answer of the callee.

You could signal using a dataChannel and, when you be sure, you can execute the call.

**Comment by marcjulianfleck** [comment]
Since this issue is now closed for three years and this feature is still not implemented I want to reopen it and ask if it would not make a great feature?
