### ISSUE TITLE
Request For Screen Recording

### ISSUE THREAD

**Issue by webciter** [peers/peerjs#397]
request for sending a screen capture recording to other peers using, similar methods already in place.

**Comment by bradisbell** [comment]
That's not something that belongs at the PeerJS level.  It's part of the Media Capture API.  https://w3c.github.io/mediacapture-screen-share/

Note that in Chrome, you'll need to make an extension to relay the media stream ID to your page, for "security".

**Comment by kidandcat** [comment]
Not possible at the moment without extesions as mentioned before.
