### ISSUE TITLE
video chat automatically disconnect in internet

### ISSUE THREAD

**Issue by stoneWeb** [peers/peerjs#398]
In the local it works, then I deployed it to internet and added turn url in iceServers, Each time the normal video connection disconnected automatically after a few seconds, the log is 'iceConnectionState is disconnected, closing connections to XXX', why?

**Comment by mesutyigit** [comment]
@stoneWeb  Did you solve this issue

**Comment by soulpcbr** [comment]
I have the same problem. Anybody know how solve this?

**Comment by vptagupa** [comment]
Does anyone solved this problem?

**Comment by kidandcat** [comment]
If you still have this problem, could you post your browser versions?

**Comment by kidandcat** [comment]
Test with latest version, comment if it still happens.

**Comment by Payetus** [comment]
This is happening to me
