### ISSUE TITLE
this project seems abandoned, I have a fork which may help some of you

### ISSUE THREAD

**Issue by Simplici** [peers/peerjs#400]
it's a pity that this project is not evaluating.
I have a fork which i will try to maintain for my own purpose. 
https://github.com/Simplici/pearjs

For the moment, it works with the latest versions of Chrome, Firefox and Safari11.

Hope it could help some of you.

Of course, PRs are welcomed and encouraged.
Attention, i am not a experienced Javascript developper.

**Comment by Mrsevic** [comment]
This fork does not do absolutely nothing, you can add adapter.js by yourself manually. I suggest everyone to take a look @nttcom peerjs project and to merge some of it's commits into codebase.

**Comment by bradisbell** [comment]
@Simplici I don't mean any disrespect, but this is an extremely popular project, and you should leave it up to a more experienced developer to look after.  I think we can all appreciate your efforts in organizing the project and trying to continue it... it's a shame the original developers are nowhere to be found and are squatting on a good project name... but if you are going to advertise a fork, it should be a fork that is significant with a commitment from devs who can carry it in a good way.

Perhaps look at one of the other forks and commit to them, or help organize those instead.  That way there's a chance this project will be successful again.

Again, I don't mean you any disrespect, nor do I want to discourage you.  I just think that there's already a ton of confusion around this project, and it needs a strong direction from folks who have a solid understanding.
