### ISSUE TITLE
Firefox - File transfer not working (Even in chat demo)

### ISSUE THREAD

**Issue by madawadkar** [peers/peerjs#401]
In firefox, the file transfer does not work. Even in the peerjs chat demo (http://cdn.peerjs.com/demo/chat.html), file is never received by the connected peer. It works in Chrome though.

**Comment by devrandomguy** [comment]
Confirmed, in Firefox 55.0. The console shows a bunch of deprecation warnings:

```
RTCIceServer.url is deprecated! Use urls instead.  peer.js:1513
RTCIceServer.url is deprecated! Use urls instead.  peer.js:1538
RTCIceServer.url is deprecated! Use urls instead.  peer.js:1556
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.min.js:2:40351
RTCIceServer.url is deprecated! Use urls instead.  peer.js:503
onaddstream is deprecated! Use peerConnection.ontrack instead.  peer.js:574
RTCIceServer.url is deprecated! Use urls instead.  peer.js:503
onaddstream is deprecated! Use peerConnection.ontrack instead.  peer.js:574
ICE failed, add a TURN server and see about:webrtc for more details (unknown)
```

Looks like this repo hasn't been updated since 2015. Has this library been made obsolete by something else? It's hard to imagine that something like this would be abandoned.

**Comment by madawadkar** [comment]
Test

**Comment by kidandcat** [comment]
Could you check again with latest version?
