### ISSUE TITLE
How can I add a third peer to an ongoing audio call?

### ISSUE THREAD

**Issue by Sreekanthp74** [peers/peerjs#403]
On my current code one to one call is working fine but when i try to add a new peer the communication only happen between the first and last peer, not happening the bradcasting of audio. Anyone please give me a solution.

**Comment by luongnv89** [comment]
Let's say you have 3 peers: A, B, C.
How did you set up the connection between them?
In my case, I set up a mesh network:

```
A <--> B
A <--> C
C <--> B
```

**Comment by Sreekanthp74** [comment]
Currently I am adding the clients dynamically i.e.
When 'A' is starting a session and when the client 'B' try to join, 'A'  gets the ID of client 'B' and 'A' calls the client 'B' and 'B' will join in the session. When a new client 'C' is trying to join in that call, the clients 'A' and 'B' gets notified and gets the ID of  client 'C', now now both 'A' and 'B' calls the 'C'.

This is the way that am doing currently.

**Comment by Sreekanthp74** [comment]
Currently I am adding the clients dynamically i.e.
When 'A' is starting a session and when the client 'B' try to join, 'A' gets the ID of client 'B' and 'A' calls the client 'B' and 'B' will join in the session. When a new client 'C' is trying to join in that call, the clients 'A' and 'B' gets notified and gets the ID of client 'C', now now both 'A' and 'B' calls the 'C'.

This is the way that am doing currently.

**Comment by kidandcat** [comment]
You may be overriding your connection or something, could you post your code @Sreekanthp74 ?
