### ISSUE TITLE
Peerjs not working with cordova-plugin-iosrtc for iOS 10

### ISSUE THREAD

**Issue by hardikifuturz** [peers/peerjs#405]
Peerjs browser to browser works, then integrate in Meteorjs for ios app and install iosrtc (https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc) and in ios camera started but when i call to second peer and script stopped :(

Console Error : TypeError: undefined is not a constructor (evaluating 'new RTCPeerConnection(connection.provider.options.config, optional)')

Peerjs Version : 0.3.14
IOS Version : 10.2

**Comment by hardikifuturz** [comment]
Still waiting for reply

**Comment by luispimenta** [comment]
Did you solve it?

**Comment by kidandcat** [comment]
It looks like the RTCPeerConnection is not available, that means WebRTC is not supported. Please answer if you find a solution, thanks!

**Comment by RamyaAshika** [comment]
Can you please how you made it atleast from browser to browser in safari @hardikifuturz I'm also facing the same issue. It returns as a black screen in safari when sharing media stream. @kidandcat
