### ISSUE TITLE
Is this project under development?

### ISSUE THREAD

**Issue by FelipeMiranda** [peers/peerjs#407]
I did check and it hasn't been a commit since 2015

**Comment by w-biggs** [comment]
Looks like it's not. :/

**Comment by bradisbell** [comment]
No, this project is long dead.  Worse yet, the folks that created it don't respond to e-mail, haven't commented on any issues, and are sitting on a good NPM package name.  I think we should pick one of the better forks, contact NPM, and reclaim it for the community.
