### ISSUE TITLE
decline call

### ISSUE THREAD

**Issue by novakgio** [peers/peerjs#408]
I am not much experienced in peer js and this is the first time i am working on it.
when I call from one peer to another, Let's say the receiver instantly wants to hang up. what should I do? in documentation there's not much said . docs say use disconnect event ,and as soon as it happens,the caller gets the notification,but this way it destroys peer and i will need to generate new peer_id which seems illogical. I think it would be much better if on hang up button i send dataconnection socket and the caller gets this socket and does what he wants ;)  
Or is there any better way?

THanks guys.

**Comment by kidandcat** [comment]
I would implement this by:
1- Setting another communication channel, e.g. using websockets with your server or
2- Opening first a DataChannel, and then sending the signals over there (deciding if you want to answer the call or not) and then opening or not the video channel
