### ISSUE TITLE
Codec Issue

### ISSUE THREAD

**Issue by hardikifuturz** [peers/peerjs#409]
Peer connect is established between 2 any native or browser but when 1 Android device sent streaming to 2 android device then getting "Unable to create an H.264 decoder fallback. Decoding of this stream will be broken." error. and 1 android device to browser is working perfectly.

As per my knowledge i think there is something codec issue with android device.

Peerjs Version : 0.3.14 & 0.3.15

**Comment by kidandcat** [comment]
Could you test with 0.3.15?

**Comment by kidandcat** [comment]
No feedback
