### ISSUE TITLE
can't get call event 

### ISSUE THREAD

**Issue by mdnight** [peers/peerjs#412]
I've tried call examples, presented in peerjs website, but it was unsuccessfull. When i do peer.call on one side, i don't receive call event on another side. Did anyone have the same problem?
P.S. I tested it in Firefox 57

**Comment by AsheTM** [comment]
Hi,
I have the same problems !
I can't receive the call from the other side !
I'min Google Chrome

**Comment by kidandcat** [comment]
The public server was down, I'm restoring the website and the public server, it will be working by the end of the week

**Comment by kidandcat** [comment]
Update your peerjs version and it will work
