### ISSUE TITLE
Being served over HTTP causes issues on HTTPS sites

### ISSUE THREAD

**Issue by JGames101** [peers/peerjs#413]
When attempting to use PeerJS from a site that is served over HTTP, this error appears in the console:
`Blocked loading mixed active content “http://0.peerjs.com:9000/lwjd5qra8257b9/id?ts=15151778159410.6040248252280473”`

Because the site for peerJS is served over HTTP, it is considered dangerous for the script to be loaded from there.

**Comment by 2n2n** [comment]
use a custom peerjs-server for this and host it to your vps

**Comment by Bohmaster** [comment]
@2n2n Can u please give a example or documentation how to do that? I have the exact same problem.

I'm using this: [](https://github.com/nwah/peerjs-audio-chat)

**Comment by kidandcat** [comment]
I will be adding SSL to the open server this week

**Comment by hevyhomie** [comment]
Any updates on this?

**Comment by kidandcat** [comment]
Update your peerjs version and it will work. (Even with key option, although it's useless)
