### ISSUE TITLE
Hello World Broken in Chrome Windows

### ISSUE THREAD

**Issue by snissn** [peers/peerjs#414]
On Chrome 63 on windows the hello world ( and other examples) are not working, but working fine in firefox. There should be text in the blue box but there is none.

http://cdn.peerjs.com/demo/helloworld.html

![image](https://user-images.githubusercontent.com/1981537/35181424-3bf18964-fd8f-11e7-89d5-8d7d88048c32.png)

**Comment by kidandcat** [comment]
Some PRs have been merged, could you try again? feel free to reopen if the issue persists
