### ISSUE TITLE
peer js and peer-server cannot run in vps 

### ISSUE THREAD

**Issue by geraldsamosir** [peers/peerjs#416]
i try to use peer js in my vps  i run it in here 
https://159.65.15.56:9000/ and the source is 
here https://gitlab.com/geraldsamosir/my_webrtc  
and thats work if in same hotspot but if access from deference hotspot 
cannot use video chat , can you tell me how to solve it because there are an err when i try to video call from difrent hotspot with my friends

**Comment by vincentsartoko** [comment]
Hello, do u still work on this project? I kinda need a little help :/
