### ISSUE TITLE
client for react native

### ISSUE THREAD

**Issue by geraldsamosir** [peers/peerjs#418]
can peer js connect with react native  ?
there are any client ?

**Comment by kidandcat** [comment]
No native clients exist. but some people suggest to host a webview:
https://stackoverflow.com/a/28370368

**Comment by awesomemarcus** [comment]
Hello have one tried creating react native version for this?

**Comment by kidandcat** [comment]
I don't thin react native has the same webrtc API than the browsers.

**Comment by TheadoreL** [comment]
@geraldsamosir  Have you ever try [oney/react-native-webrtc](https://github.com/oney/react-native-webrtc)

**Comment by Zemke** [comment]
I put myself to it: https://github.com/Zemke/react-native-peerjs
