### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by SkacDias** [peers/peerjs#420]
I am writing an app using https, node and peerjs ssl, below I have mentioned the code script.js

$(function(){

  var messages = [];
  var peer_id, name, conn;
  var messages_template = Handlebars.compile($('#messages-template').html());

  var peer = new Peer({
	host: '187.84.228.139',
	port: 9000,
	path: '/peerjs',
	debug: 3,
	config: {'iceServers': [
	{ url: 'stun:stun1.l.google.com:19302' },
	{ url: 'turn:numb.viagenie.ca',
	  credential: 'muazkh', username: 'webrtc@live.com' }
	]}
  });

  peer.on('open', function(){
    $('#id').text(peer.id);
  });

  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

  function getVideo(callback){
    navigator.getUserMedia({audio: true, video: true}, callback, function(error){
      console.log(error);
      alert('An error occured. Please try again');
    });
  }

  getVideo(function(stream){
    window.localStream = stream;
    onReceiveStream(stream, 'my-camera');
  });

  function onReceiveStream(stream, element_id){
    var video = $('#' + element_id + ' video')[0];
    video.src = window.URL.createObjectURL(stream);
    window.peer_stream = stream;
  }

  $('#login').click(function(){
    name = $('#name').val();
    peer_id = $('#peer_id').val();
    if(peer_id){
      conn = peer.connect(peer_id, {metadata: {
        'username': name
      }});
      conn.on('data', handleMessage);
    }

    $('#chat').removeClass('hidden');
    $('#connect').addClass('hidden');
  });

  peer.on('connection', function(connection){
    conn = connection;
    peer_id = connection.peer;
    conn.on('data', handleMessage);

    $('#peer_id').addClass('hidden').val(peer_id);
    $('#connected_peer_container').removeClass('hidden');
    $('#connected_peer').text(connection.metadata.username);
  });

  function handleMessage(data){
    var header_plus_footer_height = 285;
    var base_height = $(document).height() - header_plus_footer_height;
    var messages_container_height = $('#messages-container').height();
    messages.push(data);

    var html = messages_template({'messages' : messages});
    $('#messages').html(html);

    if(messages_container_height >= base_height){
      $('html, body').animate({ scrollTop: $(document).height() }, 500);
    }
  }

  function sendMessage(){
    var text = $('#message').val();
    var data = {'from': name, 'text': text};

    conn.send(data);
    handleMessage(data);
    $('#message').val('');
  }

  $('#message').keypress(function(e){
    if(e.which == 13){
      sendMessage();
    }
  });

  $('#send-message').click(sendMessage);

  $('#call').click(function(){
    console.log('now calling: ' + peer_id);
    console.log(peer);
    var call = peer.call(peer_id, window.localStream);
    call.on('stream', function(stream){
      window.peer_stream = stream;
      onReceiveStream(stream, 'peer-camera');
    });
  });

  peer.on('call', function(call){
    onReceiveCall(call);
  });

  function onReceiveCall(call){
    call.answer(window.localStream);
    call.on('stream', function(stream){
      window.peer_stream = stream;
      onReceiveStream(stream, 'peer-camera');
    });
  }

});

After this when I run my app, it give me this error (error in the moment of get the peer id:

What must I to do for solve this problem?

peer.js:861 GET https://187.84.228.139:9000/peerjs/peerjs/id?ts=15203472868440.4518224899442411 net::ERR_TUNNEL_CONNECTION_FAILED
Peer._retrieveId @ peer.js:861
Peer @ peer.js:796
(anonymous) @ script.js:7
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2
peer.js:1476 PeerJS:  ERROR Error retrieving ID undefined
peer.js:1476 PeerJS:  ERROR Aborting!
peer.js:1476 PeerJS:  ERROR Error: Could not get an ID from the server.
peer.js:1476 PeerJS:  ERROR Error retrieving ID ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
peer.js:1476 PeerJS:  ERROR Aborting!
peer.js:1476 PeerJS:  ERROR Error: Could not get an ID from the server.
peer.js:861 XHR failed loading: GET "https://187.84.228.139:9000/peerjs/peerjs/id?ts=15203472868440.4518224899442411".
Peer._retrieveId @ peer.js:861

**Comment by kidandcat** [comment]
Have you setup your Peer-server to use the path /peerjs? if not, just change in your client path: "/peerjs" to path: "/"

**Comment by kidandcat** [comment]
Reopen if error continues

**Comment by mrbarua** [comment]
I am getting the error. Someone Can tell me whats wrong am I doing?

peer.min.js:1 GET https://localhost:9000/peerjs/peerjs/id?ts=15345079195030.11740366878807929 0 ()
c._retrieveId @ peer.min.js:1
c @ peer.min.js:1
(anonymous) @ script.js:15
peer.min.js:1 PeerJS:  ERROR Error retrieving ID undefined
peer.min.js:1 PeerJS:  ERROR Aborting!
peer.min.js:1 PeerJS:  ERROR Error: Could not get an ID from the server.
script.js:59 Error: Could not get an ID from the server.
    at c.emitError (peer.min.js:1)
    at c._abort (peer.min.js:1)
    at XMLHttpRequest.b.onerror (peer.min.js:1)
    at XMLHttpRequest.b.onreadystatechange (peer.min.js:1)
(anonymous) @ script.js:59
d.emit @ peer.min.js:1
c.emitError @ peer.min.js:1
c._abort @ peer.min.js:1
b.onerror @ peer.min.js:1
b.onreadystatechange @ peer.min.js:1
XMLHttpRequest.send (async)
c._retrieveId @ peer.min.js:1
c @ peer.min.js:1
(anonymous) @ script.js:15
peer.min.js:1 PeerJS:  ERROR Error retrieving ID ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
peer.min.js:1 PeerJS:  ERROR Aborting!
peer.min.js:1 PeerJS:  ERROR Error: Could not get an ID from the server.
script.js:59 Error: Could not get an ID from the server.
    at c.emitError (peer.min.js:1)
    at c._abort (peer.min.js:1)
    at XMLHttpRequest.b.onerror (peer.min.js:1)
(anonymous) @ script.js:59
d.emit @ peer.min.js:1
c.emitError @ peer.min.js:1
c._abort @ peer.min.js:1
b.onerror @ peer.min.js:1
error (async)
c._retrieveId @ peer.min.js:1
c @ peer.min.js:1
(anonymous) @ script.js:15
script.js:114 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M69, around September 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

**Comment by zahra-ove** [comment]
same problem... how can I fix it?

**Comment by XolifyDev** [comment]
Welp no one ever helped. That sucks, shows that they don't care...
