### ISSUE TITLE
Peerjs in Electron - Connection issues

### ISSUE THREAD

**Issue by SpyrosKoustas** [peers/peerjs#422]
Hello, I am trying to create a peer to peer app using electron. I am able to send messages to a website that uses peerjs (locally) , but I cannot get to receive data to the electron app. Neither from the website, nor from another electron application. Please help!

Code in electron app:

_var peer = new Peer('peer-1', {key: '##########'});

peer.on('connection', function(conn) {
  conn.on('data', function(data){
    // Should print 'data!' 
    console.log(data);
  });
});_

**Comment by kas2000** [comment]
Something happened to their server. peerjs.com doesn't work

**Comment by shivamgupta-gupta** [comment]
Do you have any idea when will it be live again @kas2000 ?

**Comment by kas2000** [comment]
@shivamgupta-gupta No idea. I've started to rebuild my video chat using simple-peer:
https://github.com/feross/simple-peer

**Comment by shivamgupta-gupta** [comment]
@kas2000 but it seems that simple-peer does not work on the client side. Its CDN does not work.

**Comment by kidandcat** [comment]
I'm working on restoring this library back, you could use host: 'peerjs.com' while I setup the original domain

**Comment by SpyrosKoustas** [comment]
So does this mean that peerjs is going to get live again and work with electron ?

**Comment by kidandcat** [comment]
That's our goal, yes

**Comment by SpyrosKoustas** [comment]
Can you estimate the date of the release ?

**Comment by kidandcat** [comment]
I will be releasing a new working version this weekend, and if everything goes well and quickly, I expect to have the peerjs server online for next weekend.

If problems appear, it may be delayed to the end of this month.

**Comment by SpyrosKoustas** [comment]
Thank you in advance, this is awesome! Will publish the release when it is happening ?

**Comment by kidandcat** [comment]
yes, I will publish something on the Readme, and also I will answer all these issues related to it not working, so you will be noticed.

**Comment by kidandcat** [comment]
Update your peerjs version and it will work
