### ISSUE TITLE
how a 5k stars library goes deprecated without notice?

### ISSUE THREAD

**Issue by kidandcat** [peers/peerjs#427]
I'm sorry, but @michelle @ericz , how a 5k stars library goes deprecated without notice?

**Comment by bradisbell** [comment]
Attempts to contact those folks have always failed for me.  It's really sad when folks completely abandon their project even when it's in heavy use, without allowing someone else to take it over.

If we can all agree on a fork, we can easily contest this with NPM, to at least recover the package name for the community.

**Comment by kidandcat** [comment]
I wrote them an email, I want to wait few days, but after that, I can support you recovering the package.

**Comment by michelle** [comment]
Hi there,

I apologize for the radio silence here -- there's no excuse for it.

If someone would like to take over this project, I'm more than happy to give them full access.

**Comment by kidandcat** [comment]
Thanks @michelle , if you could give @bradisbell or me access, we will try to recover it.

**Comment by michelle** [comment]
I've gone ahead and invited you to a team with admin access.

**Comment by kidandcat** [comment]
Thanks @michelle I will start reviewing PRs in a few days, may you have the original website with the documentation?

**Comment by michelle** [comment]
@kidandcat it's a private repo, so I've invited you separately :).

**Comment by kidandcat** [comment]
I can't accept the invitation without the repo's URL :(
