### ISSUE TITLE
Failed to set remote answer sdp

### ISSUE THREAD

**Issue by doozookn** [peers/peerjs#429]
hi. i was bumped with "Failed to set remote answer sdp: Called in wrong state: kStable" when i try to connect peers from differents networks. i use ice servers (stun & turn), also i use latest version from master branch.

**Comment by kidandcat** [comment]
Could you post your browser version?

**Comment by vasserr** [comment]
I use latest chrome browsers both cases

**Comment by kidandcat** [comment]
@vasserr Did you also use version from Master branch instead of installing it from NPM?

**Comment by vasserr** [comment]
@kidandcat Yes i did. version from master

**Comment by kidandcat** [comment]
Tests are working for me on Chrome 68.0.3440.33 (Build oficial) beta (64 bits) Linux.

Could you post the code that's failing?

**Comment by kidandcat** [comment]
@doozookn @vasserr Could you test again with the latest changes? dist/ files have been rebuild so you can use them.

**Comment by kidandcat** [comment]
@doozookn @vasserr I'm closing this issue, please if the error persists with the latest changes, write here and I'll reopen it.
