### ISSUE TITLE
'RTCPeerConnection': Cannot create so many PeerConnections

### ISSUE THREAD

**Issue by antoniofaienza93** [peers/peerjs#431]
Hello everyone
I'm trying to create a multiplayer game in phaser. Once the game has been created i have two player. When i move my player (green) I can see the movement in a new page of my browser (not green). 
![schermata del 2018-07-24 12-44-53](https://user-images.githubusercontent.com/16166749/43133904-7c85666a-8f40-11e8-8fdc-14676359025d.png)
Everything works for the best. But considering that the number of movements is high, after some time you get this error:
 `VM2455:300 Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new WrappedRTCPeerConnection (<anonymous>:300:28)
    at Object.m._startPeerConnection (http://localhost/SP2P/lib/peer.js:1:33131)
    at Object.m._getPeerConnection (http://localhost/SP2P/lib/peer.js:1:32849)
    at Object.m.startConnection (http://localhost/SP2P/lib/peer.js:1:32216)
    at new d (http://localhost/SP2P/lib/peer.js:1:2579)
    at p.connect (http://localhost/SP2P/lib/peer.js:1:25072)
    at PeerClient.conn (http://localhost/SP2P/P2P/PeerClient.js:100:27)
    at Object.P2PMaze.send (http://localhost/SP2P/js/GameMultiplayer.js:42:29)
    at P2PMaze.GameMultiplayer.update (http://localhost/SP2P/js/GameMultiplayer.js:236:21)
    at Phaser.StateManager.update (http://localhost/SP2P/lib/phaser.js:31183:39)`

Peerjs Version: 0.3.9
Chrome version: 67.0.3396.62

**Comment by kidandcat** [comment]
It seems like you are creating a lot of new connections. Could you show your code?
Also it would be helpful if you use the unminified version of the library, you have it on dist/peer.js

**Comment by antoniofaienza93** [comment]
Of course. My code is this: 
`var P2PMaze = P2PMaze || {};

// global variable 
var map;
var backgroudLayer; 
var blockedLayer;
var player; 
var toOpponentPlayer = []; 
var cursor; 
var items; 

var logicalOrder = {};
var playerOrder = 1; // the player starts to 1 for compare the item to take 

var createdOpponentPlayer = false;

var opponentPlayer;

var jump = false;
var hitPlatformO;




P2PMaze.send = function(data){     
    var id = P2PMaze.peer.getConnectTo().getId();
    var conn = P2PMaze.peer.conn(id);
    P2PMaze.peer.sendData(conn, data);    
}; 

P2PMaze.GameMultiplayer = function(){
    console.log("%cStarting GameMultiplayer", "color:black; background:yellow");
};

P2PMaze.GameMultiplayer.prototype = {
    preload: function() {
        this.game.load.tilemap('temp', 'assets/tilemaps/temp.json', null, Phaser.Tilemap.TILED_JSON);
        this.game.load.image('tempImage', 'assets/images/tiles.png');

       
        this.load.spritesheet('player', 'assets/images/dude.png',32,48);        // Quello che vorrei usare 
        
     
        this.load.image('redcup', 'assets/images/estintore_grande.png');
        this.load.image('greycup', 'assets/images/greencup.png');
        this.load.image('bluecup', 'assets/images/bluecup.png');





    }, 
    create: function() {
        //  We're going to be using physics, so enable the Arcade Physics system
        this.game.physics.startSystem(Phaser.Physics.ARCADE);

       map = this.game.add.tilemap('temp'); 

       map.addTilesetImage('tiles','tempImage');

       // create the layer 
       backgroudLayer = map.createLayer('backgroudLayer');
       blockedLayer = map.createLayer('blockedLayer');


        // The number between 1 and 2000 is an index range for the tiles for which we want to enable
        // collision (in this case such a big number should include them all which is what I intended).
        // In order to obtain this number open file.json and in “layers” – “data” of the two layers 
        // find the largest number you can find, in this case 1896 so I put 2000 just to be sure I didn’t 
        // miss a slightly larger number. 
       map.setCollisionBetween(1, 200, true, 'blockedLayer'); 

       backgroudLayer.resizeWorld();


       this.createItems();
       
       var result = this.findObjectsByType('playerStart', map, 'objectLayer');


       // create the player 
       player = this.game.add.sprite(result[0].x, result[0].y, 'player');

       // create the phisics body. Can be a single object (as in this case) or of array of Objects
       this.game.physics.arcade.enable(player);

       //  Player physics properties. Give the little guy a slight bounce.
        player.body.bounce.y = 0.2;
        player.body.gravity.y = PLAYER.GRAVITY_Y;
        player.body.collideWorldBounds = true;

       // see image: 0, 1, 2, 3 is the frame for runring to left 
       // see image: 5, 6, 7, 8 is the frame for running to right 
       // 10 = frames per second 
       // the 'true' param tell the animation to loop 
       player.animations.add('left', [0, 1, 2, 3], 10, true);
       player.animations.add('right', [5, 6, 7, 8], 10, true);

      

       //the camera will follow the player in the world
       this.game.camera.follow(player); // TODO forse questo non serve

       var keyPlayer = {"key": P2PMaze.peer.getId()};
       var posx ={"posx":player.position.x};
       var posy = {"posy":player.position.y}
       var key = {"Key":player.key};       
       
        toOpponentPlayer.push(keyPlayer);
        toOpponentPlayer.push(posx);
        toOpponentPlayer.push(posy);
        toOpponentPlayer.push(key);
        P2PMaze.send(toOpponentPlayer);
        // prova = document.getElementById("prova");
        // prova.onclick = function () {  P2PMaze.send(opponentPlayer); P2PMaze.receive() };

       // move player with cursor key 
       cursor = this.game.input.keyboard.createCursorKeys();
              
    },
    update: function(){

        // creation opponent player
        if(P2PMaze.dataReceived!=undefined && createdOpponentPlayer==false){

            opponentPlayer = this.game.add.sprite(P2PMaze.dataReceived[1].posx, P2PMaze.dataReceived[2].posy, 'player');

            // create the phisics body. Can be a single object (as in this case) or of array of Objects
            this.game.physics.arcade.enable(opponentPlayer);
     
            //  Player physics properties. Give the little guy a slight bounce.
            opponentPlayer.body.bounce.y = 0.2;
            opponentPlayer.body.gravity.y = PLAYER.GRAVITY_Y;
            opponentPlayer.body.collideWorldBounds = true;
     
            // see image: 0, 1, 2, 3 is the frame for runring to left 
            // see image: 5, 6, 7, 8 is the frame for running to right 
            // 10 = frames per second 
            // the 'true' param tell the animation to loop 
            opponentPlayer.animations.add('left', [0, 1, 2, 3], 10, true);
            opponentPlayer.animations.add('right', [5, 6, 7, 8], 10, true);

     
            //the camera will follow the player in the world
            this.game.camera.follow(opponentPlayer); 

            // the opponent player start to 4 frame
            opponentPlayer.frame = 4;
            createdOpponentPlayer=true;
           
        }

     // collisio to do 
     // https://phaser.io/docs/2.4.4/Phaser.Physics.Arcade.html#collide
     var hitPlatform;
     
      hitPlatform = this.game.physics.arcade.collide(player, blockedLayer);
      if(opponentPlayer!=undefined){
        hitPlatformO = this.game.physics.arcade.collide(opponentPlayer, blockedLayer);
      }
     
     // player movement   
     // NB: comment these to gain less control over the sprite      
     // player.body.velocity.y = 0; 
     player.body.velocity.x = PLAYER.VELOCITY_X_START;

     
     if(opponentPlayer!=undefined){
        opponentPlayer.body.velocity.x = PLAYER.VELOCITY_X_START;
     }

     if(this.game.input.activePointer.justPressed()){
         // move on the direction of the input 
         this.game.physics.arcade.moveToPointer(player, 150); 
        //  player.animations.play('left');
     }

        var updatePos = [];
        if(cursor.left.isDown){
            player.body.velocity.x = PLAYER.VELOCITY_X_LEFT;         
            player.animations.play('left');
   
            // send to opponent player the left position of player
            
           
                var keyupdating = {"key": "left"};
                var updateX ={"updatePosx":player.x};
                var updateY ={"updatePosy":player.y}; // TODO secondo me questo può essere tolto e posto solo in altezza 
                updatePos.push(keyupdating);
                updatePos.push(updateX);
                updatePos.push(updateY);

                 // SEND 
                P2PMaze.send(updatePos);
            
            
            
        }else if(cursor.right.isDown){
            player.body.velocity.x = PLAYER.VELOCITY_X_RIGHT;
            player.animations.play('right');
   
            // send to opponent player the right position of player
          
            var keyupdating = {"key": "right"};
            var updateX ={"updatePosx":player.x};
            var updateY ={"updatePosy":player.y}; 
            updatePos.push(keyupdating);
            updatePos.push(updateX);
            updatePos.push(updateY);
            P2PMaze.send(updatePos);
           
            
        }
        else{
            //  Stand still
            player.animations.stop();    
            player.frame = 4;
        }
   
        // if(cursor.up.isDown && player.body.touching.down){
        if(cursor.up.isDown && hitPlatform){
            player.body.velocity.y = -250;
            }
      

     // move the opponent player to specific LEFT position
     if(opponentPlayer!=undefined && P2PMaze.dataReceived[0].key=="left"){       
        
        var posx = P2PMaze.dataReceived[1].updatePosx;
        var posy = P2PMaze.dataReceived[2].updatePosy; 
        
        // when the opponent player came to specific position + or - 1 (for avoid loop), stop the animation and set the frame to 4
        if(Math.floor(opponentPlayer.x) === Math.floor(posx) || 
           Math.floor(opponentPlayer.x) === (Math.floor(posx) +1) ||
           Math.floor(opponentPlayer.x) === (Math.floor(posx) -1)) 
        {
            opponentPlayer.animations.stop();
            opponentPlayer.frame = 4;
        }else {
            this.game.physics.arcade.moveToXY(opponentPlayer,Math.floor(posx),Math.floor(posy)); 
            opponentPlayer.animations.play('left');
        }        
       
     }

     // move the opponent player to specific RIGHT position
     if(opponentPlayer!=undefined && P2PMaze.dataReceived[0].key=="right"){         
        
        var posx = P2PMaze.dataReceived[1].updatePosx;
        var posy = P2PMaze.dataReceived[2].updatePosy; 
        
        // when the opponent player came to specific position + or - 1 (for avoid loop), stop the animation and set the frame to 4
        if(Math.floor(opponentPlayer.x) === Math.floor(posx) || 
           Math.floor(opponentPlayer.x) === (Math.floor(posx) +1) ||
           Math.floor(opponentPlayer.x) === (Math.floor(posx) -1)) 
        {
            opponentPlayer.animations.stop();
            opponentPlayer.frame = 4;
        }else {
            this.game.physics.arcade.moveToXY(opponentPlayer,Math.floor(posx),Math.floor(posy)); 
            opponentPlayer.animations.play('right');
        }        
       
     }
     // Checks for overlaps between two game objects.
     // - The first object or array of objects to check. 
     // - The second object or array of objects to check.
     // - An optional callback function that is called if the objects overlap. 
     //      The two objects will be passed to this function in the same order in which you specified them, 
     //      unless you are checking Group vs. Sprite, in which case Sprite will always be the first parameter.
     // - A callback function that lets you perform additional checks against the two objects if 
     //     they overlap. If this is set then overlapCallback will only be called if 
     //     this callback returns true
     // - The context in which to run the callbacks.
     this.game.physics.arcade.overlap(player, items, this.collect, this.choiceItems, this);
     
     if(opponentPlayer!=undefined){
        this.game.physics.arcade.overlap(opponentPlayer, items, this.collect, this.choiceItems, this);
     }
        
    },
    collect: function(player, collectable){
        console.log(collectable.key);
       
        // remove sprite
        collectable.destroy();

    },
    choiceItems: function(player, item){
        
     

       // if exist inside the hashmap a key with the same name of the sprite
       // and the value is equal of playerOrder then return true
        if((item.key in logicalOrder) && logicalOrder[item.key] === playerOrder){
            playerOrder++;                  // icrease the order of player 
            delete logicalOrder[item.key];  // delete key-value            
            return true;
        }else {
            this.game.physics.arcade.collide(player, items);
            return false;
        }
       
        
    }, 
    findObjectsByType: function(type, map, layer){

        // DEBUG
        // console.log(map);
        // console.log(map.objects);

        var result = new Array();
        map.objects[layer].forEach(function(element){
                if(element.properties.type === type ){
                    //Phaser uses top left, Tiled bottom left so we have to adjust the y position
                    //also keep in mind that the cup images are a bit smaller than the tile which is 16x16
                    //so they might not be placed in the exact pixel position as in Tiled
                    element.y -= map.tileHeight;
                    result.push(element);
                }
        });

        return result;
    },
    
    createItems: function(){

        // create items
        items = this.game.add.group();

        // If true all Sprites created with #create or #createMulitple will have a physics body created on them.
        items.enableBody = true;
        // items.physicsBodyType = Phaser.Physics.ARCADE;
         
        // result = take all element from tileset with 'item' proprieties
        var resultItem = this.findObjectsByType('item', map, 'objectLayer');
        
        
        // element = take a specific result with proprieties etc
        resultItem.forEach(function(element){    

            // Creates a new Phaser.Sprite object and adds it to the top of this group.
            // 'x' and 'y' are the coordinates that display the newly created Sprite at.The value is in relation to the group.x/group.y point
            // This is the image or texture used by the Sprite during rendering. 
            // It must matching from proprieties in Tiled and the name of sprite i.e redcup
            var spriteObject = items.create(element.x, element.y, element.properties.sprite);
            
            // enable for all sprites of object a physical properties
            this.game.physics.arcade.enable(spriteObject);
            
            // default = each objects are immovable
            spriteObject.body.immovable = true;

            // DEBUG
            //  console.log(element.properties.order + " " + element.properties.sprite);
           
            // fill the HashMap for the logic of game
            // key = sprite name
            // value = order  
            logicalOrder[element.properties.sprite] = element.properties.order;
                      
            //this.createFromTiledObject(element, items);
          }, this);
    },
    render:function() {

        // ===== DEBUG PLAYER 
        this.game.debug.body(player);
        this.game.debug.spriteInfo(player, 32, 32);

        // ===== DEBUG ITEMS
        // this.game.debug.physicsGroup(items);
        // space = 130; 
        // items.forEachAlive(this.renderGroup, this, space);       
       
    },
    renderGroup: function(member, number){
       
        this.game.debug.body(member);
        this.game.debug.spriteInfo(member, 32, number);
        space = number + 130;
    }
};`

I try to create a single connection. I create a global variable `var conn = undefined` and then assign the the connection in the update: 
` if(P2PMaze.dataReceived!=undefined && createdOpponentPlayer==false){

            opponentPlayer = this.game.add.sprite(P2PMaze.dataReceived[1].posx, P2PMaze.dataReceived[2].posy, 'player');

            ....
            var id = P2PMaze.peer.getConnectTo().getId();
            conn = P2PMaze.peer.conn(id);
            createdOpponentPlayer=true;
           
        }`
and 
`
...
...
var updatePos = [];
        if(cursor.left.isDown){
            player.body.velocity.x = PLAYER.VELOCITY_X_LEFT;         
            player.animations.play('left');
   
            // send to opponent player the left position of player
            
            if(conn!=undefined){
                    var keyupdating = {"key": "left"};
                var updateX ={"updatePosx":player.x};
                var updateY ={"updatePosy":player.y};
                updatePos.push(keyupdating);
                updatePos.push(updateX);
                updatePos.push(updateY);
                P2PMaze.send(updatePos);
             }
                
            
            
            
        }else if(cursor.right.isDown){
            player.body.velocity.x = PLAYER.VELOCITY_X_RIGHT;
            player.animations.play('right');
   
            // send to opponent player the right position of player
          if(conn!=undefined){
            var keyupdating = {"key": "right"};
            var updateX ={"updatePosx":player.x};
            var updateY ={"updatePosy":player.y}; 
            updatePos.push(keyupdating);
            updatePos.push(updateX);
            updatePos.push(updateY);
            P2PMaze.send(updatePos);
           }
            
        }
....`
But in this way my multiplayer doesn't work. For this I thought that the correct approch is 
`var id = P2PMaze.peer.getConnectTo().getId();
    var conn = P2PMaze.peer.conn(id);
    P2PMaze.peer.sendData(conn, data);`

`P2PMaze.peer` is assignment that i doing in a form in this way: 
`P2PMaze.peer = peerClient;` 
and `peerClient` is instance of my class: 
`/**
 * Class that create a peer. The param are: 
 * @param {string} id the id of my peer
 * @param {string} host the path of server
 * @param {int} port the number of port
 * @param {path} pht the app name of the server. It is useful for establish the connection
 */
class PeerClient {  
    
    

    constructor(id, h, p, pth){
        this._id = id;
        this._host = h;
        this._port = p;
        this._path = pth;
        this._peerToConnect = undefined;
 
        this._peer = new Peer(this._id, {
            host: this._host, // 'localhost',
            port: this._port, //  9000,
            path: this._path // '/peerjs'
        });

    }

    /**
     * Return the id of my peer
     */
    getId() {
        return this._id;
    }

    

    /**
     * Return the peer connected with me
     */
    getConnectTo() {
        return this._peerToConnect;
    }
    
    /**
     * This metohd is used for setting the peer with i want connect. It used when I receive the request of 
     * connection by a specific peer. 
     * @param {peer} peerToConnect 
     */
    setConnectTo(peerToConnect){
        this._peerToConnect = new PeerClient(peerToConnect, this._host, this._port, this._path);
    }

    
    /**
     * This allow to create the player
     * @param {*} x initial position x
     * @param {*} y initial position y
     * @param {*} identifierString the unique string by which we'll identify the image later in our code.
     */
    createPlayer(x,y, identifierString){
        return P2PMaze.game.add.sprite(x,y,identifierString)
    }

    /**
     * Make the peer avilable for the connection 
     */
    openConnection() {
        this._peer.on('open', function(id_peer) {
          console.log('My peer ID is: ' + id_peer); //DEBUG
        });
    }

    
    /**
     * Closes the data connection gracefully, cleaning up underlying DataChannels and PeerConnections.
     * REF:https://stackoverflow.com/questions/25797345/peerjs-manually-close-the-connection-between-peers 
     * @param {object} conn i
     */
    closeConnection(conn) {
        conn.on('open', function(){            
            conn.close();
            alert("CONNESSIONE CHIUSA"); // TODO mettere un qualche messaggio
          });
    }
    
    /**
     * See the error of peer .     * .
     */
    seeError(){
        this._peer.on('error', function(err){
            alert(err.message);
        });
    }

    
    /**
     * This method is used for create a connection
     * @param {object} id_another_peer is the id of peer that I want to connect
     */
    conn(id_another_peer) {
        return this._peer.connect(id_another_peer);
    }

    

   
    /**
     * Sharing data among peer. The first param is the value that return from the previusly method (conn)
     * @param {object} conn     this is the connection
     * @param {object} data     this is the data to send
     */
    sendData(conn, data) {
        conn.on('open', function(){
            conn.send(data);
          });
    }
    
    /**
     * This method is used for receive data.
     * @param {method} callback return the data that arrived from sender
     */
    enableReceptionData(callback) {
        this._peer.on('connection', function(conn) {
            conn.on('data', function(data){
                console.log("--------------------------------");
                console.log("MESSAGGIO RICEVUTO : \n");
                console.log(data);
                console.log("--------------------------------");
                callback(data);                
            });
        });
    }


}`

**Comment by kidandcat** [comment]
If I'm not wrong, here:
```
P2PMaze.send = function(data){     
    var id = P2PMaze.peer.getConnectTo().getId();
    var conn = P2PMaze.peer.conn(id);
    P2PMaze.peer.sendData(conn, data);    
     }; 
```

You are opening a new connection every time you want to senda  message. You should save your created connection somewhere, and use it for all messages, for example, something like this:

```
P2PMaze.connect = function(data){     
    var id = P2PMaze.peer.getConnectTo().getId();
    P2PMaze.otherPlayer = P2PMaze.peer.conn(id);
}; 

P2PMaze.send = function(data){
    P2PMaze.otherPlayer.send(data);   
}
```

Use the `send` method from the connection object:
https://peerjs.com/docs/#dataconnection-send

And listen for the `data` event on the connection:
https://peerjs.com/docs/#dataconnection-on-data

**Comment by kidandcat** [comment]
```
sendData(conn, data) {
       conn.on('open', function(){
            conn.send(data);
        });
}
```

Here you are creating a new listener, and when the event 'open' come, you send the data. You should just send the data:

```
sendData(conn, data) {
       conn.send(data);
}
```

The Open event is to check if the connection has been established. You can check for it, or you can just send the data and let it fail if the connection is not still open.

**Comment by antoniofaienza93** [comment]
ooooh very good. Thanks. I did not understand. When i try my code i post the result. thanks thanks thans

**Comment by antoniofaienza93** [comment]
Ok it works, but now i don't receive the data:
`/**
     * This method is used for receive data.
     * @param {method} callback return the data that arrived from sender
     */
    enableReceptionData(callback) {
        this._peer.on('connection', function(conn) {
            conn.on('data', function(data){
                console.log("--------------------------------");
                console.log("MESSAGGIO RICEVUTO : \n");
                console.log(data);
                console.log("--------------------------------");
                callback(data);                
            });
        });
    }`
I see from console that the connection and the sharing of data is ok, but this method doesn't work. Can you explain me why ?

**Comment by antoniofaienza93** [comment]
If I undestrand the `conn.on('open', function(){ .. }` can be omitted. But if i print in the console: 
`       

        enableReceptionData(callback) {

        console.log(conn); // IMPORTANT
 
        this._peer.on('connection', function(conn) {

        conn.on('data', function(data){

            console.log("--------------------------------");
            console.log("message received : \n");
            console.log(data);
            console.log("--------------------------------");

            callback(data);                
        });
    });
}

` 

I retrieve this message: 
d {_events: {…}, options: {…}, open: false, type: "data", peer: "zzz-6UsEonI", …}
you can see the open is false. 
My new PeerClass is this: 
`        /**
         * Class that create a peer. The param are: 
         * @param {string} id the id of my peer
         * @param {string} host the path of server
         * @param {int} port the number of port
         * @param {path} pht the app name of the server. It is useful for establish the connection
         */
        class PeerClient {  
            
            

            constructor(id, h, p, pth){
                this._id = id;
                this._host = h;
                this._port = p;
                this._path = pth;
                this._peerToConnect = undefined;
                this._conn = undefined;
        
                this._peer = new Peer(this._id, {
                    host: this._host, // 'localhost',
                    port: this._port, //  9000,
                    path: this._path // '/peerjs'
                });

            }

            /**
             * Return the id of my peer
             */
            getId() {
                return this._id;
            }

            

            /**
             * Return the peer connected with me
             */
            getConnectTo() {
                return this._peerToConnect;
            }
            
            /**
             * This metohd is used for setting the peer with i want connect. It used when I receive the request of 
             * connection by a specific peer. 
             * @param {peer} peerToConnect 
             */
            setConnectTo(peerToConnect){
                this._peerToConnect = new PeerClient(peerToConnect, this._host, this._port, this._path);
            }

            
            /**
             * This allow to create the player
             * @param {*} x initial position x
             * @param {*} y initial position y
             * @param {*} identifierString the unique string by which we'll identify the image later in our code.
             */
            createPlayer(x,y, identifierString){
                return P2PMaze.game.add.sprite(x,y,identifierString)
            }

            /**
             * Make the peer avilable for the connection 
             */
            open() {
                this._peer.on('open', function(id_peer) {
                console.log('My peer ID is: ' + id_peer); //DEBUG
                });
            }

            openConnection(){
                this._conn.on('open', function(data){
                    console.log(data);
                });
            }
            
            /**
             * Closes the data connection gracefully, cleaning up underlying DataChannels and PeerConnections.
             * REF:https://stackoverflow.com/questions/25797345/peerjs-manually-close-the-connection-between-peers 
             * @param {object} conn i
             */
            closeConnection(conn) {
                conn.on('open', function(){            
                    conn.close();
                    alert("CONNESSIONE CHIUSA"); // TODO mettere un qualche messaggio
                });
            }
            
            /**
             * See the error of peer .     * .
             */
            seeError(){
                this._peer.on('error', function(err){
                    alert(err.message);
                });
            }

            
            /**
             * This method is used for create a connection
             * @param {object} id_another_peer is the id of peer that I want to connect
             */
            conn(id_another_peer) {
                this._conn =  this._peer.connect(id_another_peer);
                return this._conn;
            }

            /**
             * return the connection
             */
            getConnection(){
                return this._conn;
            }
            

        
            /**
             * Sharing data among peer. The first param is the value that return from the previusly method (conn)
             * @param {object} conn     this is the connection
             * @param {object} data     this is the data to send
             */
            // sendData(data) {
            //     this._conn.on('open', function(){
            //         this._conn.send(data);
            //       });
            // }
            sendData(data) {
                this._conn.send(data);
            }

            
            /**
             * This method is used for receive data.
             * @param {method} callback return the data that arrived from sender
             */
            enableReceptionData(callback) {
                this._peer.on('connection', function(conn) {
                    console.log(conn);
                    conn.on('data', function(data){
                        console.log("--------------------------------");
                        console.log("MESSAGE UPDATED : \n");
                        console.log(data);
                        console.log("--------------------------------");
                        callback(data);                
                    });
                });
            }


        }`

**Comment by kidandcat** [comment]
When you open the connection in:
```
 conn(id_another_peer) {
            this._conn =  this._peer.connect(id_another_peer);
            return this._conn;
        }
```

You should inmediatly start listening the events, so:

```
 conn(id_another_peer) {
            this._conn =  this._peer.connect(id_another_peer);
            this.enableReceptionData();
            return this._conn;
 }
```

**Comment by antoniofaienza93** [comment]
ok thanks for the patience, as soon as I implement the code I will post the result :+1:

**Comment by antoniofaienza93** [comment]
No this continues to not work.

**Comment by antoniofaienza93** [comment]
thank you so much for the opportunity. At the moment my code is an open construction site. As soon as I have arranged it I will make it available. In the meantime, when you have time, could you tell me if the last solution I indicated could be a good approach to the problem?
Thanks again and see you soon :)

**Comment by kidandcat** [comment]
The second solution would be much recommended. The first one will give you a lot of troubles because you are creating a lot of connections, one per message, and that will not only lead you to the first error you got from PeerJS, but it will also beat your resources (cpu, ram, network)

**Comment by antoniofaienza93** [comment]
I confirm that with the second solution I avoid the error. For this, now I have only two connection: 
- the first: from A to B
- the second: from B to A
The other exchange of data is execute with the same connection. Thank @kidandcat for your support. :+1:
