### ISSUE TITLE
Receiving audio but not video

### ISSUE THREAD

**Issue by LucaColombi** [peers/peerjs#435]
I am correctly receiving audio stream but video is stripped off:

outgoing audio: [MediaStreamTrack]0: MediaStreamTrack {kind: "audio", id: "7ba82f29-61c6-4e90-a30e-d4560459b641", label: "", enabled: true, muted: false, …}
outgoing video: [MediaStreamTrack]0:
```
MediaStreamTrack{
enabled:true
id:"02e8f242-a845-40d6-ac92-fa21fb6abb3a"
kind:"video"
label:"camera 1, facing front"
muted:false
onended:null
onmute:null
onunmute:null
readyState:"live"
}
```

incoming audio:[MediaStreamTrack]0: MediaStreamTrack {kind: "audio", id: "7ba82f29-61c6-4e90-a30e-d4560459b641", ...
incoming video:[] //NONE

Is it possibile that calling with only audio stream blocks the incoming video stream?

Otherwise what could stop the incoming video stream and let audio working correctly?

**Comment by LucaColombi** [comment]
Hello, this is not a bug I confirm that if not video is sent, no video can be received, I solved with a fake video sent:

```
					let w = 640;
					let h = 480;
					let canvas: any = Object.assign(document.createElement("canvas"), { w, h });
					canvas.getContext('2d').fillRect(0, 0, w, h);
					let blackStream = canvas.captureStream();
					outgoingStream.addTrack(blackStream.getVideoTracks()[0]);
```

Anyway it would be nice to do this automatically or even better let receive video even if not video is sent

**Comment by afrokick** [comment]
I think it is an application level logic. May be in future we provide some helpers for that.
