### ISSUE TITLE
PeerJS and Socket.IO conflict

### ISSUE THREAD

**Issue by shubhendumadhukar** [peers/peerjs#440]
This is not really an issue rather a doubt.

I am using PeerJS and Socket.IO both in my application. Could that create a conflict between the two?

I am not sure because I am facing an issue where I am running the app on localhost and it seems to be working fine but when deployed to Azure, even though all requests and responses are similar, the socket connections aren't established.

Has anyone faced such issue before?

**Comment by shubhendumadhukar** [comment]
It must have been an issue with Azure hosting. I moved my application from Azure to Google cloud where I personally found more control over the ports. And I was able to get the application working.
Thanks.

**Comment by kidandcat** [comment]
Nice!
