### ISSUE TITLE
iOS 11.2 DataConnection on Data won't trigger.

### ISSUE THREAD

**Issue by capripio** [peers/peerjs#441]
I implemented peer.js in a hybrid application.  everything working fine. but issue regards iOS 11.2 peer.js don't fire data event thus. no data received.

**Comment by hshahtech** [comment]
The peerjs is currently based on WebRTC which is not supported on the iOS unless you have chrome browser installed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by wardhanster** [comment]
@capripio I think this is more of a safari issue rather than iOS.
I noticed similar behavior when I was working with simplewebrtc. The reason in my case was a failure when the handshake was happening. Can you elaborate on the browsers who were trying to connect and any other relevant info?
