### ISSUE TITLE
Fault Managment

### ISSUE THREAD

**Issue by antoniofaienza93** [peers/peerjs#442]
Good Afternoon, 
I want to ask about the fault management between two peers after the connection has been established. I have seen from [documentation](https://peerjs.com/docs/#peeron-error)  (and i try it) that if I establish a connection with a new peer that is disconnected, i obtain: 'peer-unavailable'. Right. 
But if i have already establish connection between peer A and peer B and B for example refresh the page, then the peer A is able to send message to peer B. Are there a way for take a feedback/callback ? I think that one possible solution is make a server-request. Is it correct ?

**Comment by kidandcat** [comment]
Sorry, I don't get your point, if you refresh the page, the browser will try to reconnect everything, so it will be  as nothing happened for the user. The behavior will be different if you for example open the url in another tab.

**Comment by antoniofaienza93** [comment]
Exactly, if the I refresh the page are there callback from the server ?
Now i have resolved whit a polling that every 5 second ask to the server if
a peer is disconnected.



Il giorno gio 30 ago 2018 alle ore 10:32 Jairo Caro-Accino Viciana <
notifications@github.com> ha scritto:
