### ISSUE TITLE
Release the latest version on ALL channels - or ONLY use npm

### ISSUE THREAD

**Issue by Masterxilo** [peers/peerjs#443]
https://peerjs.com/ lists 0.3.9 as the latest version.

https://github.com/peers/peerjs/releases has 0.3.14

only https://www.npmjs.com/package/peerjs has the proper 0.3.16

Please fix this. There seem to be some weird bugs with 0.3.14 and I ran into them...

PS: When you're at it, for the sake of transparency, why not remove the possibility to contact you via team@peerjs.com, making github the only forum about this?

**Comment by kidandcat** [comment]
Everything done!
