### ISSUE TITLE
Throw proper errors in unsupported browsers

### ISSUE THREAD

**Issue by Masterxilo** [peers/peerjs#444]
Apparently this does not work in Microsoft EDGE. Please use a console.error message to indicate this - makes troubleshooting easier.

**Comment by kidandcat** [comment]
It should work as Edge has implemented WebRTC and  it is on adapter.js. Let me have a look if there is any guard on the code blocking it. Also, it would be very helpful if you give me any info you got. It will be a little big hard for me because I don't have any Windows machine near

**Comment by Masterxilo** [comment]
But you are right, it should work - I can properly receive a stream on appr.tc

What am I doing wrong?

**Comment by kidandcat** [comment]
Edge has partial support for webrtc (calls yes but not data channels) so I will think a way of handle this

**Comment by afrokick** [comment]
We supported only Chrome 72+, Firefox 59+ and Safari 12.1+
