### ISSUE TITLE
Peerjs doens't work with Firefox 52.9.0

### ISSUE THREAD

**Issue by antoniofaienza93** [peers/peerjs#446]
Hi,
i am trying my project from Firefox 52.9.0 and Chrome 67.0.3396.62. 
I have visited this link: https://peerjs.com/status/ and this https://caniuse.com/#feat=rtcpeerconnection and i have seen that this version of firefox is not supported. Ok. My question is: 
Should not I get a 'browser-incompatible' error message? 

thanks

**Comment by kidandcat** [comment]
You mean in the status page? or when trying to use the library?

**Comment by antoniofaienza93** [comment]
mmm yes, i noticed that when I am under the university Network  all browsers doesn't work. 
Now i want see if with an STUN/TURN IceServer it work. For this i change my object peer in this way: 




            `this._peer = new Peer(this._id, {

            host: this._host, // 'localhost',

            port: this._port, //  9000,

            path: this._path, // '/peerjs'   
  
            config: {'iceServers': [
                  { url: 'stun:stun.l.google.com:19302' },
                  { url: 'turn:homeo@turn.bistri.com:80', credential: 'homeo' }
             ]}
        });`

My question now is: 

- Can be depend of this?

- In case of Yes, Can I use I list of STUN Server that can be find inside the Network ? (i.e: https://gist.github.com/mondain/b0ec1cf5f60ae726202e) or i configure my Stun Server ?

- In case of No, What can depend on ?

Thanks

**Comment by kidandcat** [comment]
Webrtc should work if there is at least one port open, also if you are not using a custom PeerServer, the PeerServer Cloud service uses port 9000 so...

**Comment by antoniofaienza93** [comment]
ok, i have found the problem (I hope). My university network, has a particular DNS that avoid the connection from different PC. For this reason, when i want establish a comunication with an other peer the comunication can't be establish.

My PeerServer is combined with Express (https://github.com/peers/peerjs-server#combining-with-existing-express-app). For this reason when I'm in local, i can set the port on 9000, but when I deploy, 
i must use process.env.PORT.

**Comment by maxpavlov** [comment]
@antoniofaienza93 if your issue is resolved, please close the ticket. We need to clear up the issues for the project if we expect it to move forward.
