### ISSUE TITLE
WebRTC video calling broken by Firefox update from 61.0.2 to 62.0

### ISSUE THREAD

**Issue by osnoww** [peers/peerjs#447]
The update of Firefox from version 61.0.2 to version 62.0 has broken video calling in my application. Neither outgoing nor incoming calls to FF work.

Calls between Chrome / Chrome and Chrome / my app continue to work.

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/62 indicates some media related changes, but nothing obviously the root cause

**Comment by bradisbell** [comment]
Surely the issue is this?  https://bugzilla.mozilla.org/show_bug.cgi?id=1454889

Are you using `URL.createObjectURL()`?

**Comment by osnoww** [comment]
Thanks Brad,
Possibly. Looking through the code now. Cheers
Oliver

**Comment by osnoww** [comment]
> Surely the issue is this? https://bugzilla.mozilla.org/show_bug.cgi?id=1454889
> 
> Are you using `URL.createObjectURL()`?

Brad, you were spot on. Thanks! I owe you a beer :-)
