### ISSUE TITLE
Getting Syntax error "SCRIPT5022: SCRIPT5022: SyntaxError" on Edge Browser

### ISSUE THREAD

**Issue by Sreekanthp74** [peers/peerjs#452]
When I try to initiate the peer setup in Microsoft Edge browser am getting an error from peer.min.js file. (peerjs build:0.3.16, production)
**

> SCRIPT5022: SCRIPT5022: SyntaxError

**

But it is working fine on chrome, safari and firefox

Please give me a quick solution.Because its very critical for me.

**Comment by kidandcat** [comment]
What are you trying to do, call (audio or video) or data channel?

**Comment by kidandcat** [comment]
Edge does not completely support webrtc yet, closing issue because lack of details

**Comment by Sreekanthp74** [comment]
@kidandcat 
I was trying to do audio/video call. But while creating the new Peer i got this syntax error.
![error](https://user-images.githubusercontent.com/11881498/46594116-adb2bf00-caee-11e8-95b2-8f0fd023c78c.PNG)

My code for creating new peer is
`            peer = new Peer(my_peer_id, {
                host: '/',
                port: '',
                path: '/peerjs',
                debug: 3,
                config: {
                    iceServers: [array of ice servers]
                }
            });`

**Comment by kidandcat** [comment]
Could you post any log in your browser console?

**Comment by Sreekanthp74** [comment]
Codes am trying to make the connection is 

           ```
           peer = new Peer(peer_id, {
                host: '/',
                port: '',
                path: '/peerjs',
                debug: 3,
                config: {
                    iceServers: result
                }
            });

            // Once the initialization succeeds:
            peer.on('open', function() {

            });

            // When someone connects to your session:
            peer.on('connection', function(connection) {

            });

           peer.on('call', onReceiveCall);

            peer.on('error', function(err) {
                // alert("An error ocurred with peer: " + err);
                console.log(err);
                if (err.type == 'network') {
                    switch (err.message) {
                        case 'Lost connection to server.':
                            // peer.reconnect();
                            console.log('Client Disconneted');
                            break;
                        default:
                            // peer.reconnect();
                            break;
                    }
                }
            });

            peer.on('disconnected', function(){
                console.log('Peer disconnected');
            });

            peer.on('close', function(){
                console.log('Peer close');
            })
```


but getting error while initializing .i.e. when calling peer = new Peer() itself am getting the syntax error. Please find the snap shot attached
![log_snap](https://user-images.githubusercontent.com/11881498/47838081-3c57ea80-ddd4-11e8-8a86-9104bedd1774.PNG)

**Comment by kidandcat** [comment]
Edge partially implements WebRTC, so I recommend you not to use it until it
is fully supported.

**Comment by Sreekanthp74** [comment]
@kidandcat  Yes I know, but i am able get my local media stream using adapter.js shim. The issue is only with creating the peer connection. This is a syntax error right?

**Comment by Sreekanthp74** [comment]
Any update on this guys?

**Comment by kidandcat** [comment]
No sorry. I haven't been able to test on a Windows machine.

**Comment by afrokick** [comment]
Sorry, we didn't support edge
