### ISSUE TITLE
relay mode does  not working even  when TURN server is provided

### ISSUE THREAD

**Issue by ivanhxq** [peers/peerjs#456]
Network penetration failure will not go relay even  when TURN server( coturn )  is provided.I can be sure my turn server relay is ok when  I tested with pjsip .But it does not work with peerjs &&webrtc. I try seveal  config as below:

1)	    var peer = new Peer({
        host: "132.232.32.161",
        port: 9000,
        path: '/peerjs',
        debug: 3,
		iceTransportPolicy: 'relay',
        config: {
            'iceServers': [
                { url: 'stun:132.232.32.161' },
                {
                    url: 'turn:132.232.32.161:3478',
                    credential: 'ling',
                    username: 'ling1234'
               }
            ]
			
        }
    });

2) var peer = new Peer({
        host: "132.232.32.161",
        port: 9000,
        path: '/peerjs',
        debug: 3,
		iceTransportPolicy: 'relay',
        config: {
            'iceServers': [
                {
                    url: 'turn:132.232.32.161:3478',
                    credential: 'ling',
                    username: 'ling1234'
               }
            ]
			
        }
    });

3)	 var peer = new Peer({
        host: "132.232.32.161",
        port: 9000,
        path: '/peerjs',
        debug: 3,
        config: {
            'iceServers': [
                { url: 'stun:132.232.32.161' },
            ]
			
        }
    });

4)	    var peer = new Peer({
        host: "132.232.32.161",
        port: 9000,
        path: '/peerjs',
        debug: 3,
		iceTransportPolicy: 'relay',
        config: {
            'iceServers': [
                { url: 'stun:132.232.32.161' },
                {
                    url: 'turn:132.232.32.161:3478?transport=tcp',
                    credential: 'ling',
                    username: 'ling1234'
               }
            ]
			
        }
    });

ALL of these config do not work.Anyone can help? thanks!

**Comment by kidandcat** [comment]
Mmm, the use of TURN servers is managed by the browser, do you have a firewall on any of the machines?

**Comment by RamyaAshika** [comment]
I'm too working on this issue only I have configured my coturn project and started a server as well as I have configured my configuration in my code like the way uh did @ivan but I don't see any logs when I'm sharing my mediastream.

**Comment by kidandcat** [comment]
But do you have any problem sharing mediaStreams @RamyaAshika ?

**Comment by afrokick** [comment]
It seems like coturn's timeout.

**Comment by afrokick** [comment]
I tested config - it works fine.

Coturn has timeout for session, you should increase it in config file.

**Comment by afrokick** [comment]
> No its disconnecting after 5-6mins @kidandcat

https://github.com/coturn/coturn/issues/332

**Comment by RamyaAshika** [comment]
Can you please tell me how you have configured in coturn's config file @afrokick

**Comment by pcvengros** [comment]
> Can you please tell me how you have configured in coturn's config file @afrokick

make sure your coturn config file has disabled "stale-nonce" option

**Comment by RamyaAshika** [comment]
how to do that? @pcvengros I have overwritten the config file like this stale-nonce=600 to stale-nonce=3600. Is it correct?

**Comment by pcvengros** [comment]
> how to do that? @pcvengros I have overwritten the config file like this stale-nonce=600 to stale-nonce=3600. Is it correct?

just comment it out..

`# Uncomment if extra security is desired,
# with nonce value having limited lifetime (600 secs).
# By default, the nonce value is unique for a session,
# but it has unlimited lifetime. With this option,
# the nonce lifetime is limited to 600 seconds, after that
# the client will get 438 error and will have to re-authenticate itself.
#
#stale-nonce`

**Comment by afrokick** [comment]
@RamyaAshika 
```
listening-port=3478
tls-listening-port=5349
listening-ip=122.122.122.122
relay-ip=122.122.122.122
external-ip=122.122.122.122
lt-cred-mech
server-name=xxx.com
user=nick:pass123
realm=xxx.com
```

**Comment by afrokick** [comment]
Ok, i suggest to close this issue. If anybody need a help - please, open another one.

**Comment by RamyaAshika** [comment]
Hey, it's not working for me listening-port=3478
tls-listening-port=5349
listening-ip=xx.xx.xx.xx
relay-ip=xx.xx.xx.xx
external-ip=xx.xx.xxx.xxx
user=test:test@123
lt-cred-mech
userdb=/etc/turnuserdb.conf 

@afrokick @pcvengros

**Comment by RamyaAshika** [comment]
Where that file will be there @pcvengros in turn server??

**Comment by afrokick** [comment]
@RamyaAshika why you use userdb?

**Comment by RamyaAshika** [comment]
I don't have server-name and realm fields. Is it necessary? @afrokick

**Comment by RamyaAshika** [comment]
and this is how I'm starting my server turnserver -v -r xx.xx.xxx.xxx:3478 -a -b turnuserdb.conf -c turnserver.conf -u test:test@123 @afrokick

**Comment by afrokick** [comment]
@RamyaAshika just use config file `/etc/turnserver.conf` and run server via shell `$> turnserver`

try remove userdb field

**Comment by afrokick** [comment]
I'm not expert with coturn and i think that a good place to get answer about settings is https://github.com/coturn/coturn issue's

**Comment by RamyaAshika** [comment]
But peer only disconnecting right after a 5-10mins whether it's happening only because of coturn or peerjs?? @afrokick

**Comment by afrokick** [comment]
I think the issue in coturn's config file - you should properly tune it. Because peerjs doesn't have such timeouts
