### ISSUE TITLE
could not get an id from the server peerjs

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#457]
It worked perfectly but suddenly from yesterday the peer id is not generating?

**Comment by thienanh96** [comment]
The same problem

**Comment by kidandcat** [comment]
Yesterday servers went down. I've changed the server provider. But right now only WSS (Websocket secure) connections are allowed. 

To use WSS you need to setup these configuration:

      new Peer({host: "https://0.peerjs.com"})

Or simply update the library to version 0.3.18 and it will connect automatically without configuration (using WSS which uses port 443)

**Comment by RamyaAshika** [comment]
Is this possible to transfer the stream of canvas to a remote connection? @kidandcat

**Comment by kidandcat** [comment]
@RamyaAshika I answered you in the related issue, I'm closing this issue.

**Comment by PeadarO** [comment]
0.3.18 is only available in 32 bit.  - I'm still stuck

**Comment by PeadarO** [comment]
I've tried installing 12.18.2    12.18.3   13.10.0     14.0.0  an dI am still getting   "could not get an id from the server"

**Comment by PeadarO** [comment]
KidAndKat,  You have suggested   new Peer({host: "https://0.peerjs.com"})   but I don'w know what that is. What do I do with it?

**Comment by ats1999** [comment]
start peer 
```js
peerjs --port 5001
```
