### ISSUE TITLE
Is this possible to transfer the stream of canvas to remote connection?

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#460]
I have connected the peers between user A and user B that works fine. Now I need to send a canvas stream to the remote connection canvas with the same peer ID. Is it possible?

Thanks in advance.

**Comment by kidandcat** [comment]
Yes, it is possible, you can use https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream

**Comment by RamyaAshika** [comment]
Ok Fine. But I already created a connection between user A and user B and shared the media stream. Now with the same connection, I need to share my canvas stream from user A to user B. Is it possible? @kidandcat

**Comment by kidandcat** [comment]
You need to create another connection. One per new stream.

**Comment by RamyaAshika** [comment]
So !! For canvas one connection, I need to create and for the media stream, I need to create another connection? But this is the one I'm trying to do
https://www.youtube.com/watch?v=yC2OnESpcf4 using peerjs and canvas Is it possible? @kidandcat

**Comment by kidandcat** [comment]
Almost yes, but they are using Augmented Reality for the draws to stay on their place. Probably ARCore and ARKit. For the streams the only thing is that you need to make one call per stream, so you will need to do 2 calls, one for the video and another one for the canvas.

**Comment by RamyaAshika** [comment]
Yes, but for video application, I have used webRTC. Now which way I can go to achieve like what they did? Whether by canvas can I acheieve like the way I'm expecting? @kidandcat

**Comment by Sreekanthp74** [comment]
@RamyaAshika  you can create data connection using **peer.connect()** for passing the values from one end to another. By using the data connection you can send the canvas drawing coordinates  and you can plot the point in another end. And by using **peer.call()** and **peer.answer()** you can make video or audio calls.

**Comment by kidandcat** [comment]
Yes, you can overlay a canvas on top of a video.

**Comment by RamyaAshika** [comment]
Ok, I will try and let you know. Thanks @kidandcat

**Comment by RamyaAshika** [comment]
But whether it will reflect on user B from user A over the video which I'm doing on canvas? @kidandcat

**Comment by kidandcat** [comment]
Yes, you can transmit the canvas by obtaining a mediastream from it (look
into MDN docs).

**Comment by RamyaAshika** [comment]
Okay, thanks, I will try and let you know @kidandcat

**Comment by RamyaAshika** [comment]
Hey I have done that but both  are colliding each other   var 
var stream = can.captureStream();
myvideo.srcObject=stream;

Like this, I captured my stream and if I'm doing it in the single page it works fine but when I'm trying to send this to my peer connection it's taking as a video stream and hiding my background video and this canvas stream is showing.

   peer.on('connection', function (conn1) {
                    conn1.on('data', function (data) {
                        var conn = peer.connect(data);
                        conn.on('open', function () {
			var can = document.getElementById("cv1");                           
                               var  stream = can.captureStream();
				 myvideo1.srcObject=stream;
			 conn = peer.call(data, stream);       
                        });
                    });
                })
and this is how I have connected. Is there any other way to send only canvas stream to my peer connection? @kidandcat @Sreekanthp74

**Comment by Sreekanthp74** [comment]
@RamyaAshika 
Please do the stream capture on
peer.on('call', onReceiveCall);
on receive call you can do 
```
                 call.answer(localStream);
                // Receive data
                call.on('stream', function (remoteStream) {
                    // Store a global reference of the other user stream
                    // window.peer_stream = remoteStream;
                    // Display the stream of the other user in the peer-camera video element !
                    onReceiveStream(remoteStream);
                });

                // Handle when the call finishes
                call.on('close', function(){
                    console.log("The videocall has finished");
                });

```


and for calling peer with peer id 
```

    function callPeer(peerId, stream, metadata) {
        var test = getPeer(peerId);
        console.log('Peer going to call :---------' + JSON.stringify(test));
        var outgoing = peer.call(peerId, stream, metadata);

        outgoing.on('stream', function(remoteStream) {
            // window.peer_stream = remoteStream;
            onReceiveStream(remoteStream);
        });

        outgoing.on('close', function() {
            console.log("Peer outgoing close");
            stopLocalStreamTrack();
        });

        outgoing.on('error', function() {
            console.log("Peer outgoing error");
            stopLocalStreamTrack();
        });
    }

```

onReceiveStream(); will always get the remote stream and there you can play with the remote stream.

**Comment by RamyaAshika** [comment]
I am trying to capture html5 canvas using captureStream API which has drawings on it and play it using html5 video tag. The problem I am facing this when I capture the stream and play it within video tag It plays exactly same. But when I send that stream to another peer (webRTC Streaming) and play it there.

It gets played with the black background. i.e. video is not transparent anymore. 

So this is the problem I'm facing so this is the solution for this? @Sreekanthp74

**Comment by Sreekanthp74** [comment]
@RamyaAshika  Sorry, I thought you are having issue with the peer stream. 
But html video tag background can be changed with the 'CSS' itself , 
just add this to test it 
```
video {
    object-fit: none; /* or scale-down */
    background: blue;
} 
```
But am not sure about the video background. Am not much familiar with captureStream API.

**Comment by RamyaAshika** [comment]
Ok Can we make it as transparent? @Sreekanthp74

**Comment by RamyaAshika** [comment]
Heii I had made this successfully on chrome, firefox and so on by making two media connections I can able to share the video as well as on top of that I can able to pass canvas but now it's not working in safari. When we making two media connections using getUserMedia(). In safari disables the first connection and show the black screen. I want to pass my canvas stream from peer.call() without getUserMedia.Please help needed. Is that possible? @kidandcat  @Sreekanthp74

**Comment by kidandcat** [comment]
Safari is slowly supporting WebRTC and other APIs, but it still has incompatibilities. I'm fading similar issues at work related to Service Workers . . . there is nothing to do but wait for Apple.

**Comment by RamyaAshika** [comment]
OMG !! I need to do urgently. But in this document I'm seeing without media stream we can able to do something like that https://peerjs.com/docs/#peercall

_When calling or answering a call, a MediaStream should be provided. The MediaStream represents the local video (webcam) or audio stream and can be obtained with some (browser-specific) version of navigator.getUserMedia . When answering a call, the MediaStream is optional and if none is provided then a one-way call is established. Once the call is established, its open property is set to true._

How can we set this open property as true and if I set, Can I able to receive streams? @kidandcat

**Comment by RamyaAshika** [comment]
Ya sure.
https://ec239ffa.ngrok.io/ARTC/Support.html

https://ec239ffa.ngrok.io/ARTC/LinkToConnect.html?roomId=gby6tophcwf00000 @kidandcat

**Comment by RamyaAshika** [comment]
I fixed it. Thanks.

**Comment by simonbuehler** [comment]
@RamyaAshika i have the exact same problem, what was your fixed solution?

**Comment by gushenjie** [comment]
> Heii I had made this successfully on chrome, firefox and so on by making two media connections I can able to share the video as well as on top of that I can able to pass canvas but now it's not working in safari. When we making two media connections using getUserMedia(). In safari disables the first connection and show the black screen. I want to pass my canvas stream from peer.call() without getUserMedia.Please help needed. Is that possible? @kidandcat @Sreekanthp74

can you share your solution?

**Comment by gushenjie** [comment]
> I fixed it. Thanks.
i have the exact same problem, what was your fixed solution?can you share your solution?

**Comment by gushenjie** [comment]
> @RamyaAshika i have the exact same problem, what was your fixed solution?

i have the exact same problem, what was your fixed solution?can you share your solution?

**Comment by meenal552** [comment]
> I am trying to capture html5 canvas using captureStream API which has drawings on it and play it using html5 video tag. The problem I am facing this when I capture the stream and play it within video tag It plays exactly same. But when I send that stream to another peer (webRTC Streaming) and play it there.
> 
> It gets played with the black background. i.e. video is not transparent anymore.
> 
> So this is the problem I'm facing so this is the solution for this? @Sreekanthp74

Did you find the solution?
