### ISSUE TITLE
InvalidStateError: RTCPeerConnection is gone (did you enter Offline mode?)

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#465]
Why this keeps on coming when I'm trying to connect to peers and one more thing I'm getting is 
ICE failed, add a TURN server and see about:webrtc for more details often can I know why these are things are happening?

**Comment by RamyaAshika** [comment]
Okay Let me see this,Actually I'm new to this. I will let you know once its done. @kidandcat

**Comment by RamyaAshika** [comment]
I have gone through this but how to add these servers. I mean how to do add this relay server or TURN server? Whether these are open source?@kidandcat

**Comment by kidandcat** [comment]
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
