### ISSUE TITLE
mediastream return black screen in safari

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#472]
Hello all,
        I have tried to connect with on peer to another peer. getusermedia works on one peer and I'm sharing the stream using MediaStream API. 
//Making call
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                    navigator.mediaDevices.getUserMedia({
                        audio: false
                        , video: true
                    }).then(function (mediaStream) {                      
                        conn = peer.call(destId, mediaStream);                  
                        myvideoplay.srcObject = mediaStream;
                        myvideoplay.addEventListener('loadeddata', function () {
                            myvideoplay.play(); // start playing
                            update(); //Start rendering
                        });
                    }, function (err) {             
                        alert(err);
                    });
                }

//Receiving call
  peer.on('call', function (call) {
                if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                    navigator.mediaDevices.getUserMedia({
                        audio: false
                        , video: true
                    }).then(function (mediaStream) {
                        call.answer(mediaStream);
                        call.on('stream', function (mediaStream) {                        
                            myvideo1.srcObject = mediaStream;
                            myvideo1.addEventListener('loadeddata', function () {
                                myvideo1.play(); // start playing
                                update(); //Start rendering
                            });
                        });
                    }, function () {
                        alert("Error! Make sure to click allow when asked for permission by the browser");
                    });
                }
                else {
                    console.log('browser wont support')
                }
            });

but its returning as a black screen in ios. Help needed.

**Comment by RamyaAshika** [comment]
Fixed it.

**Comment by TryHarderOfGit** [comment]
> 
> 
> Fixed it.

Hi

How did you solve this problem? If I open two instances locally I don't have any problems, but when the instances are from different networks the video appears black.
