### ISSUE TITLE
Multiple race conditions cause data transmission failure or connection truncation

### ISSUE THREAD

**Issue by anadon** [peers/peerjs#474]
A partner and I were working with peerjs in order to add collaborative functionality to draw.io.  In the process, we found that a connection was cut short while establishing if one of our loops just operated without any slowdown, and a connection would fail if the slowdown was in the time frame of connecting.  I know this sounds vague, but those are the best I can come up with to describe these bizarre race conditions.

To replicate, pull and build the following:
```
git clone https://github.com/MTU-CS5441/drawio
cd drawio
git checkout TestingPeer
cd etc/build
ant all
```

From here, start and connect multiple clients by opening a browser of your choice, and opening `drawio/src/main/webapp/index.html` 3 or more times.  Under the peer menu, with the top item give each instance a unique name.  Under the peer menu with the bottom item enter the unique ID of every other instance.  This is the base testing setup.  

In `drawio/src/main/js/mxgraph/Dialog.js` in the `EditPeerIDsDialog` function lines 1064-1093 the anonymous synchronization function is defined.  There is an alert on line 1081.  Without this alert, or disabling alerts data does not make it to all clients, usually just the last one.  If an alert is added inside the connection logic, it similarly breaks no matter how fast it is dismissed.

This means there is a race condition for connecting and sending data to peers to quickly, and too slowly.

**Comment by kidandcat** [comment]
@anadon do you have any news on this?

**Comment by anadon** [comment]
No, I've had to leave this for other projects.  Behavior should still be replicable based on the included instructions.

**Comment by afrokick** [comment]
should works in the latest version from master
