### ISSUE TITLE
Unable to connect to a peer in Safari on macOS

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#478]
Whenever I am trying to connect to a peer in Safari with specifying an option of { reliable: true } I get an error:
`TypeError: Object is not a constructor (evaluating 'new Reliable(this._dc, util.debug)')`
![image](https://user-images.githubusercontent.com/669701/51644302-630f6280-1f78-11e9-8b1a-009832512198.png)

Is there a way I can still use reliable data channel in Safari?

**Comment by pReya** [comment]
I can confirm this bug. Seems to be because of different APIs on Chrome/Firefox vs. Safari. Other WebRTC libraries seem to have had the same problems:
https://github.com/feross/simple-peer/issues/190

To fix this, a couple of methods need to be changed from Callback syntax to Promise syntax. Should not be too much work. I'll see if I can work on this problem.

**Comment by tombertrand** [comment]
The error seems to come from the way Reliable is exported.

source -> `import { Reliable } from "reliable";`
babel -> `var Reliable = require('reliable');`

Changing the compiled code to the following works...
`this._reliable = new Reliable.Reliable(this._dc, util.debug);`

**Comment by kidandcat** [comment]
Wow, I haven't access to that repo. @tombertrand what do you recommend? the fix to the import or just remove `reliable: true`?

If it's better to have it, I'll clone the repo and do the update.

**Comment by pReya** [comment]
Tried tweeting and mailing to @michelle if she can merge this PR. Just hope she'll respond.

**Comment by tombertrand** [comment]
I've experimented with Safari, fixing JS errors caused by `Reliable` lib and `negotiator.ts`. There was no more errors but the message wouldn't reach the connections. I ended up doing reliable connections for the browsers that supports it, unreliable for unsupported browsers.

```
import Peer from 'peerjs';
import Util from 'peerjs/lib/util';

// Host
const peer = new Peer(HOST_PEER_ID, { secure: true, debug: 3 });

// Guests
const guestConnection = guestPeer.connect(HOST_PEER_ID, {
  reliable: Util.supports.reliable, // true / false depending if the browser supports reliable connection
});
```

**Comment by pReya** [comment]
I've reached @michelle and she merged the PR. Also a good workaround @tombertrand. But it's still sad to see reliable connections not working on Safari :(

**Comment by kidandcat** [comment]
It should just work then, because the package.json uses the latest master version from the repo.

**Comment by maxpavlov** [comment]
Ok, so as 'reliable' part got fixed, I am still seeing this when I attempt to connect to peer from Safari 12:
![image](https://user-images.githubusercontent.com/669701/54667771-e15e3000-4af5-11e9-8191-22f90d6677f6.png)

Can anyone suggest what is wrong here? Thanks.

**Comment by maxpavlov** [comment]
I was able to trace the problem down to this point. Once new t.RTCPeerConnection is called with an array of iceServers, it fails internally in the native code. 
<img width="782" alt="Screen Shot 2019-03-21 at 8 30 46 AM" src="https://user-images.githubusercontent.com/669701/54736470-e08bd380-4bb3-11e9-999a-85f2dabdd3e3.png">

**Comment by maxpavlov** [comment]
The problem turned out to be exactly as the error implies. I was passing in the array of url instead of urls and the array of actual strings containing the urls for stun servers. My mistake after all.

**Comment by themindstorm** [comment]
Is this related to #574 in any way? I tried using safari. If Safari is the host, it fail silently. If I try to connect another browser (ex, Chrome) to Safari, I get the error
```
Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary
```

It seems to be a problem with `i.createOffer(function(e) {` in `peer.min.js`
