### ISSUE TITLE
Version 0.3.19 Publishing issue?

### ISSUE THREAD

**Issue by ramkalari** [peers/peerjs#481]
Comparing the two versions on npm, it looks like the lib folder in the latest version has typescript files which is causing module not found errors. Is this a publishing issue?
https://registry.npmjs.org/peerjs/-/peerjs-0.3.19.tgz
https://registry.npmjs.org/peerjs/-/peerjs-0.3.18.tgz

**Comment by kidandcat** [comment]
Yes, it should point now to dist folder, not lib. I've updated "main" entry in package.json. That should fix it.
