### ISSUE TITLE
Cannot connect to peer on Safari 12 (osx/ios)

### ISSUE THREAD

**Issue by akotynski** [peers/peerjs#485]
Peerjs uses a deprecated api based on callbacks - [example](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createAnswer#Deprecated_parameters).
Safari 12 only supports promise based APIs, so the library probably should be migrated to it.

**Comment by Pacific112** [comment]
True, I just came across the same problem. Very hard to fix without forking whole library.

**Comment by kidandcat** [comment]
Changes are in master branch, could you test in Safari?

**Comment by alfredoizjr** [comment]
Sorry, it is fixed? because I still have the same issue, I use the basic example you have here, and on my client receiver, open with safari 12 say can't connect with the server, I am using Ipad pro and  last update

**Comment by alfredoizjr** [comment]
The version I got is peerjs@0.3.22

**Comment by kidandcat** [comment]
It is fixed in master branch until we do some tests, then a new version
will be published

**Comment by alfredoizjr** [comment]
Ok, thanks for your answer I will waiting for it.

**Comment by akotynski** [comment]
generally it's working but I found one more usage of deprecated api

**Comment by akotynski** [comment]
now everything works fine on safari

**Comment by kidandcat** [comment]
v0.3.23 is out with these changes

**Comment by alfredoizjr** [comment]
sorry I am using iPad pro with safari 12 I update to the new version "peerjs": "^0.3.23","peer": "^0.2.10", but I can't connect whet I use safari 12

**Comment by kidandcat** [comment]
@alfredoizjr can you post console log? also, with "peer": "^0.2.10", you mean you have your own PeerServer, right?

**Comment by alfredoizjr** [comment]
Yes, I am I try to implement the basic example video and audio with receiver and sender, the only error I got is Lost connection to the server that is only on safari is happening can be the stun server?
