### ISSUE TITLE
I can't reach the documents and the site?

### ISSUE THREAD

**Issue by tolgahanuzun** [peers/peerjs#487]
I get an error. I wonder what's wrong. How can I reach?

<img width="1052" alt="screen shot 2019-02-22 at 09 20 05" src="https://user-images.githubusercontent.com/10615529/53223945-0f318f80-3684-11e9-95ab-d0fa85f7733c.png">

**Comment by RamyaAshika** [comment]
Ya for me too @kidandcat

**Comment by kidandcat** [comment]
Sorry, didn't remember I changed my credit card number, it's online now

**Comment by tolgahanuzun** [comment]
No problem. Thank you. :)
