### ISSUE TITLE
standard belongs in devDependendies

### ISSUE THREAD

**Issue by gardner** [peers/peerjs#489]
Hi @kidandcat 

Thanks for cleaning up the codebase and adding standard. I ran into an issue while using https://github.com/facebook/create-react-app with peerjs.

react-scripts complains about a version of eslint being installed that is incompatible with react-scripts.

**Steps to reproduce:**
```
npm i -g yarn && \
npx create-react-app peerjs-test && \
cd peerjs-test && \
yarn add -D eslint-plugin-jsx-a11y eslint-plugin-jest eslint-plugin-react && \
yarn add peerjs && \
CI=true yarn test
```

Please note installing peerjs before the eslint dependencies is a valid workaround for this issue.

This is the commit that standard was introduced into the dependencies section of the peerjs package.json: 
https://github.com/peers/peerjs/commit/a8f62112bf84a671e31b5987a0778ca562bfe45b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R54

To fix this issue, please move standardjs to the `devDependencies` section in package.json, as according to the standardjs [docs](https://standardjs.com/), and republish the npm module. 

Thank you,
  Gardner

**Comment by kidandcat** [comment]
Commited and published: v0.3.24

Thanks for the info @gardner !
