### ISSUE TITLE
Dropping calls immediately

### ISSUE THREAD

**Issue by pshah123** [peers/peerjs#491]
I'm using the latest stable JS from the website.

The issue occurs on certain public networks. In this case, the connection is going through the TURN server presumably (I'm 100% sure the TURN server is in use because I'm able to call w/ my Android smartphone which is on LTE), but the call is IMMEDIATELY disconnected. The stream is delivered and an answer is made on both ends, but the call drops almost instantly.

![image](https://user-images.githubusercontent.com/6960204/53989292-a5899a80-40f3-11e9-9f46-e290fd159ab3.png)

I'm behind a normal NAT and the peer is also behind normal NAT.

This issue occurs with that peer specifically with every other configuration, so I at first thought it was a wireless issue. However, it is able to communicate with other WebRTC solutions, even my raw/simple webrtc trial with a turn server. It's just when using PeerJS that the connection is immediately dropped.

I tried implementing the changes discussed in #347 regarding sdpMid but this made no improvement.

I'm a bit lost and there doesn't seem to be any other logs other than the ones pictured above, can someone point me in the right direction?

**Comment by pshah123** [comment]
I'm not experiencing different behaviour. Now, the peers stay connected, and a MediaStream is delivered. However, the stream contains no real video or audio. It's just a black screen with no sound.

It works with nearly every other client.

**Comment by kidandcat** [comment]
Could you post here whatever you find on chrome://webrtc-internals/ when that happens?

**Comment by pshah123** [comment]
Yup, happened again today. The call is long so the dump will probably begin from when the connection was fine, near the end the peer switched wireless networks and refreshed and the call dropped immediately.

[webrtc_internals_dump.txt](https://github.com/peers/peerjs/files/2958892/webrtc_internals_dump.txt)

**Comment by pshah123** [comment]
Here's another dump of the same thing, this time with some console errors as well:

![image](https://user-images.githubusercontent.com/6960204/54238376-aef97500-44ee-11e9-8dd9-542fae8812c2.png)


Reds in WebRTC Internals:

![image](https://user-images.githubusercontent.com/6960204/54238370-a9039400-44ee-11e9-9cbf-68b93c854c57.png)

Full dump attached

[webrtc_internals_dump (1).txt](https://github.com/peers/peerjs/files/2958906/webrtc_internals_dump.1.txt)

**Comment by afrokick** [comment]
@pshah123 Could use please try a version from master branch?

**Comment by RamyaAshika** [comment]
Can you please release the latest version? @afrokick

**Comment by kidandcat** [comment]
We will be releasing it very soon, but we want to do things the right way. This will be a breaking release, so we need to go slowly and test everything.

Anyway, you can easily use github as a source with npm. You should target a commit to have stability, for example, to install using latest master branch:

`npm install peers/peerjs#09d556f`

**Comment by RamyaAshika** [comment]
Ya that's good to hear but so far I'm using your cdn version   <script src="https://cdnjs.cloudflare.com/ajax/libs/peerjs/0.3.18/peer.min.js"></script> until that can I use your peer.min.js from your master branch? Whether it will work? @kidandcat

**Comment by afrokick** [comment]
@RamyaAshika Yeap, you can use raw link https://raw.githubusercontent.com/peers/peerjs/master/dist/peerjs.min.js

But please, keep in mind, that it isn't a release version, so, it maybe unstable

**Comment by RamyaAshika** [comment]
Sure Thank you @afrokick

**Comment by 0crypto0** [comment]
I'm having the same issue now when going through turn server.
