### ISSUE TITLE
How come peerjs is a dependency of peerjs itself?

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#493]
In current packages.json we see the following entry in dependencies:
https://github.com/peers/peerjs/blob/36a3c7268ae5efff2990a6132e872c40cb9f6b14/package.json#L52
```
"dependencies": {
    "@types/node": "^10.12.0",
    "eventemitter3": "^0.1.6",
    "express": "^4.16.3",
    "js-binarypack": "0.0.9",
    "opencollective": "^1.0.3",
    "opencollective-postinstall": "^2.0.0",
    **"peerjs": "^0.3.20",**
```

How come we have a previous version of peerjs as a dependencty of a current one? Thanks in advance for explaining.

**Comment by afrokick** [comment]
#496 it was removed. Thanks @maxpavlov

**Comment by maxpavlov** [comment]
Any time.
