### ISSUE TITLE
new Peer only works if using window.Peer in angular application

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#494]
Hi.

I am importing peerjs npm package into my client-side application vie plugins capability in webpack:

`
...
let plugins = [
	new webpack.ProvidePlugin({
		$: "jquery",
		jQuery: "jquery",
		Peer: "peerjs"
...
`

Until recently, I was able to just call `var peer = new Peer(idService.generateId(), config.peerConfig);` and the Peer object would be instantiated for me. Now with a recent update, only calling a window.Peer as a constructor results in expected behavior, while simply trying to call `new Peer(...` will result in _Peer is not a constructor_ error. 

Did I miss some change announcement or the way I import it is wrong for .ts-based peerjs implementation?

**Comment by kidandcat** [comment]
I think you should just import Peer from "peerjs"

**Comment by maxpavlov** [comment]
Import Peer from "peerjs" is "not pretty" and some prefer using webpack ability to import plugins as it makes the code more syntactically correct.

Regardless of the fact, if I "import Peer from "peerjs" I still get the "Peer is not a constructor" if I use it without .window. Perhaps someone who is using Peerjs in a similar setup can comment. Probably some angular thing.

**Comment by kidandcat** [comment]
Which version are you using?

**Comment by maxpavlov** [comment]
@kidandcat  I am using the 0.3.24 and I've seen people confirm it works for them. Let's leave this ticket open, I will either create and reference a simple boilerplate app that showcases the problem or someone who experiences the similar might chip-in.

**Comment by kidandcat** [comment]
Are you doing this? 

> For importing the default export of an ES2015 module, you have to specify the default property of module.

**Comment by maxpavlov** [comment]
@kidandcat you have a terrific intuition, man 👍 

```
new webpack.ProvidePlugin({
		$: "jquery",
		jQuery: "jquery",
		Peer: ['peerjs','default']
	}),
```

Importing with default property specified has fixed the problem of having to use window.Peer. Thank you.
