### ISSUE TITLE
Multiple streams per MediaConnection

### ISSUE THREAD

**Issue by afrokick** [peers/peerjs#495]
Hi. I found a PR #132 related to my issue.

I want to send video+audio+screen.

What do you advice?

**Comment by afrokick** [comment]
Ok, I found a trick https://blog.mozilla.org/webrtc/warm-up-with-replacetrack/

I have one stream with 3 'empty' tracks - audio, video and screen.

Next, I call method 'call' and then have senders:
const [audioSender, videoSender, screenSender]= call.peerConnection.getSenders();

just replace track via audio.replaceTrack(null|audioTrack) to mute/unmute

**Comment by shivarajnaidu** [comment]
Any sample code snippet with peerjs will be helpful for newbie webrtc people :)

Thanks in advance !

**Comment by kidandcat** [comment]
New news, I'll be releasing a new version of PeerJS next week, completely rewritten, using a much simpler concept, and it will not need a PeerServer. So wait few days.

The new concept is based on rooms, a Room is the only thing that exists, so if you want to call someone, just go into a random ID room that both peers share. If what you want is multiple connections, just enter into a room with more people, that simple.

Here is an early test: https://dist-9yeo4sucs.now.sh/

The getUserMedia is inside the librayr, but I'll take it out probably.

**Comment by shivarajnaidu** [comment]
great news .. ! awaiting for new version . Where can i see the updates related to new release

**Comment by kidandcat** [comment]
The branch is ready https://github.com/peers/peerjs/tree/v2.0.0
You can join to a Telegram group if you want to discuss or ask for anything related to PeerJS: [Telegram](tg://join?invite=ENhPuhTvhm8WlIxTjQf7Og)

**Comment by PaperPlaneSoftware** [comment]
Sorry to comment on a closed issue but I'm trying to do exactly the same thing but I can't make it work. I can add multiple tracks to a stream and the receiving end get the stream with the same number of tracks but I can't get the streams out of those tracks to do anything with.

I thought I'd try to listen for track events on the receiving side and they are triggered but the stream that is attached to the track event is only ever the stream from the first track! I'm at a complete loss as to how to do this. Is it even possible to have multiple streams over one connection? Should I just make multiple connections, one for each stream?

@afrokick how did you solve this in the end?

**Comment by muhammedsirajudeen** [comment]
@ohuu Iam trying to implement the same thing. I have attached the stream but the only stream thats getting attached is the stream from the fist event. Do you have any follow up on this?
