### ISSUE TITLE
Docs: API Key is not being used anymore – correct?

### ISSUE THREAD

**Issue by pReya** [peers/peerjs#510]
I noticed there are still many locations in the API docs and markdown files, where API Key is referenced. Also, the link to obtain an API key (https://peerjs.com/peerserver) is dead. Since I've been using the library for a couple of months now, I assume the API Key is not being used anymore, is this correct? This is a permanent change, and not just a temporary thing, right?

If that's the case, I'd be happy to contribute a PR for [0.4.0](https://github.com/peers/peerjs/milestone/1) with updates to the docs reflecting the change.

BTW: Huge thanks @afrokick for picking up the work here again!

**Comment by afrokick** [comment]
@pReya Yes, you don't need to obtain api key. Just use default 'peerjs'.

You can use api key for your own server to check an access to your application.

**Comment by pReya** [comment]
Thanks, I'll put together a PR with the necessary changes.
