### ISSUE TITLE
API Key is not being used on client side

### ISSUE THREAD

**Issue by rousan** [peers/peerjs#512]
I started peerjs server with APP Key to `something` with `--key something`, but when I try to create new `Peer` instance on the client side with that APP key like below:

```javascript
const peer = new Peer({
  host: 'localhost',
  port: 9000,
  path: '/',
  secure: false,
  reliable: true,
  key: 'something',
});
```
It still uses default APP key `peerjs` instead of provided key `something`.

Can you help me where I am doing wrong?

**Comment by afrokick** [comment]
Could you please attach WebSocket's url from Network tab in DevTools?

**Comment by kidandcat** [comment]
We haven't yet published the new version to NPM. So if you are installing by npm install, you have an old version.

**Comment by rousan** [comment]
I am using `peerjs` library from cdn like below:

```html
 <script src="https://cdn.jsdelivr.net/npm/peerjs@0.3.20/dist/peer.min.js"></script>
```

but the `open` event is not being triggered by the `peer` instance.

```javascript
const peer = new Peer({
  host: 'localhost',
  port: 9000,
  path: '/',
  secure: false,
  reliable: true,
  key: 'abc',
});

peer.on('open', (id) => {
  console.log(`My peer ID is: ${id}`);
});

peer.on('connection', (conn) => {
  console.log(conn);
  conn.on('data', (data) => {
    console.log('Received', data);
  });
});
```

I started server like following:

```bash
node ./src/index.js --host 0.0.0.0 --port 9000 --key abc  --path 
```

<img width="1440" alt="Screenshot 2019-04-04 at 12 09 07 PM" src="https://user-images.githubusercontent.com/12519292/55534715-ba495600-56d2-11e9-97f0-af6b5382e2f8.png">
<img width="1440" alt="Screenshot 2019-04-04 at 12 09 05 PM" src="https://user-images.githubusercontent.com/12519292/55534716-ba495600-56d2-11e9-9f6e-42349245804b.png">

**Comment by kidandcat** [comment]
That's an old version. 0.3.24 is the latest released one.

Anyway I recommend you to use master branch, something like:

package.json
```
npm install peers/peerjs#master
```

We are going to release a mayor version with a lot of improvements (thanks to @afrokick :) ), so you should start using it now, so you will not need to change your code in a week or two.

**Comment by rousan** [comment]
Thanks, it is working from `master` branch, but if I try to inject it through script tag, then I need to access it as:

```javascript
const peer = new peerjs.Peer({/* config */});
```

**Comment by afrokick** [comment]
> I think you should use `UMD` as build format.

Thanks, I added Peer to global. Just update your version from master.
