### ISSUE TITLE
Cannot read property 'metadata' of undefined on latest master branch

### ISSUE THREAD

**Issue by rousan** [peers/peerjs#515]
I tried to connect with other peer by `connect` method as follows:

```javascript
const conn = peer.connect(elemInpTo.value);
```

It throws
```text
Uncaught TypeError: Cannot read property 'metadata' of undefined
```

But if I try to connect with `metadata`, it works, it means you have to supply metadata option in `connect` method as follows:

```javascript
  const conn = peer.connect(elemInpTo.value, { metadata: 'anything' });
```

Library version: Latest master branch.

<img width="838" alt="Screenshot 2019-04-04 at 1 36 47 PM" src="https://user-images.githubusercontent.com/12519292/55539765-16b27280-56df-11e9-9f7a-78b4532203e0.png">

**Comment by afrokick** [comment]
@rousan please, check it again. should be fixed
