### ISSUE TITLE
Data is not being serialized with BinaryPack on latest master branch

### ISSUE THREAD

**Issue by rousan** [peers/peerjs#516]
The `dataConnection.send(/*any data*/)` does not serialize data as expected.

The sample code:

```javascript
conn.send({ x: 111 });
```

On the receiver, it gets a stringified version of data instead of object `{ x: 111 })`.

<img width="509" alt="Screenshot 2019-04-04 at 1 54 04 PM" src="https://user-images.githubusercontent.com/12519292/55540706-2337ca80-56e1-11e9-8fed-f56071ae65e6.png">

Library Version: latest master branch

**Comment by afrokick** [comment]
@rousan Could you please try a fix from #517 ?

**Comment by afrokick** [comment]
@rousan i had merge a fix in master, please, check it

**Comment by rousan** [comment]
@afrokick, thanks, it is working.
