### ISSUE TITLE
ICE Connection state disconnected 

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#518]
Hi,
I have shared my video streams. I display my webcam and my partner. Everything works fine until the 30 seconds. Then, the connection is lost. In chrome console gives me the following:

- IceConnectionState is disconnected, closing connection to (id number).
- Cleaning up peer connection to (id number).

Always occurs at 25-30 seconds. Can you think of what could be the fault? @afrokick @kidandcat

**Comment by afrokick** [comment]
Which version of peerjs?

**Comment by RamyaAshika** [comment]
<script src="https://cdnjs.cloudflare.com/ajax/libs/peerjs/0.3.18/peer.min.js"></script>  @afrokick

**Comment by afrokick** [comment]
I think the issue in transport level, not in library.

>disconnected: Checks to ensure that components are still connected failed for at least one component of the RTCPeerConnection. This is a less stringent test than "failed" and may trigger intermittently and resolve just as spontaneously on less reliable networks, or during temporary disconnections. When the problem resolves, the connection may return to the "connected" state.

Maybe you have problems with routers? could you please check examples like jitsi chat and check webrtc-internals?

**Comment by RamyaAshika** [comment]
Okay, but when can I expect the latest stable version of peerjs @kidandcat  @afrokick  or else what I need to do to have a stable connection atleast for 30-40mins?? I'm in urge.

Thanks

**Comment by afrokick** [comment]
@RamyaAshika could you please check the latest release?

**Comment by jrowny** [comment]
I think the issue is that the negotiator closes the connection when it disconnects, but it shouldn't because it's recoverable. I'm going to put together a PR to stop this behaviour.
