### ISSUE TITLE
Data channel in Edge

### ISSUE THREAD

**Issue by korneliuscode** [peers/peerjs#519]
hi, is there a workaround to use this cross browser, even in Edge, which does not support the data channel, yet?

**Comment by kidandcat** [comment]
The only workaround is to use a server and http api or websockets, but you must implement it by yourself.

**Comment by RamyaAshika** [comment]
Hey Hi @kidandcat When can I expect the latest version of peerjs?

**Comment by afrokick** [comment]
@RamyaAshika we just released it

**Comment by RamyaAshika** [comment]
Through cdn?? Still https://peerjs.com/ 0.3.20 ?? @afrokick

**Comment by kidandcat** [comment]
We don't officially support any CDN, but you have lots of options, for example unpkg.com:

unpkg.com/:package@:version/:file

unpkg.com/peerjs@1.0.0/dist/peerjs.min.js

**Comment by RamyaAshika** [comment]
Okay, but I have tried this link unpkg.com/peerjs@1.0.0/dist/peerjs.min.js The video is not at all connected on two peers @kidandcat @afrokick

**Comment by afrokick** [comment]
Open a new issue please.
