### ISSUE TITLE
Error trying code from Getting started guide

### ISSUE THREAD

**Issue by majid4466** [peers/peerjs#52]
Trying the code in Getting started guide, I get this error in Google Chrome console:

Failed to load resource: the server responded with a status of 401 (Unauthorized)

Opening the link in a new tab, this is the json sent with header 401:

{"code":"MethodNotAllowedError","message":"GET is not allowed"}

Am I missing a required step?

**Comment by minusplusminus** [comment]
I'm currently testing the connection with the peer.js server and simulating bad connections, reconnecting multiple times per minute to see what happens. Sometimes I get the same error.

**Comment by shah-smit** [comment]
I did get this error earlier this morning, however, the issue was to do with http(s) request.
