### ISSUE TITLE
Not working from chrome to safari browser.

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#522]
It worked early but now with the master branch code it's not working

**Comment by pReya** [comment]
Could you be a little more specific? What exactly isn't working? Any errors in the console?

**Comment by RamyaAshika** [comment]
Uncaught TypeError: Cannot read property 'addIceCandidate' of undefined @pReya @afrokick @kidandcat

**Comment by afrokick** [comment]
I think the issue relates to unified-plan, because only safari 12.1+ will support it.

@RamyaAshika could you please check it with plan-b?

**Comment by RamyaAshika** [comment]
No, I'm using latest IOS version only and it worked early within the same browser @afrokick

**Comment by afrokick** [comment]
Which environment do you use?

**Comment by RamyaAshika** [comment]
iPhone 6 and Safari browser. @afrokick

**Comment by themindstorm** [comment]
I'm having a similar problem. PeerJS does not work in Safari: #574

**Comment by afrokick** [comment]
I'll close issue. If the problem still exists - reopen please.
