### ISSUE TITLE
sdpTransform does not apply to makeAnswer SDP

### ISSUE THREAD

**Issue by Lovinity** [peers/peerjs#523]
The new sdpTransform option in Peer.js transforms the SDP offer as expected. However, the transformations do not apply to the answer side. As a result, a change in bandwidth, for example, does not get negotiated.

For instance, if I sdpTransform to add a "b=AS:128" line to increase bandwidth to 128kbps, the line correctly gets added to the offer SDP. However, on the receiver, although it correctly receives this in the remote SDP, it does not actually set it in its localDescription nor in its answering SDP. As a result, the bandwidth negotiation gets lost, and the application defaults to using Chrome's default bandwidth (about 30 kbps).

The above was also experienced for a=fmtp: lines passed to Opus; these lines correctly get transmitted in the offer, but they do not get registered on the receiver nor in the answer, effectively voiding them.

To test that this was actually what was happening, I modified negotiator.ts in Peer.js and generated my own build. In the ts, I required a separate custom javascript file that had functions for transforming the SDP. I then hard-coded SDP transformations both in the _makeOffer and in the _makeAnswer functions of negotiator. The transformations were successful, and webrtc successfully increased allotted bandwidth for the call.

Side note: The application I use does not pass a stream in the answer() call; it only makes one-way audio calls for remote broadcasting over a radio station.

**Comment by kidandcat** [comment]
PRs are always welcome :)

**Comment by Lovinity** [comment]
The above is not something I would ideally PR because it's completely hard-coded and not meant for use in the actual peer.js library; it was only used so I can experiment to see if bitrate really wasn't getting negotiated.

**Comment by afrokick** [comment]
Fixed in #524 Could you please check it?

**Comment by Lovinity** [comment]
Thank you, I will not be able to check this for several days as Peer.js is used in a business application, which I do not have office hours again until the end of the week. But I will let you know then.

**Comment by afrokick** [comment]
@Lovinity did you try a fix?

**Comment by Lovinity** [comment]
@afrokick unfortunately not. Due to the timely needs of my workplace, we had to switch to the SkywayJS library (they use a modified older version of PeerJS with better STUN and TURN servers).

However, just eye balling the code, my assumption is that it would not work. sdpTransform is passed through the call method on the sender. So has the code been modified so that this.connection gets sdpTransform from the answer method on the receiver? The answering device would need to pass an sdpTransform option of its own in the answer method in order for this to work, since that device never uses call for that specific connection.
