### ISSUE TITLE
How do check if my call video was answered !

### ISSUE THREAD

**Issue by danbeo95** [peers/peerjs#525]
I have implement peer js to make a app with video call,everthing work fine ! But i can not found event when  my call video was answered.Anyone has solution ? Thanks so much !
<img width="328" alt="Ảnh chụp Màn hình 2019-04-20 lúc 15 39 46" src="https://user-images.githubusercontent.com/21057627/56454940-9b112080-6382-11e9-8251-9ed922c64b0f.png">
<img width="325" alt="Ảnh chụp Màn hình 2019-04-20 lúc 15 39 54" src="https://user-images.githubusercontent.com/21057627/56454944-a401f200-6382-11e9-9429-14db4645e6f9.png">
i want if USER WAS CALLED click "Answer" button ,USER CALL can listen this event !

**Comment by afrokick** [comment]
You need to listen `stream` event of `MediaConnection`. https://peerjs.com/docs.html#mediaconnection-on-stream

**Comment by istiti** [comment]
@afrokick it seems not working to me too... I can listen 'stream' only on call-reciever.html  while in caller.html this 'stream' event never fired even If I respond from call-reciever.html with call.answer(strm)
donno if it's symmetric nat question

**Comment by istiti** [comment]
FYI im on normal nat (not symmetric)

**Comment by istiti** [comment]
After few investigation i find problem. maybe it is working as intended but we cant make a call without sending null as stream...
[This ](https://github.com/peers/peerjs/issues/158) could be related.

I wonder why this is working like that ? because `call-reciever.html` has `answer(withCorrectStream)`  and caller don't recieve event 'stream' 

call-reciever.html recieve call but with (non realy existing stream)
```
// caller.html
<video hidden autoplay></video>
var video = document.querySelector('video');

var call = peer.call('responder', video.captureStream()); // this stream is fake one
call.on('stream', (stream) {...}); // this event NEVER fire???
```

on other side 
```
// call-reciever.html
<video autoplay width=50></video>
var video = document.querySelector('video');

async function gdmAndAcceptCall() {
    await navigator.mediaDevices.getDisplayMedia({video: true})
        .then((strm) => {video.srcObject = strm}).catch(() => {...});
    
    call.answer(video.captureStream()); // this is real existing correct stream

    call.on('stream', (stream) {...}); // this event fire
}
```

IMHO I expect here `'stream'`  event fired in `caller.html` and not in `call-reciever.html`

cc @michelle

**Comment by afrokick** [comment]
@elvisbegovic Let me know if you have a problem with 'stream' event now, i reopen this issue

**Comment by naonvl** [comment]
which function to do something like waiting for answer as first image above?
