### ISSUE TITLE
Connection is not at all working properly within two peer

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#526]
I have tested from the latest code. The connection is often not working properly. Sometimes the connection is not initiating on another peer @afrokick  @kidandcat

**Comment by afrokick** [comment]
Could you please provide more description about the problem? At least logs...

**Comment by RamyaAshika** [comment]
Sure I will try to get logs and I will send you @afrokick

**Comment by RamyaAshika** [comment]
peer.js:1589 PeerJS:  Socket open
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Set remoteDescription: OFFER for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Created answer.
peer.js:1589 PeerJS:  Set localDescription: answer for: vpdb9dsffyr00000
2peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
2peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Received remote stream
peer.js:1589 PeerJS:  Receiving stream MediaStream
peer.js:1589 PeerJS:  Set remoteDescription: OFFER for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Created answer.
peer.js:1589 PeerJS:  Set localDescription: answer for: vpdb9dsffyr00000
5peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Received data channel
peer.js:1589 PeerJS:  Data channel connection success
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Created offer.
peer.js:1589 PeerJS:  DataChannel closed for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Set localDescription: offer for: vpdb9dsffyr00000
2peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
7peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Set remoteDescription: ANSWER for: vpdb9dsffyr00000
2peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  iceConnectionState is disconnected, closing connections to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Set remoteDescription: OFFER for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Created answer.
peer.js:1589 PeerJS:  Set localDescription: answer for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Received remote stream
peer.js:1589 PeerJS:  Receiving stream MediaStream
2peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Set remoteDescription: OFFER for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Created answer.
peer.js:1589 PeerJS:  Set localDescription: answer for: vpdb9dsffyr00000
2peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Received data channel
peer.js:1589 PeerJS:  Data channel connection success
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Created offer.
peer.js:1589 PeerJS:  DataChannel closed for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Set localDescription: offer for: vpdb9dsffyr00000
5peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
2Support.js:171 error
peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Set remoteDescription: ANSWER for: vpdb9dsffyr00000
2peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Creating RTCPeerConnection.
peer.js:1589 PeerJS:  Listening for ICE candidates.
peer.js:1589 PeerJS:  Listening for data channel
peer.js:1589 PeerJS:  Listening for remote stream
peer.js:1589 PeerJS:  Created offer.
peer.js:1589 PeerJS:  Set localDescription: offer for: vpdb9dsffyr00000
6peer.js:1589 PeerJS:  Received ICE candidates for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Setting remote description RTCSessionDescription
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Set remoteDescription: ANSWER for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  Data channel connection success
peer.js:1589 PeerJS:  Added ICE candidate for: vpdb9dsffyr00000
peer.js:1589 PeerJS:  iceConnectionState is disconnected, closing connections to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000
peer.js:1589 PeerJS:  iceConnectionState is disconnected, closing connections to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000
peer.js:1589 PeerJS:  iceConnectionState is disconnected, closing connections to vpdb9dsffyr00000
peer.js:1589 PeerJS:  Cleaning up PeerConnection to vpdb9dsffyr00000

**Comment by RamyaAshika** [comment]
This is the logs I have found @afrokick @kidandcat

**Comment by RamyaAshika** [comment]
PeerJS:  Creating RTCPeerConnection.
peer.js:689 PeerJS:  Listening for ICE candidates.
peer.js:689 PeerJS:  Listening for data channel
peer.js:689 PeerJS:  Listening for remote stream
peer.js:689 PeerJS:  add connection data:dc_eioexvrcb6j
       to peerId:m
peer.js:689 PeerJS:  Creating RTCPeerConnection.
peer.js:689 PeerJS:  Listening for ICE candidates.
peer.js:689 PeerJS:  Listening for data channel
peer.js:689 PeerJS:  Listening for remote stream
peer.js:689 PeerJS:  add tracks from stream UHcZhDX9XYpDb0J4pWnPDYiAFhPYJfzSjIJ2 to peer connection
peer.js:689 PeerJS:  add connection media:mc_dy7han4cqp7
       to peerId:m
2peer.js:689 PeerJS:  Created offer.
peer.js:689 PeerJS:  Set localDescription: RTCSessionDescription for:m
peer.js:689 PeerJS:  Set localDescription: RTCSessionDescription for:m
6peer.js:689 PeerJS:  Received ICE candidates for: m
LinkToConnect.js:261 error
peer.js:689 PeerJS:  Socket open
2peer.js:689 PeerJS:  Received ICE candidates for: m

On opposite side @afrokick @kidandcat

**Comment by PyrozhenkoSerhii** [comment]
Almost the same issue on Heroku. Peerjs works well locally, yet on Heroku peers isn't get connected to each others
![123](https://user-images.githubusercontent.com/34453331/58476430-68b0cb00-8159-11e9-8470-96ae2a2e7d9f.png)

**Comment by jernejpregelj** [comment]
I have same problem. Logs stop at "Received ICE candidates":
<img width="945" alt="Screenshot 2019-06-14 at 18 52 10" src="https://user-images.githubusercontent.com/7147341/59525043-9a55c000-8ed5-11e9-827e-9023d20e0965.png">

**Comment by afrokick** [comment]
@jernejpregelj could please share a demo project to reproduce an issue?

**Comment by mgoulao** [comment]
I have created a simple [Demo](https://mgoulao.github.io/peerjs-test/index.html),  you can check the source code [Here](https://github.com/mgoulao/mgoulao.github.io/blob/master/peerjs-test/index.html).

**Comment by afrokick** [comment]
Thank you. I noticed two cases:
1) RTCIceCandidatePair contains both local and remote iceCandidates with 127.0.0.1
2) RTCIceCandidatePair contains local candidate with 127.0.0.1 and remote with public ip.

The first case should work, because it is localhost communication.

The second case doesn't work for me because of NAT as I understand.

@mgoulao did you try to test communication between two separate devices(pc+mobile or 2 pcs)?

**Comment by mgoulao** [comment]
Yes, I have tested with 2 Pcs and it didn't work, probably because of NAT because with a TURN server they now connect. Not sure if this is was @RamyaAshika problem.
I have updated the example and it seems that the first message sent by the user that "joins" is never received by the other peer, not sure if this is a problem with my implementation.

**Comment by afrokick** [comment]
seems like NAT problem. please use relay server to resolve it.
