### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR when trying to receive in Electron app

### ISSUE THREAD

**Issue by stuartlangridge** [peers/peerjs#527]
In a simple Electron app, when I try to set up a peerjs connection to receive incoming data, it fails.

`var peer = new Peer("mysecretid", {key: 'lwjd5qra8257b9', debug:3});`
throws error
`.../electron-quick-start/peer.min.js:1 WebSocket connection to 'wss://0.peerjs.com/peerjs?key=peerjs&id=mysecret&token=(snip)' failed: Error in connection establishment: net::ERR_SPDY_PROTOCOL_ERROR`

I've verified the same code working fine in a "real" Firefox browser window. I've also tried with `secure: false` as an extra parameter. Is this something that I'm doing wrong?

**Comment by kidandcat** [comment]
Try this?: https://zenguard.zendesk.com/hc/en-us/articles/204423722-Chrome-error-ERR-SPDY-PROTOCOL-ERROR-

**Comment by kidandcat** [comment]
Have you solved it?

**Comment by stuartlangridge** [comment]
I have not, I'm afraid.

**Comment by kidandcat** [comment]
https://err-spdy-protocol-error.com/

This is not related at all with PeerJS, if you find some way we can help you, write us, if not, we can't do anything else.
