### ISSUE TITLE
Failed to construct Peer Object

### ISSUE THREAD

**Issue by chak774** [peers/peerjs#533]
I am trying to create a peer by below code:

import * as Peer from 'peerjs';
this.myPeerId = `aaa${Math.floor((Math.random() * 10) + 1)}`;
this.peer = new Peer(this.myPeerId, {key: 'lwjd5qra8257b9'});

However, I received this error:
peerjs__WEBPACK_IMPORTED_MODULE_2__ is not a constructor

Anyone can help? Thanks!

**Comment by chak774** [comment]
I am using Ionic 3 with TypeScript

**Comment by frankrobert** [comment]
@chak774 try a default import

```ts
import Peer from 'peerjs';
```

**Comment by nhducseuit** [comment]
> I am trying to create a peer by below code:
> 
> import * as Peer from 'peerjs';
> this.myPeerId = `aaa${Math.floor((Math.random() * 10) + 1)}`;
> this.peer = new Peer(this.myPeerId, {key: 'lwjd5qra8257b9'});
> 
> However, I received this error:
> peerjs__WEBPACK_IMPORTED_MODULE_2__ is not a constructor
> 
> Anyone can help? Thanks!

Exactly what I'm facing now with Angular 7.

@frankrobert  `import Peer from 'peerjs';` doesn't work. The error says that the module has no default export.

**Comment by afrokick** [comment]
```javascript
import { peerjs } from 'peerjs';
const Peer = peerjs.Peer;
```

@nhducseuit is it work for you?

**Comment by chak774** [comment]
Found solution.

1. add peerjs.min.js to assets/js/

2. add "src/assets/js/peerjs.min.js" to scripts array of angular.json

3. add this declaration in .component.ts
declare var Peer: any;

**Comment by nguyendinhhao17029171** [comment]
TypeError: peerjs__WEBPACK_IMPORTED_MODULE_1__ is not a constructor
Please help me with this error

**Comment by FelixSelter** [comment]
> ```js
> const Peer = peerjs.Peer;
> ```



> TypeError: peerjs__WEBPACK_IMPORTED_MODULE_1__ is not a constructor Please help me with this error

The above is actually working
