### ISSUE TITLE
Peer state is both disconnected and destroyed on network error

### ISSUE THREAD

**Issue by frankrobert-ls** [peers/peerjs#534]
I'm attempting to write some reconnect functionalities throughout my application and they cover most flows, however, among the most challenging seems to be network issues.

When I disconnect from my network it triggers a `closed` event as I believe would be expected, followed very quickly by an `error` event, and then lastly a `disconnected` event.

My reconnect function called then checks the state of the peer with `peer.disconnected` and `peer.destroyed`. In this case, both return `true`.

When attempting to then trigger `peer.reconnect()` it fails with an error saying the peer hasn't been disconnected from the server yet.
![image (1)](https://user-images.githubusercontent.com/47538444/57646026-a3c5d280-758d-11e9-9b2b-30d531f30742.png)
Meanwhile, attempting to create a new peer with the same id or calling `peer.connect` with the same ID gives a different error
![image](https://user-images.githubusercontent.com/47538444/57646190-01f2b580-758e-11e9-800f-b94cef987db8.png)

My naive understanding of the situation so far is that the reason I can't call reconnect is that the lack network makes it so that PeerJS can't communicate with the signaling server.

Any additional information or understanding would be _greatly_ appreciated. Hopefully, it's my own misunderstanding of the documentation, which could easily be resolved with some simple wording changes but worst case scenario there's a real bug here.

Edit:
Also worth noting that I'm currently using `"peerjs": "0.3.18",`. Is this an issue that's been fixed since? If so, are there any migration guides or is the API 100% backward-compatible?

Edit2:
Wondering if #513 and/or #502 resolve this issue in V1.0.0

**Comment by afrokick** [comment]
We added ping/pong feature and fix a lot of bugs since 0.3.18.

It would be nice if you check new version for issue you found in previous version.

**Comment by afrokick** [comment]
fixed in #580
