### ISSUE TITLE
Fails to pack/send modern javascript class instances due to js-binarypack issue

### ISSUE THREAD

**Issue by RealHandy** [peers/peerjs#536]
Peerjs can't send modern javascript class instance objects if their constructors == _class ClassName_ rather than _Object_. See https://github.com/binaryjs/js-binarypack/pull/13.

Peerjs imports js-binarypack and includes it in the dist, so the fix for Peerjs is to include a patched version of js-binarypack.

**Comment by kidandcat** [comment]
This will not affect the new V2. Write here and I'll reopen if it's a critical feature you need, and you can't upgrade to V2 (If you can't upgrade I recommend you to open an issue refering to what are you missing in V2 instead of staying in V1)

**Comment by RealHandy** [comment]
Commenting here that this didn't make it into 1.0.2  as indicated by @JenGL here: https://github.com/peers/peerjs/issues/540#issuecomment-514967430

This issues was closed as not a problem in V2, so I think it got lost for 1.0.2.
