### ISSUE TITLE
Webpack warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by dorthrithil** [peers/peerjs#537]
I'm using peer.js in my Angular 7 project in Typescript and I'm getting the following warning:

```
WARNING in ./node_modules/peerjs/dist/peerjs.min.js 36:17-34
Critical dependency: the request of a dependency is an expression
```

This is how I'm importing `Peer`:

`import * as Peer from 'peerjs';`

When I try to import `Peer` like described in the readme, I'm getting the same warning plus a compiler error:

```
ERROR in src/app/...ts(4,8): error TS1192: Module '"/.../node_modules/peerjs/index"' has no default export.
```

**Comment by dorthrithil** [comment]
The compiler error is gone if I enable `allowSyntheticDefaultImports` in my `tsconfig.json`. The warning is sill there, though.

**Comment by kidandcat** [comment]
I'll investigate, but Angular is always throwing strange webpack errors (there are similar issues). If you find the way to solve this one, please write me here.

**Comment by dorthrithil** [comment]
I didn't find a clean way to get rid of the warning. It seems like this warning comes if webpack cannot statically resolve some require imports. This seems to be happening somewhere around here: 

```
        // Try the node require function if it exists.
        if (nodeRequire && typeof name === 'string') {
          return nodeRequire(name);
        }
```

I'm really no expert when it comes to webpack and require.js and the like, so I wasn't able to get closer to the real solution than this.

In the end I got rid of the warning like that:

I imported Peer normally during development. After finishing the code that uses peerjs I removed the import and instead included `peerjs.min.js` in the scripts in my `angular.json`, plus I added `declare var Peer: any;` to all relevant files. Now I can compile without errors/warnings, but I really don't like his solution. 

I would be happy if this could be resolved on library side.

**Comment by udanpe** [comment]
Nuxt + typescript has same problem. Any solution?

**Comment by kidandcat** [comment]
It's an issue between Parcel and Webpack, we cannot change the bundler we use only because of that warning.

**Comment by udanpe** [comment]
@kidandcat My solution for nuxt, but, of course, it's really bad idea. I will hope you can...)
```
extend(config, ctx) {
  if (ctx.isDev && ctx.isClient && config.module) {
    config.module.exprContextCritical = false;
  }
}
```

**Comment by Pigotz** [comment]
I suggested a possible solution here https://github.com/peers/peerjs/issues/630#issuecomment-910028230
