### ISSUE TITLE
Firefox can’t establish a connection to the server

### ISSUE THREAD

**Issue by simonmeusel** [peers/peerjs#538]
I have a project using PeerJS. It works very good using the file protocol or a localhost server, but does not work with HTTPS.

Live demo: https://simonmeusel.de/e2e-p2p/
Source code: https://github.com/simonmeusel/e2e-p2p/

Error message:
```
Firefox can’t establish a connection to the server at wss://0.peerjs.com/peerjs?key=peerjs&id=43aae01d45c218f4fa4f629e05453d9755b425eb66465002f3e45ca2478085b0&token=8pgalmsvy8k. bundle.js:41:214572
Error: "Lost connection to server."
    emitError https://simonmeusel.de/e2e-p2p/dist/bundle.js:41
    _initializeServerConnection https://simonmeusel.de/e2e-p2p/dist/bundle.js:41
    emit https://simonmeusel.de/e2e-p2p/dist/bundle.js:41
    onclose https://simonmeusel.de/e2e-p2p/dist/bundle.js:41
bundle.js:17:9305
Disconnected: Peer connection error bundle.js:17:13317
```

![a](https://user-images.githubusercontent.com/16321843/59554903-b5deca80-8faa-11e9-938d-fc93ff2b82c8.png)

Peer js version: `"peerjs": "^1.0.0"` (over npm)

Firefox version: `67.0.2 (64-bit)` on MacOS

If I open the site in Chrome, it properly connects to the Peer JS broker server, but another issue occurs later on.

**Comment by kidandcat** [comment]
It connects for me in Firefox, maybe the server was down few minutes or similar?

**Comment by simonmeusel** [comment]
No, I still have the issues.
