### ISSUE TITLE
Terrible audio feedback (echo) on Android/Chrome

### ISSUE THREAD

**Issue by webseta** [peers/peerjs#539]
So I've created a P2P chat/audio/video call app using Peer.JS and on desktop it works fine but whenever one of the peers is a mobile device, terrible audio feedback occurs. Note, I'm talking about a simple audio call so it's not an issue of the local video stream being muted or not. It's not just noisy either, it's completely unusable, feedbacks to such a point where it is physically hurting to listen to.

Am I doing something wrong here?

**Comment by webseta** [comment]
Managed to solve this by reducing the audio element's volume to 0.1 on mobile devices. Is this standard practice though? :)

**Comment by kidandcat** [comment]
I never had such a problem, so can't answer you :(
