### ISSUE TITLE
using peerjs client with browserify

### ISSUE THREAD

**Issue by itsarnavsingh** [peers/peerjs#541]
I am trying to do something very simple 

var Peer = require('peerjs-client') 

and then using Browserify to output it to a bundle.js file which is obviously not working(), I guess it is also not supposed to as peerjs-client is not official, the npm page says to install peerjs-client but use a script tag to include it,

**Comment by kidandcat** [comment]
The new version preview is available, you can try it. It is not published to NPM registry. But you can install directly from github by simply:

`yarn add peers/peerjs#v2.0.0`

or

`npm install peers/peerjs#v2.0.0`

**Comment by kidandcat** [comment]
You can follow V2 progress in the PR #546
