### ISSUE TITLE
How do I reject an incoming data connection request?

### ISSUE THREAD

**Issue by bilo1967** [peers/peerjs#542]
I've three peers A, B, C communicating each other (data only) and I want to reject further incoming connections. 

A register itself on a server and eventually sends its ID to B and C (e.g. via email).
B and C also register themselves and independently call A. For each of them a data channel is set up and handled.

If a fourth peer D tries to connect to A an event is fired at A to handle a new data connection.
I would like to gracefully reject that connection.

I've tried with something like this on A's side:

```javascript
  myPeer.on('connection', function(c) {  
     if (! verify(c)) {
        c.close();
     }
     ...
  });
```

After a while, D gets an error "Error: Negotiation of connection to XXXXXXX failed" which doesn't explain the exact reason why the connection has been rejected (A is busy).

Wouldn't it be possible to add a DataConnection.reject(reason) method with a DataConnection.on("reject", function(reason) {...}) counterpart?

**Comment by kidandcat** [comment]
Yes, but as I'll soon release the new version, it is implemented there. Later when that version be stable enought, if there is people who for any reason cannot move to the new version, I'll make the fix on the old version.

Expect 1 week for the new version to be available. To be informed about the latest news: https://t.me/peerjs


Of course PRs are always welcome.

**Comment by bilo1967** [comment]
Excellent! I can surely wait the new version, since I'm still developing my project and this part would be just a refinement.

Will it be possible to reject also MediaStream calls?

**Comment by kidandcat** [comment]
Of course, rejection will be in an abstraction layer, not related to the
kind of connection, so it works the same for call or data.

**Comment by kidandcat** [comment]
https://github.com/peers/peerjs/tree/v2.0.0

**Comment by kidandcat** [comment]
Closing this, you can follow the new version development in the pull request #546

**Comment by Almo7aya** [comment]
This will never happen?!
