### ISSUE TITLE
v2.0.0: possible glitch with JQuery?

### ISSUE THREAD

**Issue by bilo1967** [peers/peerjs#545]
I've played a little with your example. See [here ](https://mypeerjs2test.netlify.com/) for full code.

I've basically added a Bootstrap4 login dialog, jQuery to select elements and handle events and a few lines of code. When a new remote mediastream `rs` is notified to the peer, a video element with an unique id (I'm using the stream id string prefixed by "`stream-`") is created, added to a div on the page and `rs` is set as its `srcObject`. This way it works:
```javascript
document.querySelector('#stream-' + id).srcObject = rs;
```
When I try to do the same with JQuery, it doesn't:
```javascript
$("#stream-"+id).attr('src', rs);
```
On the console I get an error message `GET https://my.domain.tld/[object%20MediaStream] 404 (Not Found)`

P.S.
I've just tested with Chrome, latest version.

**Comment by kidandcat** [comment]
That looks like a jQuery error, sorry but I don't know how jQuery works
