### ISSUE TITLE
Safari iOS to Chrome macOS not working

### ISSUE THREAD

**Issue by hieyou1** [peers/peerjs#553]
UA of iOS device: "Mozilla/5.0 (iPad; CPU OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"
UA of macOS device: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

Error in console (console log ("connection") is for me don't worry about it):
<img width="1001" alt="Screen Shot 2019-07-13 at 11 43 07 AM" src="https://user-images.githubusercontent.com/31020711/61174270-71bbf700-a563-11e9-91b7-0ca85674b090.png">
Thanks for taking a look!

**Comment by hieyou1** [comment]
Also gives a error in Chrome (depending on who connected to who):
<img width="553" alt="Screen Shot 2019-07-14 at 11 19 43 AM" src="https://user-images.githubusercontent.com/31020711/61186309-5a474180-a629-11e9-9799-5e95f235421c.png">

**Comment by JenGL** [comment]
I had a problem with ios, caused by bad format of the cfg passed to peerjs.
```
config: {
    iceServers: [
      {
        urls: "stun:stun.l.google.com:19302",
        url: "stun:stun.l.google.com:19302"
      },
      {
        urls: "[...]",
        url: "[..]",
        credential: "***",
        username: "***"
      }
    ],
    sdpSemantics: "unified-plan"
  }
```
I added *urls* to each iceServer entry because iOS was looking for urls member not for url, and now it's working

**Comment by afrokick** [comment]
> I had a problem with ios, caused by bad format of the cfg passed to peerjs.
> 
> ```
> config: {
>     iceServers: [
>       {
>         urls: "stun:stun.l.google.com:19302",
>         url: "stun:stun.l.google.com:19302"
>       },
>       {
>         urls: "[...]",
>         url: "[..]",
>         credential: "***",
>         username: "***"
>       }
>     ],
>     sdpSemantics: "unified-plan"
>   }
> ```
> 
> I added **urls** to each iceServer entry because iOS was looking for urls member not for url, and now it's working
> 
> I add both url and urls, because in api config it says to use url but in code DEFAULT_CFG use urls and iOS give error if you don't set urls variable ^^'

`url` is deprecated https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/url so we don't support it. Which iOS version do you use?

**Comment by afrokick** [comment]
> Also gives a error in Chrome (depending on who connected to who):
> <img alt="Screen Shot 2019-07-14 at 11 19 43 AM" width="553" src="https://user-images.githubusercontent.com/31020711/61186309-5a474180-a629-11e9-9799-5e95f235421c.png">

I think we fixed it in 1.0.1 Could you please check it again @hieyou1 ?

**Comment by JenGL** [comment]
I'll try to switch again to npm version now that 1.0.2 is out. So How to specify turn server now in config ? This is no more valid right ? ````````

**Comment by JenGL** [comment]
> `url` is deprecated https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/url so we don't support it. Which iOS version do you use?

Last iOS available - iPhone 6

**Comment by afrokick** [comment]
Yes, use `urls`

**Comment by JenGL** [comment]
everything seems to work fine with 1.0.2. I ping you again if after some test I see any Issue

**Comment by afrokick** [comment]
@hieyou1 please leave comment again if you have a problem in 1.0.2+ version.

**Comment by hieyou1** [comment]
<img width="994" alt="Screen Shot 2019-08-13 at 7 31 55 PM" src="https://user-images.githubusercontent.com/31020711/62986405-1058a380-be01-11e9-9d0c-3da8c982633a.png">
Still there, not giving me any errors though. It fires peer.on("connection") {connection event}, but never fires peer.on("open"). I wait for the connection to open before sending anything over the data channel in my app (obviously), but the connection just doesn't open. I don't know what's going wrong. For clarification it is {connection from peer.on("connection"}.on("open") that's not firing, not peer.on("open"). The latter is working as it should. Same platforms, and I updated to iOS 12.4 if that makes any difference. Using new peerjs version 1.0.2. My cdn link is: <br/>
https://unpkg.com/peerjs@1.0.2/dist/peerjs.min.js <br/>
I think that's correct? I don't know. Let me know please! thanks

**Comment by afrokick** [comment]
Could you please provide your settings?

**Comment by hieyou1** [comment]
Here's the dump (replacing my public IPv4 with "MYPUBLICIPV4")
[webrtc_internals_dump.txt](https://github.com/peers/peerjs/files/3505960/webrtc_internals_dump.txt)
In chrome://webrtc-logs/ it says that I have "no recently captured WebRTC text logs." and "no recently captured WebRTC event logs."<br />Hope this helps.

**Comment by afrokick** [comment]
@hieyou1 I think it is NAT's issue. Did you try relay server?
```
        const peer = new Peer('randomId', {
            debug: 3,
            config: {
                iceServers: [
                    { urls: "stun:stun.l.google.com:19302" },
                    { urls: "turn:0.peerjs.com:3478", username: "peerjs", credential: "peerjsp" }
                ],
                sdpSemantics: "unified-plan",
                iceTransportPolicy: "relay" // <- this is hint for WebRTC to use relay server
            }
        });
        ...
```
