### ISSUE TITLE
How to reference peerjs util with webpack.provideplugin

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#554]
I am referencing peerjs via a mirrored own repository on gitlab. When npm install is done, I see the following peerjs folder in node_modules:
![image](https://user-images.githubusercontent.com/669701/61576517-b1df2480-aae3-11e9-8272-d689d4526b4c.png)
I am able to successfully import Peer constructor via webpack.provideplugin with the following declaration:
![image](https://user-images.githubusercontent.com/669701/61576531-dcc97880-aae3-11e9-8d1e-1351dd25e735.png)
I need to also import util object so that my js logic can utilize it. But I can' figure out the correct approach to do so.

P.S. If I go with `path.resolve(path.join(__dirname, 'peerjs/lib/util'))` approach, I think my webpack will need to be able to compile util.ts and this requires a whole a lot more configuratinon to add that capability to webpack pipeline. Can util be imported from built distro in my node_modules/peersjs/dist? 

Thanks in advance for any tips you might provide!

**Comment by afrokick** [comment]
did you try `window.peerjs.util` or `peerjs.util` ? We export **Peer** and **util** via namespace **peerjs**

**Comment by maxpavlov** [comment]
Yes, I can work with peerjs.util just fine, thanks for clarification.
