### ISSUE TITLE
A proper way to check if peer object has a connection event bound in v1+

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#555]
Hi. In my app's code, I used to check if the peer has a connection event binding already via the following code:

`if (!peer._events.hasOwnProperty('connection')) {
          peer.on('connection', function (connection) {
            connection.on('data', function (data) {
`

Now I get an error when I try to get the properties of _events object like this:
`TypeError: peer._events.hasOwnProperty is not a function`

I am not a js pro but I think the protptype for _events object has changed now and we can't iterate properties via hasOwnProperty function.

What is the possible way to check of the connection even already is bound to from now on? Thanks.

**Comment by afrokick** [comment]
`peer.listenerCount('connection')` ?

Peer extends EventEmitter

**Comment by maxpavlov** [comment]
Yep, works like this. Thanks.
