### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by bilo1967** [peers/peerjs#558]
I'm getting an `Uncaught (in promise) DOMException` error when trying to assign a mediastream to a srcObject like in this snippet of code:
```javascript
            // Video call
            supervisorMedia = myPeer.call(userID, localStream, { metadata: {role: myRole} } );

            supervisorMedia.on('stream', function(mediaStream) {
                // `stream` is the mediaStream of the remote peer.
                // Here you'd add it to an HTML video/canvas element.
                
                supervisorVideo.srcObject = mediaStream;
                ...
```
The error, with latest Chrome on Windows 10 and peerjs 1.02 (but happened also with 1.0.0), is this:
```
interpreter.html:291 Uncaught (in promise) DOMException
(anonymous) @ interpreter.html:291
i.emit @ peerjs.min.js:11
l.addStream @ peerjs.min.js:28
o._addStreamToMediaConnection @ peerjs.min.js:24
e.ontrack @ peerjs.min.js:24
```
It occurs also in other parts of the code in identical situations (assign mediasource to srcObject) and either on the caller and the callee side.

By the way the connection goes on, so I just ignore it (and I don't even know if this is really an issue or not).

P.S.
Any idea when a new release of v2.0 will be ready?

**Comment by afrokick** [comment]
@bilo1967 could you please provide example of your app?

**Comment by bilo1967** [comment]
May I send you the link privately?
It's an university project I'm developing and I wish not to have the link fully disclosed and indexed before mid september.

**Comment by afrokick** [comment]
> May I send you the link privately?
> It's an university project I'm developing and I wish not to have the link fully disclosed and indexed before mid september.

Ok, just text me in telegram https://t.me/joinchat/ENhPuhTvhm8WlIxTjQf7Og Alex So

**Comment by bilo1967** [comment]
Done (or better: I hope I did it, never used Telegram before!)

**Comment by bilo1967** [comment]
Ok.

The `<video id="xyz" ... muted></video>` trick fixed the problem. I'd also had to comment out a couple of lines of code:
```:javascript
    s = document.getElementById('#'+callerRole);
    m = myPeer.call(calleeID, localStream, { metadata: {role: callerRole} } );
    m.on('stream', function(mediaStream) {
        v.srcObject = mediaStream;
        //--> v.play();
        //--> v.muted = false;
        v.onloadedmetadata = function(e) {
            v.play();
            v.muted = false;
        }
    });
```
Now it works with no warnings. Thank you very much!
