### ISSUE TITLE
peerjs_WEBPACK_IMPORTED_MODULE_2_ 

### ISSUE THREAD

**Issue by lvargass** [peers/peerjs#559]
good afternoon,

I am working on an application in **ionic 4** with angular but I am having this error;

**ERROR TypeError: peerjs_WEBPACK_IMPORTED_MODULE_2_ is not a constructor.**

when I am trying to connect to the peerjs server, eg;

**import { Component } from '@angular/core';
import { PeerJSOption } from 'peerjs';
import * as Peer from 'peerjs';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {
  protected peer: Peer;

  constructor() {
    const coon: PeerJSOption = {
      host: 'localhost',
      port: 9000,
      path: '/myapp'
    };
    this.peer = new Peer('person3', coon);
    console.log(this.peer);
  }
}**

dependences
"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "buffer": "^5.2.1",
    "core-js": "^2.5.4",
    "peerjs": "^1.0.2",
    "rxjs": "~6.5.1",
    "simple-peer": "^9.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },

**Comment by afrokick** [comment]
Did you try solution from this issue? https://github.com/peers/peerjs/issues/533

**Comment by lvargass** [comment]
No, I still have the same problem.

**Comment by dunkfordyce** [comment]
Your import line should be 
`import Peer from "peerjs"`

**Comment by ChrisAcrobat** [comment]
I get a similar issue.
`ERROR TypeError: peerjs__WEBPACK_IMPORTED_MODULE_0__ is not a constructor`
@dunkfordyce: That gives me a compile error.
![image](https://user-images.githubusercontent.com/15955091/124575766-f6d50080-de4b-11eb-92fd-6f42b754af49.png)

**Comment by ChrisAcrobat** [comment]
I solved it.
1. Add `"./node_modules/peerjs/dist/peerjs.min.js"` to `projects.THE_PROJECT.architect.build.options.scripts`.
2. In the `.ts` file add below `import`: `declare var Peer:any;`
3. Exit and restart `ng serve`! I guess this is what have been missing all along.

**Comment by afrokick** [comment]
Should be fixed in `peerjs@beta.0`
