### ISSUE TITLE
Unable to create connection to local server when internet

### ISSUE THREAD

**Issue by kunalverma94** [peers/peerjs#562]
I am running a peer server on node on my local machine .But when i am trying to connect  from client page  it  reffers to https://0.peerjs.com/peerjs/id?ts=15647394027850.8572294835316543
requst again and again...

**Comment by afrokick** [comment]
Did you change config?
```javascript
<script>
    const peer = new Peer('someid', {host: 'localhost', port: 9000, path: '/myapp'});
</script>`

**Comment by afrokick** [comment]
@kunalverma94 if you have a question - leave a new comment please

**Comment by kunalverma94** [comment]
@afrokick  It worked  .sorry for delay in  reply . Thanks :)
