### ISSUE TITLE
Is there a way to tell from code if a Reflexive connectivity is used, or communication is going through TURN relay

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#563]
Hello. Is there a way to know, after the connection to the peer has been established, if the connection with the peer (data connection or any other type) is happening through TURN relay or is s the direct connection? Thank you.

**Comment by afrokick** [comment]
Very interesting question. I'll try to investigate it.

**Comment by maxpavlov** [comment]
I've just finished setting up coturn with letsencrypt ssl and it works like a charm. The only thing missing is the ability to tell if the data being sent from peer-to-peer via direct (aka "reflexive") connection or is being relayed through TURN. Thanks, I'll be looking forward to it.

So far I've found this attempt by someone to suggest how to know if a relay is used:
https://jsfiddle.net/5ftsd5c2/17/
But it deals with RTCPeerConnection, so on a lower level.

**Comment by afrokick** [comment]
I found a way to get info about relay. You should check sdp field after connection established.

Works in Chrome 77, Safari 12.1

```
const isRelay = dataConnection.peerConnection.currentLocalDescription.sdp.includes('typ relay')` 
//or
const isRelay = mediaConnection.peerConnection.currentLocalDescription.sdp.includes('typ relay')
```

**Comment by maxpavlov** [comment]
I am afraid we got it wrong. currentLocalDescriptor will hold 'typ relay' as a candidate listing in case a configuration references an available TURN server. And there is absolute no telling if TURN is actually to be used if we start sending data right now. So we are yet to find out how to detect TURN traffic.

**Comment by Payetus** [comment]
I think there is something you can do with the getStats API
