### ISSUE TITLE
Default port is 443?

### ISSUE THREAD

**Issue by d07RiV** [peers/peerjs#567]
How come `new Peer({host: 'www.myserver.com'})` sends a request to `http://www.myserver.com:443/...`?

**Comment by afrokick** [comment]
from `lib/util.ts`

**Comment by d07RiV** [comment]
I suppose that's a documentation issue, then? It says

    port NUMBER
    Server port. Defaults to 80.

**Comment by afrokick** [comment]
@kidandcat We need to deploy docs to site.

**Comment by afrokick** [comment]
updated https://docs.peerjs.com
