### ISSUE TITLE
DataConnection.on('close') event is not firing when another close the connection. 

### ISSUE THREAD

**Issue by leonraw** [peers/peerjs#568]
When a peer closes the connection(use `DataConnection.close()` or in other ways). It will triggers the self `DataConnection.on("close")` event but the other one does not.

It works fine at about _v0.3.18._ But it won't be triggered since _1.0.x._
#41

**Comment by lagcamgc** [comment]
Hello, i'm having the same issue, any update on this bug?

**Comment by afrokick** [comment]
@leonraw @lagcamgc please check it in new version 1.0.4
