### ISSUE TITLE
Created peer cant connect to cloud server in devicee

### ISSUE THREAD

**Issue by chak774** [peers/peerjs#569]
I have wrote a program using peerjs in Ionic 3. I can run them successfully in computer browsers and computer android emulator (successfully connecting other peers and send/receive messages). However, I found there are no connection to cloud server when I am testing it in an android device.

This is the result from Chrome DevTools:
1. this.peer.on('open', ...) is not fired.

2. And I have also logged the created "Peer" object. 
the socket property is undefined, _id is null.

So, I guess its the connection problem to the cloud server. Anyone has idea? Thanks.

**Comment by afrokick** [comment]
It is hard to suggest any ideas without a log.

Did you try to print log messages to screen on android device?
