### ISSUE TITLE
How do I get a PeerServer key?

### ISSUE THREAD

**Issue by Holyprogrammer** [peers/peerjs#571]
Sorry, I just discovered peerJS today, so this question may be stupid.

[The PeerJS Documentation](https://peerjs.com/docs.html#api) says

> The 'key' we're passing in to the Peer constructor is a PeerServer cloud API key. You can use ours for now, but you should [sign up for your own free key](https://peerjs.com/peerserver.html).

However, the given link just leads to [this](https://peerjs.com/peerserver.html) page, which doesn't have instructions on how to get a PeerServer key.

**Comment by mgoulao** [comment]
You don't need to #510. The website has some dead links and old information, it needs to be updated

**Comment by Holyprogrammer** [comment]
Great! Thanks!
