### ISSUE TITLE
Add ordered instead of deprecating reliable option for connect

### ISSUE THREAD

**Issue by maxpavlov** [peers/peerjs#573]
Hi. As per official docs, reliable property of the connection has been abandoned, and now we should work with an ordered property:
https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/ordered

I think we should add this checking to util and connection options.

**Comment by afrokick** [comment]
Its work only in chrome, so we use Reliable library to implements reliable logic.

**Comment by afrokick** [comment]
I improved checking in util #577
