### ISSUE TITLE
PeerJS does not work in Safari

### ISSUE THREAD

**Issue by themindstorm** [peers/peerjs#574]
I tried a simple example, and it works in Chrome and Firefox. Here's the code:

# index.html (host)
```
<head>
  <title>Send</title>

  <button onclick="sendMessage()">Send message</button>
</head>

<body>
  
  <script src="https://cdn.jsdelivr.net/npm/peerjs@0.3.20/dist/peer.min.js"></script>
  <script>
    var peer = new Peer({key: 'first'})
    let conn;

    peer.on('open', function(id) {
      console.log('My peer ID is: ' + id);
    });

    peer.on('connection', function(connection) {
      console.log('Connected!');
      conn = connection;
      conn.on('data', function(data) {
        console.log(data)
      })

      conn.on('disconnected', function() {
        console.log('disconnected :(');
      })
    })

    function sendMessage() {
      conn.send('hello from index')
    }
  </script>
</body>
```

# rec.html (receiver)
```
<head>
    <title>rec</title>
  </head>
  
  <body>
    <button onclick="sendMessage()">Send message</button>

    <script src="https://cdn.jsdelivr.net/npm/peerjs@0.3.20/dist/peer.min.js"></script>
    <script>
      var peer = new Peer({key: 'first'})
      var conn = peer.connect(prompt('id'))
  
      conn.on('open', function(peer) {
        console.log('connected?')
      });

      conn.on('data', function(data) {
        console.log(data);
      });

      function sendMessage() {
        conn.send('Hello from rec again');
      }
    </script>
  </body>
```

It does not work on Safari, and returns the error message:
```
Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary
```

I'm on the latest version of MacOS Mojave. Is there anything I can do to fix this problem?

The [example](https://jmcker.github.io/Peer-to-Peer-Cue-System/) on the website also does not work in Safari.

**Comment by alexbonair** [comment]
The current version is 1.0.3, you should try this one

**Comment by afrokick** [comment]
@themindstorm did you try to use the latest version of PeerJS?

**Comment by alexbonair** [comment]
@afrokick Yes, I use the latest, but I downloaded the current master from github ;)

**Comment by afrokick** [comment]
@themindstorm try to test on my example.

1. open https://afrokick.github.io/examples/simple-chat/ copy your id and click Connect
2. open another tab, paste copied id to remove id and click Connect
3. should works

**Comment by JanKaifer** [comment]
> @themindstorm try to test on my example.
> 
> 1. open [afrokick.github.io/examples/simple-chat](https://afrokick.github.io/examples/simple-chat/) , copy `Your nickname`, click `Connect`
> 2. open another tab, paste copied id to `Remote nickname`, click `Connect`
> 3. should works
> 
> The example uses the latest version of PeerJS from master, i think it'll be `1.1.0`
> 
> If issue still exists - leave a new comment please

I tested your example on newest version of Safari and it doesn't work. I gets stuck on connect in both tabs:
<img width="640" alt="CleanShot 2021-09-24 at 15 04 45@2x" src="https://user-images.githubusercontent.com/12820484/134678922-9423f7c0-20f3-497c-bfde-fe17a58e2dc0.png">
