### ISSUE TITLE
Non-minimized version in distribution

### ISSUE THREAD

**Issue by hacklaen** [peers/peerjs#578]
Is it possible to include a non-minimized version of peerjs in the dist sudirectory?
It would be helpful for debugging purposes and to have a "quick view" into the code.

**Comment by afrokick** [comment]
@hacklaen hi
I'll investigate it. But if you know how to configure Parcel - share with us please)

**Comment by afrokick** [comment]
You can run this command to create a non minified library.
`parcel build lib/exports.ts --out-file peerjs.js --no-minify`

**Comment by afrokick** [comment]
added in 1.1.0
