### ISSUE TITLE
multi reference objects don't survive serialization on send.

### ISSUE THREAD

**Issue by givensnickel** [peers/peerjs#582]
Sorry for opening two tickets on pretty much the same thing ( #581 ), though I might have a possible solution. In this issue if an object has multiple references to the same object the value is cloned so the values are not the same.

Example:
``` javascript
// Sending side:
let common_value = ["This is a mutable object."]
let obj = { one: common_value, two: common_value }
Object.is(obj.one, obj.two) // true
Object.is(obj.one, ["This is a mutable object."]) // false
connection.send(obj)

// Receiving side:
connection.on('data', obj => { 
    // obj = { one: ["This is a mutable object."], two: ["This is a mutable object."] }
    Object.is(obj.one, obj.two) // false
    Object.is(obj.one, ["This is a mutable object."]) // false
})
```

As a solution I found [dojox](https://www.sitepen.com/blog/json-referencing-in-dojo/) which would provide serialization to solve both this issue and issue #581.

**Comment by afrokick** [comment]
@givensnickel could you please try my PR with **flatted**? https://github.com/peers/peerjs/pull/592

**Comment by kidandcat** [comment]
This is not a library issue, but you are missing the concept of pointers in JS, before sending, your obj.one  and obj.two are pointers to common_value. Of course after sending them, they are resolved to their value before serializing them.

I don't think flatted work for this example neither.

**Comment by givensnickel** [comment]
> @givensnickel could you please try my PR with **flatted**? #592

@afrokick that is perfect! And exposing the serialization per connection is also wonderful for extending it per use case. Thank you!

@kidandcat Flatted worked perfectly for both circular references and pointer references, preserving the object structure in both cases.

**Comment by afrokick** [comment]
@givensnickel thanks! We will release it in 1.2.0.

**Comment by givensnickel** [comment]
Cool! Glad to hear.
