### ISSUE TITLE
PeerJS Doesn't Work with iOS 13

### ISSUE THREAD

**Issue by KhushrajRathod** [peers/peerjs#583]
I don't have a mac, so I can't debug iOS. But I know that my software works on all devices except for those with iOS. Please help. Thanks.

Software -
1. irritator.holyprogrammer.tech
2. iOS 13

Steps:
1. Open join menu
2. Try connecting using PeerID

**Comment by rasca0027** [comment]
It works on mine. Can you provide more details, like the error message?
When I first tried, there's some error in the iceServer configs I provided, turns out instead of `url` I had to use `urls`. But maybe you can at least paste the code you're using?

**Comment by jooeycheng** [comment]
Hey @KhushrajRathod, i got it to work by changing serialization to json. Default is binary. See https://github.com/peers/peerjs#safari.

**Comment by sivakotisrinivas** [comment]
Hi. I have used peerjs for video chat,my local Stream and video stream is not working in ios.so please guide me
here is the image attached in ios mobiles 
![WhatsApp Image 2021-05-14 at 13 43 30](https://user-images.githubusercontent.com/22904111/119086765-99aff780-ba23-11eb-8b56-5015f91efcd8.jpeg)
