### ISSUE TITLE
Unable to send binary data from Safari

### ISSUE THREAD

**Issue by rasca0027** [peers/peerjs#587]
I'm using Safari 13. 
I can only connect to another peer when the serialization is `json`. When I try to use `binary` or `binary-utf8`, or not specifiy the serialization, the other side does not receive any data. There's no error in the console either.

**Comment by afrokick** [comment]
I think currently Safari supports only String(JSON serialization).

https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/send

If you send a small amount of data - just use json.

By default, PeerJS uses Binary serialization.

**Comment by afrokick** [comment]
I added a tip to readme about serialization type for Safari. @rasca0027 thanks!

**Comment by prodigy2m** [comment]
Hi, I tried sending data using JSON.stringify('hi') but it doesn't work for me. Can someone provide a good example of json serialization for Safari 13? Thank you in advance
