### ISSUE TITLE
Cannot import from typescript

### ISSUE THREAD

**Issue by adadgio** [peers/peerjs#589]
Hello, despite looking at similar issues "apparently" resovled, typescript imports are broken:

- (Docs) import Peer from 'peerjs' --> has not default export
- import { Peer } from 'peerjs' --> has no exported member Peer
- import * as peerjs from 'peerjs' --> no TS error but at runntime, new Peer is not a function (its an object...)

Is there any quick fix to this, its really sad! :/

**Comment by therealtimhawkins** [comment]
I am having the same issue! Thanks!

**Comment by afrokick** [comment]
Should works

```
import Peer from 'peerjs';

console.log(new Peer())
```

**Comment by caribeedu** [comment]
+1

**Comment by afrokick** [comment]
@caribeedu share your tsconfig please

**Comment by caribeedu** [comment]
@afrokick I don't have an, I using in a NodeJS simple project and is giving a similar error, i'm hoping the solution of this issue is the same for me

**Comment by m-thompson-code** [comment]
This issue is preventing my team from using this library with Angular.

Is there any alternative way for us to import peerjs while allowing us to have types?

**Comment by louayrm12** [comment]
it's working just add the library and import it like this

`import Peer from 'peerjs';`

**Comment by m-thompson-code** [comment]
By adding esModuleInterop to the project's tsconfig.ts, we were able to successfully use peerjs and make a build with Angular 11:

```
{
    // ...
    "compilerOptions": {
        // ...
        "esModuleInterop": true, // <-- add this
    }
}
```

 By doing this, `import Peer from 'peerjs';` works. We do get the warning: "Critical dependency: the request of a dependency is an expression" whenever we serve/build, but I haven't noticed anything odd yet. Also this warning isn't critical as mentioned here: [peerjs FAQ](https://github.com/peers/peerjs#faq).

Hopefully this solution works for you @adadgio

**Comment by afrokick** [comment]
fixed in `peerjs@beta`
