### ISSUE TITLE
Throws error in IE11

### ISSUE THREAD

**Issue by dsjdigital** [peers/peerjs#590]
In Internet Explorer 11, loading of the 1.0.0 version of PeerJS throws the following error:
`Object doesn't support property or method 'keys'`

I know you do not officially support IE11 (neither do we ;-)) but one of our customers is still using it..

**Comment by cracker0dks** [comment]
IE11 Does not support WebRTC at all (https://caniuse.com/#feat=rtcpeerconnection). So you need to catch unsupported browsers and send them an alert.

**Comment by dsjdigital** [comment]
Clear, thanks!
