### ISSUE TITLE
Peerjs with webrtc

### ISSUE THREAD

**Issue by tapkain** [peers/peerjs#593]
Hello, I'm new to webrtc and peerjs. My team created a website with the help of peer js, an analogue of chatroulette. The problem is that peerjs doesn't work in mobile browsers, so we decided to create a native app with webrtc support.
question - how to connect plain webrtc client to peer js server and is it possible to achieve good performance with this approach?
Much thanks 💚

**Comment by UnknownPlayer78** [comment]
PeerJS does in fact work in browsers but I cannot figure out why the `on` events aren't triggering. Because if you check `peer.connections` then you can see them there but they don't send data because `peer.send` is inside of the `peer.on("connection")` which is not working who knows why.

**Comment by patka817** [comment]
It works in mobile, at least android, with Chrome. Been testing multiplayer games with webrtc between mobile and pc

**Comment by ttejas123** [comment]
I found peerjs able to connect but not able to send data to other peers.
here i am only include mobile related issues. It's working pretty good at laptops, pc.

**Comment by troger19** [comment]
Hi guys. Same problem here. PeerJS works lovely on PC but cant work on Android. ANy idea why?
