### ISSUE TITLE
call.answer(stream) not emitting data back to the caller

### ISSUE THREAD

**Issue by mckayze** [peers/peerjs#601]
My caller never has connection open status on the call object created from making a call.

    // Attempts to make a call to the peer
            callPeer(){
                let t = this;
                navigator.mediaDevices.getUserMedia({ audio: true})
                    .then((stream) => {
                        let call = t.peer.call(t.callee.id.trim(), stream);

                        // Logs
                        console.log(stream);
                        console.log(call);

                        //inserting our stream to the video tag
                        let audio = document.querySelector('audio');
                        audio.src = window.URL.createObjectURL(stream);

                        call.on('stream', (remoteStream) => {
                            console.log('EVENT: call => stream'); // Never logs
                            console.log(remoteStream); // Never logs
                        });
                    }, (err) => {
                        console.log(err);
                    })
            },

            // Initializes the open event listeners, this is more for the callee side of things
            initOpenListeners(){
                let t = this;

                this.peer.on('open', function(id) {
                    t.myId = id;
                });

                this.peer.on('call', (call) => {
                    navigator.mediaDevices.getUserMedia({ audio: true})
                        .then((stream) => {
                        call.answer(stream);

                        // Logs
                        console.log(stream);
                        console.log(call);

                        //inserting our stream to the video tag
                        let audio = document.querySelector('audio');
                        audio.src = window.URL.createObjectURL(stream);

                        // Answer the call, providing our mediaStream
                        call.on('stream', (remoteStream) => {
                            console.log('EVENT: call => stream'); // Never logs
                            console.log(remoteStream); // Never logs
                        })
                    });
                });
            },

Everything else works, calls are activated (when I make a call the other user receives it) but neither calle / caller ever has their stream event fired.

**Comment by andyloweruk** [comment]
Same here. Any luck with it?

**Comment by mckayze** [comment]
@andyloweruk Yes actually i got it working fully, would you like a sample of the code? It all fits within a single page but you can expand and separate the code as needed

**Comment by andyloweruk** [comment]
That would be great, thank you!

**Comment by mckayze** [comment]
@andyloweruk do you have discord or something thatd make contacting easier? I'll need to edit the code in a bit i was in the midst of refactoring it so its in a non working state atm

**Comment by andyloweruk** [comment]
andylower6#9578 on Discord. Appreciate this, thanks.

**Comment by dunkfordyce** [comment]
@mckayze @andyloweruk What was the answer please?

**Comment by andyloweruk** [comment]
@dunkfordyce It was an issue with https://www.npmjs.com/package/react-native-peerjs that I was using on the other end. The developer of this package fixed a bug shortly after I posted above.

**Comment by KNVB** [comment]
I am creating a web application which is using Node.js and peerjs library.

All the source code can be downloaded from [here.](https://www.sendspace.com/file/dfok27) The client-side code is working on localhost only. My client-side design is that:

The web page has 2 video tag, 1 for display local stream and the other for the remote stream.

To access the web application, browse the following URL:

http://localhost:9000/id

where

if the id is 1, it shows the local video stream.

if the id is 2, it plays the local audio stream and a send stream button.

When the send stream button is clicked, it will use peerjs to connect to client "1".

I found that the client "1" receives the audio stream from the client "2".

Although client "1" answered the call from client "2" with its video stream (line 72 of room.ejs), in the client "2" side, it does not receive anything from client "1" any more.

I don't know why?

**Comment by kunalkashyap855** [comment]
@mckayze @andyloweruk can you guys please post the solution here as well

**Comment by afrokick** [comment]
Close the issue. IF anyone have a problem please open a new issue with demo to reproduce.
