### ISSUE TITLE
peerjs Server not working on mobile

### ISSUE THREAD

**Issue by anatoli308** [peers/peerjs#603]
Hello,

I have tried the Combining with existing express app example and it didnt work on my iphone 10.
I always get the error message "Error: Lost connection to server"

my code is this:

const express = require('express');
const app = express();
const ExpressPeerServer = require('peer').ExpressPeerServer;

 var server = require("https").createServer({
      key: fs.readFileSync('server.key'),
      cert: fs.readFileSync('server.cert')
    },expressApp);
const peerserver = ExpressPeerServer(server, options);

app.use('/peerjs', peerserver);

server.listen(443);

frontend:
var peer = new Peer("peer", signalingServer);
var errorFn = e => {
            alert(e); //PROBLEM ios Error: lost connection to server
        };
  peer.on("error", errorFn);
const signalingServer = {
  host: '192.168.1.10',
  port: 443,
  key:'peerjs',
  path: '/peerjs'
 },
debug: 3
};

**Comment by ncg81** [comment]
@anatoli308 

Is your server SSL certificate self signed? If so, is the CA used to generate the server's SSL certificate known to your device? In other words, have you imported it in iOS?

**Comment by anatoli308** [comment]
Thanks for the reply.
I have found the issue. The peer server doesn't work on a local enviorment on ios/safari. On windows everything is running fine so far. I always get the Error message "Error: Lost connection to server" on ios. Also my local enviorment is running on https with a self-signed certificat.
It could be my code implementation, but i have tried everything and didn't have found a solution
Everything works fine when running productive on a domain.

My next issue is, that the disconnecting of your peer partner is delayed on ios. Could also be my own mistake with my code implementation, but haven't verified yet.
