### ISSUE TITLE
Call.on('close') is few seconds delayed

### ISSUE THREAD

**Issue by Vichp** [peers/peerjs#605]
After I end the call, the call.on('close') method executes after a delay of a few seconds. This is on my localhost development environment. I tried using both the default STUN ICE server from the peerJS docs (stun.l.google.com:19302) AS well as my own STUN server that I've set up with coturn. Yet no difference and same delay, no matter what. Delay exists in both Chrome and Firefox.

I've also noticed that regardless of if I use my own stun server address or google's, the same ICE candidates ip address (92.84.33.39) appears with both cases - as can be seen in the picture below.

<img width="956" alt="Screenshot 2019-12-10 at 16 10 04" src="https://user-images.githubusercontent.com/2426841/70536959-5ed83d80-1b68-11ea-89e1-762bfebb76ac.png">

What is causing the delay and how can it be fixed, any ideas? @kidandcat  

(As a side note, DataConnection, that is sending and receiving messages/data between the two peers does not have any delay at all.)

Thanks in advance.

**Comment by afrokick** [comment]
Sorry, seems like a bug in the browsers, we can't fix it.
