### ISSUE TITLE
Problem with mediaConnection.on('stream') in react-native

### ISSUE THREAD

**Issue by Ponao** [peers/peerjs#612]
My actions:
1) `install peerjs`
2) At the beginning of the peerjs.min.js file, import `react-native-webrtc`
3) Trying to connect to the client in the browser
4) The `peerPrivate.on('call')` event fires and I answer the call and listen to the stream event
5) nothing else happens, `on.('Stream')` is not working in react native and not in the browser (provided that the calling or receiving client is `react-native`)

Here is my `react-native` code

```
privatePeer.on('call', call => {
        mediaDevices.getUserMedia({
            audio: true,
            video: true
            })
            .then(stream => {
               call.answer(stream)
            })
    
        call.on('error', console.log)
    
        call.on('stream', stream => {
            console.log(123)
        })
    })
```
Here is my web code

```
var getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia
                                                
    getUserMedia({video: true, audio: true}, (stream) => {
      let call = p.call(id, stream, options)

      call.on('stream', (remoteStream) => {
        console.log(123)
        var video = document.querySelector('video')
    
        if ('srcObject' in video) {
          video.srcObject = remoteStream
        } else {
          video.src = window.URL.createObjectURL(remoteStream) // for older browsers
        }
    
        video.play();
      })
      call.on('error', (err) => {
        console.log(err)
    })
    }, (err) => {
      
    })
```
The `call.on('stream')` event does not fire in either the browser or react native

**Comment by afrokick** [comment]
Could you please create a test repo to reproduce the issue?

**Comment by Ponao** [comment]
Thank you so much for the afrokick solution.

As a temporary solution:
1) You need to implement `addTrack` method:
```
RTCPeerConnection.prototype.addTrack = function (track, stream) {
    this.addStream (stream); 
} 
```
or maybe
```
RTCPeerConnection.prototype.addTrack = function (track, stream) {
    this.addStream (new MediaStream ([track])); 
}
```
2) You need to handle onaddstream if ontrack not working:
```
call.peerConnection.onaddstream = function (event) {
   call.addStream (event.stream, call);
}
```

the first step - before call `new Peer`
the second - after create | receive a `call(MediaConnection)`
