### ISSUE TITLE
Data Connection Failure on iOS

### ISSUE THREAD

**Issue by ChiefMilesEdgeworth** [peers/peerjs#614]
Hi, I'm working on a web application, and PeerJS works perfectly fine when using it on desktop, with multiple browsers. However, when I try to use it on iOS with those same browsers or Safari, I am able to open a new Peer object and get an ID, but I am not able to connect to another Peer. It doesn't work going either way between desktop and iOS, or for iOS on both sides. If this is an issue that has come up before, feel free to point me to the right place. I'm happy to provide code if you need, the project is open source. Thank you!

**Comment by Chovin** [comment]
I've also noticed this happening right after I updated my iOS device. Perhaps downgrading peerjs for now is the best option?
#### on peerjs 1.0.0 ❌ 
I'm able to form a connection and I'm able to receive information from a non-iOS device, but I can't send information the other way, from an iOS device to a non-iOS device. 
#### on peerjs 1.1.0 ✅ 
iOS <-> non-iOS connects and is able to send data both ways
#### on peerjs 1.2.0 ❌ 
I'm not able to form a connection between an iOS and non-iOS device (I haven't tried iOS<->iOS)

**Comment by ChiefMilesEdgeworth** [comment]
I set the serialization to json and it seems to work fine now. This probably isn't the same issue you're having, since I think I'm running the stable version (1.0.0). Thanks anyways though!
