### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by marcoippolito** [peers/peerjs#616]
I'm trying to figure out how to make PeerJS working with Vue.js:
  https://peerjs.com/docs.html#start

This is the Vue file:

    <template>
      <div>
        <p>My Peer Id : {{ myPeerId }}</p>
        <hr>
        <p>Remote Peer Id
          <input v-model="remotePeerId">
        </p>
        <hr>
        <p button @click="connect()">Connect to my friend!</p>
        <hr>
        <div class="col-xs-12 col-sm-6">
          <h3>Received Messages</h3>
          <ul class="list-group">
            <li class="list-group-item" v-for="message in messages">Message: {{ message }}</li>
          </ul>
        </div>
      </div>
    </template>

    <script>
        import Peer from 'peerjs';

        export default {
          data: () => ({
            connection: null,
            connecting: true,
            message: '',
            messages: [],
            myPeer: null,
            myPeerId: '',
            remotePeerId: ''
          }),
          created() {
            this.myPeerId = (Math.random() * 6 + Math.random()).toString(36).replace('.', '');
            this.myPeer = new Peer({ id: 'this.myPeerId', key: 'lwjd5qra8257b9' })
            this.myPeer.on('open', (id) => {
              console.log('Connected at PeerJS server with success')
              console.log('My peer ID is: ' + id);
              this.connecting = false
            })
          },
          computed: {
          },
          methods: {
            connect() {
              if (this.remotePeerId.trim().length) {
                this.connection = this.myPeer.connect(this.remotePeerId)
                // Receive messages:
                this.connection.on('data', (data) => {
                  this.connection.on('data', data => this.messages.push(data))
                })
              }
            },
            sendMessage() {
              const newMessage = {
                id: this.myPeerId,
                message: this.message
              }
              if (this.connection) {
                this.connection.send('Hello')
              }
              this.messages.push(newMessage)
              this.message = ''
            }
          },
          filters: {
          }
        }
    </script>

But it outputs the error message: Error in v-on handler: "TypeError: Cannot read property 'on' of undefined"

![PeerJS-Test-01](https://user-images.githubusercontent.com/3073209/72432116-8d17f100-3796-11ea-9267-dd70fda0a8af.jpg)

![PeerJS-Test-02](https://user-images.githubusercontent.com/3073209/72432126-91440e80-3796-11ea-83d5-210461262836.jpg)

How to solve the problem?

**Comment by frnsys** [comment]
@marcoippolito did you solve this? If so, do you mind explaining what you did to fix it instead of just closing the issue?

**Comment by marcoippolito** [comment]
@frnsys I do not actually remember how I "solved" it. But you can find here a working simple example with PeerJs and Vue.js: https://github.com/marcoippolito/PeerJS-VueJS-Test
