### ISSUE TITLE
peerjs.com 402: PAYMENT_REQUIRED

### ISSUE THREAD

**Issue by stayingqold** [peers/peerjs#619]
When going to https://peerjs.com I get a page with this error:
```
402: PAYMENT_REQUIRED
Code: DEPLOYMENT_BLOCKED
ID: lax1:l8zdh-1579726517770-761faff2d5e1
```
It also has a link to this page: https://zeit.co/docs/error/application/DEPLOYMENT_BLOCKED

**Comment by kyleplo** [comment]
You can view it on the wayback machine
http://web.archive.org/web/20200111154824/https://peerjs.com/

**Comment by s-h-a-d-o-w** [comment]
@kyleplo Have you actually tried to look at the API reference there? Because it seems like waybackmachine hasn't archived that: http://web.archive.org/web/*/https://docs.peerjs.com/

**Comment by afrokick** [comment]
@kidandcat

**Comment by kidandcat** [comment]
Sorry for the late fixing, the pricing plans where updated and I didn't noticed it. Working
