### ISSUE TITLE
Demo doesn't work in Chrome 79.0.3945.

### ISSUE THREAD

**Issue by schweini** [peers/peerjs#621]
The demo online only "connects" on Chrome, but none of the buttons does anything. JS Console shows no errors or anything at all, apart from the id.

Works fine in FF, though.

**Comment by jmcker** [comment]
Is this the https://jmcker.github.io/Peer-to-Peer-Cue-System demo? If so, we can move this over to [https://github.com/jmcker/Peer-to-Peer-Cue-System/issues](this repo). I'll take a look on the computer in a bit. I can confirm it works on Chrome 79.0.3945 mobile right now.

**Comment by schweini** [comment]
Yes, I meant that demo.

I can confirm that it works on chrome on Android, but I just checked on my
(win10) PC, and it doesn't work there.

**Comment by jmcker** [comment]
I can confirm what you're seeing on Windows 10. It looks like the connection never opens on the sender.

Strangely though, if I serve a local copy, I can use it to connect and properly send signals without issue.

**Comment by afrokick** [comment]
@jmcker could use please update peerjs version in demo to the latest `1.0.3`?

**Comment by jmcker** [comment]
Updated. Seems to be working properly. Any insight into what caused it @afrokick?

**Comment by afrokick** [comment]
Sorry, i don't know. There was a bunch of changes since 0.3.10

**Comment by schweini** [comment]
Works for me now. Thanks!
