### ISSUE TITLE
Using the library on Node.js causes "Check failed: Handle not reset in first callback."

### ISSUE THREAD

**Issue by VictorTaelin** [peers/peerjs#623]
I'm using Peer.js on Node.js `v11.4.0`. My code looks like this:

```javascript
var Peer = require("simple-peer");
var peers = [];
peer.on("signal", data => { ... });
peer.on("connect", () => { ... }); // adds to the list of peers
peer.on("data", (data) => { ... });
peer.on("error", (eer) => { ... });
peer.on("close", () => { ... });
setInterval(() => ... send data to peers with peers[...].send(...) ..., delay);
```
In other words, it just receives some connections, adds them to an object and sends messages to peers on a timer. It works fine, except, at random moments, my whole application will crash with the `"Check failed: Handle not reset in first callback."` error. Removing Peer.js from my code completely prevents the issue. 

I'd like to know if this is a known problem and what could be causing it.

**Comment by afrokick** [comment]
Please use the newest `npm i peerjs@beta` version with NodeJS support. The first version doesn't work with NodeJS.
