### ISSUE TITLE
send/receive Live demo JS error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [peers/peerjs#624]
Hi,

here is the error when I try to connect to the otherr peer.
Failed to execute 'createOffer' on 'RTCPeerConnection': The callback provided as parameter 1 is not a function.(…)

**Comment by afrokick** [comment]
@ROBERT-MCDOWELL please provide more info about your environment (OS, PeerJS version)

**Comment by ROBERT-MCDOWELL** [comment]
Seamonkey 2.49.5 (html5 compatible)
Windows XP/7/10

**Comment by ROBERT-MCDOWELL** [comment]
Seamonkey 2.49.5 (html5 compatible)
Chrome 49.x
Firefox 52.9.0
Windows XP

**Comment by afrokick** [comment]
Sorry, have no idea. Seems like not peerjs issue. Please, leave a new comment if it still exists in the new version of browsers.
