### ISSUE TITLE
Cannot open DataConnection in Chrome 80.0.3987.100 (MacOS 64-bit) - Firefox and Safari work fine

### ISSUE THREAD

**Issue by woudsma** [peers/peerjs#627]
In Chrome I cannot get `dataConnection.on('open', function() { ... });` to fire after calling `peer.connect(destPeerId)`. In Safari and Firefox I don't have this problem, they show the messages in the console in both windows.

Am I missing something in my Chrome settings? All tips welcome.
Example approach with redux and redux-thunk:
```js
export const createPeer = () => (dispatch, getState) => {
  const peer = new Peer({
    host: NODE_ENV === 'production' ? PEER_SERVER_HOST : 'localhost',
    port: NODE_ENV === 'production' ? PEER_SERVER_PORT : 9000,
    secure: NODE_ENV === 'production' ? true : false,
  })
  dispatch({ type: constants.CREATE_PEER, peer })

  peer.on('connection', peerConn => {
    dispatch({ type: constants.PEER_CONN, peerConn })
    peerConn.on('open', () => peerConn.send('hello from callee'))
    peerConn.on('data', console.log)
  })
}

export const connectToPeer = destPeerId => (dispatch, getState) => {
  const { peer } = getState()
  const conn = peer.connect(destPeerId)
  conn.on('open', () => {
    dispatch({ type: constants.CONN_OPEN, conn })
    conn.send('hello from initiator')
  })
  conn.on('data', console.log)
}

// ...

store.dispatch(createPeer())
store.dispatch(connectToPeer('<peer-id>'))
```

When I run the app in 2 Chrome browser windows the `CONN_OPEN` action never fires. It does fire in Firefox and Safari. Tested on localhost and on a self-hosted PeerServer (with SSL enabled). The `PEER_CONN` action does fire, so it seems the connection is accepted by the callee but the initiator doesn't receive the `open` event in Chrome.
Is this a bug or is there something wrong on my end?

**Comment by woudsma** [comment]
Tried it out on a new Macbook running MacOS Catalina 10.15.2, now my example does work in Chrome (version 80.0.3987.106). It also still works on Firefox, and cross-browser between Firefox/Chrome, but now it does not work in Safari (13.0.4) anymore.. Argh.

You can probably close this issue, unless someone has some feedback on usage in Safari on Catalina!

**Comment by juliuszfedyk** [comment]
I have the issue on Chrome when both users are behing nav. Please check https://li2039-53.members.linode.com/ to reproduce.

**Comment by JenGL** [comment]
I have the same problem, testing on localhost in the same PC...
No problem with chrome or firefox, but safari is not working.
