### ISSUE TITLE
Unable to disable audio/video

### ISSUE THREAD

**Issue by alfonsograziano** [peers/peerjs#638]
I'm creating a connection between two peers. Stream is "stored" in window.localStream and window.remoteStream. I'm trying ho create two toggles for enable/disable local video and audio.

That's my code: 
`  const [mediaEnabled, setMediaEnabled] = useState({ video: true, audio: true })

    const setAudioStream = (enabled) => {
        window.localStream.getAudioTracks().forEach(track => track.enabled = !track.enabled);
        console.log("Audio:" + window.localStream.getAudioTracks()[0].enabled)
        setMediaEnabled({ ...mediaEnabled, audio: enabled })
    }

    const setVideoStream = (enabled) => {
        window.localStream.getVideoTracks().forEach(track => track.enabled = !track.enabled);
        console.log("Video:" + window.localStream.getVideoTracks()[0].enabled)
        setMediaEnabled({ ...mediaEnabled, video: enabled })
    }
`

The problem is that when i disable my local video (the same for audio) the local-video tag became black (MediaStreamTrack.enabled = false), but on the second peer i could see the video streaming of the peer. How is this possible if the videoTrack is disabled?

**Comment by jrowny** [comment]
I have very similar code in my app and it's working fine, maybe there's a duplicate or cloned stream in your code somewhere?
