### ISSUE TITLE
Echo soltuion in peer js

### ISSUE THREAD

**Issue by veezo2007pk** [peers/peerjs#646]
i have these two code which make the call, i need to know who i can cancel the echo audio?

```
  function makeCall(callerID, isVideoCall) {
        console.log("Calling..." +  callerID)
        
        var options = {audio: true};
        if(isVideoCall)
            options['video'] = true;

        initializeLocalMedia(options, function() {
            myapp.showVideoCall(options)
            var call = peer.call(callerID, window.localStream, { 'metadata' : options });
            callConnect(call)
        });
    }

 ```
 function initializeLocalMedia(options, callback) {

        if(options) {
            options['audio'] = true;
            if(options['video'])
                options['video'] = true;
        } else {
            options['audio'] = true;
            options['video'] = false;
        }

        // Get audio/video stream
        navigator.getUserMedia(options, function(stream) {
            // Set your video displays
            window.localStream = stream;
            myapp.setMyVideo(window.localStream)
            if(callback)
                callback();
        }, function(err) {
            console.log("The following error occurred: " + err.name);
            alert('Unable to call ' + err.name)
        });
    }
```

**Comment by afrokick** [comment]
sorry, it is business logic of your app, it doesn't relate to PeerJS
