### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by cashpipeplusplus** [peers/peerjs#649]
PeerJS is wonderful stuff.  I'm using it in an [open-source game](http://cashpipeplusplus.github.io/othello/), using the PeerServer Cloud service by default.

I was looking for a privacy policy for that service, but I was unable to find one.  I'd like to link to it from my own privacy policy.

Do you have something like that?  If not, could you write one?  I don't think it would have to be written by a lawyer to be useful.

Thanks!

**Comment by afrokick** [comment]
You can use it as you want, just follow MIT license's agreements.

**Comment by cashpipeplusplus** [comment]
I'm not referring to the source code.  I'm referring to your publicly-available server.  Does it log our IP addresses?  Does it store any other information?  That sort of thing.

**Comment by afrokick** [comment]
All data in signaling stores In-memory. But it is open source and we don't provide it as a production-ready solution.

I have no experience in writing privacy policy.

**Comment by cashpipeplusplus** [comment]
I created a PR to add a very simple, plain language privacy policy in the server repo.  I hope it's useful!

Feel free to rewrite it in your own style or to correct anything I wrote that may be inaccurate.  But that doc is the sort of thing I would have found useful when I asked.  Thanks!

**Comment by cashpipeplusplus** [comment]
Thank you for reviewing the PR and for taking time to discuss this with me!
