### ISSUE TITLE
Offer isn't created

### ISSUE THREAD

**Issue by BioMedTech** [peers/peerjs#654]
We've stumbled upon problem with peerConnection.createOffer at `negotiater.ts:195`, which always returns undefined and causes problem with connecting, because sdp is not present in offer.
What could cause this issue?
Code we are using is pretty much the same as in example repo.

**Comment by jrowny** [comment]
Can you post some code? I've never seen that return undefined.

**Comment by afrokick** [comment]
there is no additional information about the issue, i'll close issue.
