### ISSUE TITLE
Generate key for listAllUsers() function

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [peers/peerjs#656]
Hi, 

I am using peer.js to make an AirDrop clone in Electron. So far it works, but I can't use the listAllPeers() function. Since we don't need an API key anymore, is there a way to make this function work or is it deprecated? (and no I can't use my on PeerServer)

**Comment by afrokick** [comment]
For public server we disabled it. You can use Heroku or another solution to host your own PeerServer.
