### ISSUE TITLE
Not working in Long Distance

### ISSUE THREAD

**Issue by arjun1194** [peers/peerjs#657]
I have made an application that uses peer.js i have been able to make it work within the same network. i.e. When i was checking it in  development it was working . Now in production i gave the app to a friend to test it who lives in the neighboring city, but it fails to connect or the connection is really bad.

i am getting this error

>  Uncaught (in promise) TypeError: Cannot read property 'on' of undefined at s.getMediaConnection

**Comment by jrowny** [comment]
could be that you need a turn server
