### ISSUE TITLE
New horizontally scalable peerjs compatible websocket/api server 

### ISSUE THREAD

**Issue by sumeetchhetri** [peers/peerjs#658]
Hi,

I'm the author of [ffead-cpp](https://github.com/sumeetchhetri/ffead-cpp) framework
I have added support based on the peerjs API's/websocket messages for signalling webrtc messages in the ffead-cpp server. 
The complete implementation of the webrtc signalling server can be found [here](https://github.com/sumeetchhetri/ffead-cpp/blob/master/web/peer-server/src/PeerServerController.cpp)
I have also completed the missing API functionality in peer-server in order to provide a websocket alternative to whoever needs it, more information can be found [here](https://github.com/sumeetchhetri/ffead-cpp/blob/06d28da2915d1d2d009706bf8c51baf63ed22ec5/web/peer-server/src/PeerServerController.cpp#L352)

I wanted a horizontally scalable version of peer-server for one of my use-cases and decided to implement the specification in ffead-cpp (with redis for scaling). 
Peerjs is a great freamework and a very easy to use and extend webrtc solution, thanks for the wonderful work and a great library which makes p2p video calling a breeze. My effort is in continuation to what peerjs has been doing for some time now. Hope my effort helps someone who needs a scalable signalling peerjs compatible solution.

Have currently no idea where to post this, hence posting this as an issue here.

Cheers,
Sumeet Chhetri

**Comment by olivierlemasle** [comment]
Seems great!

**Comment by afrokick** [comment]
Thanks!
