### ISSUE TITLE
PeerJS Connection has been made, but no data transfer

### ISSUE THREAD

**Issue by ihateyellow** [peers/peerjs#659]
Hi , I encountered an issue on peerjs. PeerJS Connection has been made, but no data transfer. It's completely working on internal or within the LAN . but on the other network the connection open states as "closed" . I actually follow the instruction here . https://elements.heroku.com/buttons/peers/peerjs-server

Reference : https://ibb.co/JK15r27

**Comment by ioannismihailidis** [comment]
Hi there,
I had the same issue: Local connection was working. But over a custom peer js server, which is running on aws, no data connection was possible between local pc and my smart phone (4G Connection).

After I tried the another stun and turn server (in this case a free dev account from xirsys.net) the data connection could established. In my case both devices are not running behind a symmetric NAT, so the stun server should be enough. This is just a guess, I'm not an expert on this topic.

Best regards
Janni

**Comment by ihateyellow** [comment]
Hi, @ioannismihailidis 

After using free account from https://global.xirsys.net/ . Do you establish a successful connection from local network to other network ? 

Best regards,
Jun

**Comment by ioannismihailidis** [comment]
Hi @ihateyellow ,
Yes. And I can send data from client to client.

Best wishes!

**Comment by ihateyellow** [comment]
Hi @ioannismihailidis ,

Thank you so much for giving me a hint to resolve this issue. 

It completely works but the next problem, what are the ways to optimise the bandwidth usage.  Since, peer to peer video chat consumed almost 100mb per minute  .   

Best regards,

**Comment by tiofabby** [comment]
Hello @ihateyellow , @ioannismihailidis ,
I have same issue (no data transfer in some particular cases even if users are not under a symmetric NAT) and I am wondering if what you are saying here is that adding a TURN server made it work and is the solution for this kind of issue?

If so, would you have a TURN server you would suggest to implement / use? (CoTurn for instance..?)

Thank you!!

**Comment by ioannismihailidis** [comment]
Hi @ihateyellow,
I took a look on my xirsys statistics:
![image](https://user-images.githubusercontent.com/1242010/80705079-0f2dea80-8ae6-11ea-8e15-19899219e167.png)

In my case just one client was behind a NAT. So the STUN Server was used just to get an external adresss. All traffic was transfered directly.

![image](https://user-images.githubusercontent.com/1242010/80705406-a72bd400-8ae6-11ea-9e52-cf99ceefdf2b.png)

There is a nice summary and more details on this topic (also how to set up your own stun/turn server).
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

Seems like there a lot of free stun servers out there:
https://gist.github.com/mondain/b0ec1cf5f60ae726202e

Best wishes
Janni

**Comment by afrokick** [comment]
You need to use STUN/TURN to handle NAT issues. Maybe coturn will be good for you.
