### ISSUE TITLE
Error on serving with https

### ISSUE THREAD

**Issue by DNDeveloper-s** [peers/peerjs#660]
trying to server peerjs server on the same ec2 instance on 8000 port, whereas main app is on 3000 port, using apache2 to serve
![Capture](https://user-images.githubusercontent.com/48515351/80573936-8a2bce00-8a1e-11ea-84d6-0686cd3b0c7c.PNG)

**Comment by afrokick** [comment]
it is not related to PeerJS, sorry. I have no idea about configuration apache or ec2 instance.
