### ISSUE TITLE
I recommend version 1.1.0

### ISSUE THREAD

**Issue by anonym2048** [peers/peerjs#664]
The most recent version 1.2.0 is very buggy. Don’t use it. I tried 1.2.0 and for some reason it doesn’t seem to work. It doesn’t even work on my Windows computer using Chrome or Firefox. Maybe I’ll compare the code for version 1.2.0 and 1.1.0 and I will fix the problems.

**Comment by afrokick** [comment]
You can read a changelog https://github.com/peers/peerjs/blob/master/changelog.md#120-2019-12-24 If you have any issue, please, open a new one with full description.
