### ISSUE TITLE
Does it support Samsung internet ?

### ISSUE THREAD

**Issue by wassimbj** [peers/peerjs#680]
Does th peer js support samsung internet and edge browsers ??

**Comment by Florrr** [comment]
Not sure, what "Samsung internet" is. But as long as werbtc is implemented in the browsers (which is for the latest versions of most browsers), peerjs will work.
For some configurations you might need TURN/STUN-Servers, but peerjs gives you the option to include them

**Comment by wassimbj** [comment]
Thanks,
