### ISSUE TITLE
Issues on simple-peer suggest this project is abandoned

### ISSUE THREAD

**Issue by danielcrisp** [peers/peerjs#685]
I've implemented PeerJS in a project and it seems to work quite well, however I've noticed a few issues over at https://github.com/feross/simple-peer that suggest PeerJS is an abandoned project.

Of course I can see there are now recent commits but I just wanted to clarify the status.

**Comment by KMFSousa** [comment]
I had the same question. From what I can tell it was dead at one point in time but some wonderful people have revived it. The latest PR is 3 days ago, and commits from May 2020 by @afrokick so I'd say it's pretty alive.

**Comment by afrokick** [comment]
We are welcome to any PRs & suggestions. Currently I have no much time to maintain PeerJS. But I'll try to fix any critical issues/merge RPs.

If anyone want to contribute, just rich us via Telegram channel.

**Comment by danielcrisp** [comment]
Ok, thanks for responding. That's always the challenge with open source. 

Anyway you've done a great job and it was super-easy to get the peer to peer stuff working thanks to PeerJS (and PeerJS Server). I just wanted to check the status.
