### ISSUE TITLE
Move away from `opencollective` npm package?

### ISSUE THREAD

**Issue by lazerwalker** [peers/peerjs#686]
When I include PeerJS in a client project, both GitHub's dependabot and `npm audit` warn me that there is a security issue in an upstream package: 

![Screen Shot 2020-06-16 at 7 45 19 PM](https://user-images.githubusercontent.com/821238/84839001-eb792200-b009-11ea-8e42-f97b93c4d078.png)

```
    === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ peerjs                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ peerjs > opencollective > minimist                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179
```

The security issue comes by way of the `opencollective` module you're using to prompt users to donate after installing.

As per https://github.com/opencollective/opencollective-cli/issues/17, the `opencollective` module is no longer being maintained.

One suggestion listed in there is to migrate to https://github.com/opencollective/opencollective-postinstall. Another is to get rid of your postinstall message entirely, as per Open Collective's current recommendations: https://blog.opencollective.com/beyond-post-install/

Either switching your opencollective prompt to use that alternative module, or removing your post-install Open Collective prompt entirely, means that every project that uses PeerJS will no longer receive a large not-dismissable banner every time they view their project on GitHub.

**Comment by afrokick** [comment]
Thanks! We added a Sponsor button to GitHub, so in the nearest release it will be removed

**Comment by afrokick** [comment]
Done in 1.3.0
