### ISSUE TITLE
Peer.connect can return undefined

### ISSUE THREAD

**Issue by arthuro555** [peers/peerjs#702]
Hello!
I am having a weird problem. I wrote some code that worked for me but didn't for a user. It is confusing because apparently `peer.connect` can return undefined but the doc seems to says that it doesn't.
The error:
![image](https://user-images.githubusercontent.com/19349038/87568062-58451200-c6c5-11ea-8b44-fe590f517a5b.png)
The relevant code:
```js
var peer = new Peer({debug: 1});
var connection = peer.connect(id);
connection.on("open", function() { onConnectionCallback(connection) });
```

Did I do something wrong, is the doc unclear, or is it peerjs handling the error connection reset just before incorrectly?

**Comment by ericwooley** [comment]
I'm having the same problem

Here is my code: 
```ts
const initiateConnection = (
  peer: Peer,
  personaId: string,
  myPersonaId: string,
) => {
  return new Promise((resolve, reject) => {
    console.log('initiating connection to', personaId)
    const conn = peer.connect(personaId, {
      // TODO: some kind of server signed token should be used here, to prevent impersonations
      metadata: { personaId: myPersonaId },
    })
    conn.on('open', () => resolve(conn))
    conn.on('error', (data) => {
      console.error('connectionError', data)
      conn.close()
      reject(new Error('Could not initiate connection'))
    })
  })
}
```
I'm using peerjs 1.3.1

**Comment by ericwooley** [comment]
https://github.com/peers/peerjs/blob/master/lib/peer.ts#L336

It looks like it will return undefined if the peer is disconnected. IMO this should be reflected in the types.

Ideally, it should throw an error instead of returning undefined.

**Comment by dchacke** [comment]
Any updates on this? The connection is always undefined for me, so that makes this package unusable.

**Comment by arthuro555** [comment]
For me, I wasn't having the error but a user did. After updating PeerJs and doing some other unrelated changes to the code, it just started working for that user, and he never got problems again.

**Comment by jkirsteins** [comment]
I ran into the same issue. In my case, I was passing in a custom peer ID, which contained dots (".").

Once I changed the peer ID to use "-" instead, the issue went away.

Leaving this comment in case someone else runs across the same issue.

**Comment by avszoom** [comment]
It got resolved when I used custom id - new Peer(customId, {}). Didn't worked for me when i used server generated ids. You also need to make sure socket is not getting disconnected in between.

**Comment by dhirajwarke12** [comment]
Hello all same issue are I also facing but it’s peer is undefined is resolved on my side after using  below code. After 2 seconds delay peer is ready to connect. Using this peer undefined error are not occurred please try this and let me know it’s working or not at your end.  Thanks

async function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

await sleep(2000);

const conn = peer.connect(peerId);
