### ISSUE TITLE
Cross mobile to computer or tablet isn't working.

### ISSUE THREAD

**Issue by lucastwong** [peers/peerjs#725]
Hi I'm an inventor and software developer for 4D Piano Colla (beta version).

Since today it seems that the connection between the "host" and the "peer" can only work with devices that are similar. For example computer to iPhone won't work. Computer to computer, yes. iPhone to iPhone yes. iPhone to iPad no. iPad to iPad yes. When I try to connect an iPhone to an iPad, one device shows that its joined but the other doesn't. This wasn't the case earlier this week. And I swear I didn't touch the "peerjs" part of my static webapp. Any ideas? Are there recent changes to WebRTC?

**Comment by WildHunt** [comment]
No, it works, from Safari 13.1 to iOS 12.4 works fine. Check NAT and TURN and STUN server config.

**Comment by lucastwong** [comment]
I use the Demo example from the PeerJS between my MacBook Pro and iPhone: 

https://jmcker.github.io/Peer-to-Peer-Cue-System/

It worked. So then I try to mimick/copy the code to my existing web app BELOW:

For some reason, still only my MacBook Pro can talk to my MacBook Pro. I apologize I can't paste the entire code. But what you see below is basically from the part that I am stilling debugging. I'm not using any other servers except the default one. 

Any ideas?


joining = function joinsession() {
  var enterid = window.prompt("Enter Session ID: (Note: only max. 2 players allowed)", "");
  console.log("HERE");
  if (conn) {
    conn.close();
  }
  conn = peer.connect(enterid, {
    reliable: true
  });
  conn.on('open', function() {});
  conn.on('data', function(data) {
    interpret(data);
  });
  conn.on('close', function() {});
}

function ready() {
  conn.on('data', function(data) {
    interpret(data);
  });
  conn.on('close', function() {
    conn = null;
  });
}

function initialize() {
  peer = new Peer(null, {
    debug: 2
  });
  peer.on('open', function(id) {
    if (peer.id === null) {
      peer.id = lastPeerId;
    } else {
      lastPeerId = peer.id;
    }
    theID = peer.id;
    addtips('');
  });
  peer.on('connection', function(cli) {
    if (conn && conn.open) {
      cli.on('open', function() {});
      return;
    }
    conn = cli;
  });
  peer.on('disconnected', function() {
    peer.id = lastPeerId;
    peer._lastServerId = lastPeerId;
    peer.reconnect();
  });
  peer.on('close', function() {
    console.log('Connection destroyed');
  });
  peer.on('error', function(err) {
    console.log(err);
  });
};
initialize();

**Comment by WildHunt** [comment]
```
peer = new Peer(null, {
debug: 2
});
```

Why your PeerID is null? I don't know js at all, but it's strange. Probably, you have problems with NAT, that's why u may have problems with connecting remote devices, try to add some STUN and TURN server, like below

```
var peer = new Peer({
  config: {'iceServers': [
    { url: 'stun:stun.l.google.com:19302' },
    { url: 'turn:homeo@turn.bistri.com:80', credential: 'homeo' }
  ]} /* Sample servers, please use appropriate ones */
});
```

**Comment by lucastwong** [comment]
Null means that it will take PeerJS own server. This might be stupid question as I'm not familiar with servers and stuff: how can I get a server url? Do I need to purchase it?

My program has a babylonJS wrapping on the visual and audio interface. Once I move PeerJS outside BabylonJS in global functions, I managed to get MacBook to "talk" to iPhone. However, iPad to iPhone still not luck.

**Comment by WildHunt** [comment]
URL... U mean stun server? You can find it on the web or create ur own, using PeerJS server. Try to use it without BabylonJS and add **playsinline** to ur video canvas, like

`<video id="myVideo" width="300px" playsinline autoplay muted></video>`

**Comment by lucastwong** [comment]
Thanks for your timely response! It works now.

**Comment by WildHunt** [comment]
No problem, u can close ticket
