### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Prashoon123** [peers/peerjs#738]
Failed to load resource: the server responded with a status of 404 (Not Found) peerjs/id?ts=16012175769280.5916506301104723:1 

This is the message in the console when I deploy my project. But it's working perfectly in the localhost:3000.

**Comment by verma1999** [comment]
@Prashoon123 did ur problem solved? after deploying in heroku i also getting same error.

**Comment by Prashoon123** [comment]
> @Prashoon123 did ur problem solved? after deploying in heroku i also getting same error.

No, my problem was not solved.

**Comment by Prashoon123** [comment]
I was finally able to solve the problem. I don't think it was a problem with **PeerJS**.

**Comment by ShyamKunda** [comment]
How did you solved the issue ?

**Comment by Pratyush1197** [comment]
@Prashoon123  Plz tell us how you solver.Even I am facing same issue
