### ISSUE TITLE
[question & feat] await for receiving randomized id from server

### ISSUE THREAD

**Issue by onichandame** [peers/peerjs#749]
### Problem

In the docs it says `If no ID is given, one will be generated by the brokering server.` Having done a quick test over it, I found that the process of requesting a random ID is asynchronous. But I could not find a way to await for the id to be retrieved.

### Workaround

I check the id periodically as a temporary workaround.

**Comment by arthuro555** [comment]
You can use a callback on the Peer instance:
```js
const peer = new Peer();
peer.on("open", id => {
    // Do stuff with the id
});
```
If you want to use `await`, I guess you can do something like this:
```js
const peer = new Peer();
function getID() {
    if(peer.id !== undefined) return Promise.resolve(peer.id);
    return new Promise(resolve => {
        peer.on("open", id => {
            resolve(id);
        });
    });
}
const id = await getID();
```

**Comment by onichandame** [comment]
@arthuro555 thanks. I didn't even think about the event pattern. I will try it on weekends.

**Comment by onichandame** [comment]
not using peerjs any more. closing for housekeeping
