### ISSUE TITLE
Peer constructor

### ISSUE THREAD

**Issue by rudyhadoux** [peers/peerjs#767]
Hi,

I don't understand how the Peer constructor works ? 
The ID argument is a simple string ?

I don't find information about that.

With that in an Angular App
```
import * as Peer from 'peerjs';
this.peer = new Peer();
```
it gives 
ERROR TypeError: peerjs__WEBPACK_IMPORTED_MODULE_1__ is not a constructor.

**Comment by IvanMtze** [comment]
How did you fix it?

**Comment by rudyhadoux** [comment]
import Peer from 'peerjs';
and after in the component : 
this.peer = new Peer();

**Comment by IvanMtze** [comment]
Are you using '@types/peerjs'?

**Comment by rudyhadoux** [comment]
It worked without.

**Comment by IvanMtze** [comment]
Im giving the following error:
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
Didn't you get it?

**Comment by rudyhadoux** [comment]
It worked without.
I used this example but with an other server than Meteor.
https://github.com/mikkelking/meteor-video-call
