### ISSUE TITLE
Native WebRTC errors since Chrome 89

### ISSUE THREAD

**Issue by purplegend** [peers/peerjs#803]
Since the new version of Chrome (89) i've the following:
Server on Chrome 89 - Client on Android ===> OK
Server on Chrome 89 - Client on iOS ===> err.type = "webrtc" Native WebRTC errors.

How can I solve?

**Comment by Patrick-Vogt** [comment]
The same occurs with Edge. 

Both show an error: 

An error ocurred with peer: TypeError: Attempted to assign to readonly property.

**Comment by purplegend** [comment]
I think the problem is here:
[https://bugs.chromium.org/p/webrtc/issues/detail?id=12215]

**Comment by jordanaustin** [comment]
We are having the exact same issue as you are. I filed a bug against Chromium just a few minutes ago. If you can add anything to this bug report that would be most helpful: https://bugs.chromium.org/p/chromium/issues/detail?id=1186456

**Comment by webdelin** [comment]
Thanks to Patrick-Vogt, note I unformatted peerjs and fixed the error. this variable has been overwritten {e. sdp =} that's why you get this error: TypeError: Attempted to assign to readonly property. I've tested and it also works with old versions including Firefox, Chrome, Safari and Edge. Here I have prepared a gist to download serve you.

https://gist.github.com/webdelin/cd4a4670cebd777aed453c1579034658

**Comment by fippo** [comment]
You might want to update your version of [webrtc-adapter](https://github.com/webrtchacks/adapter) from the mid-2019 one to one a newer one (above 7.6.2 which removes most of the problem in current safari).

**Comment by fippo** [comment]
you might want make sure you update to 7.7.1 published today (and that it is used by peerjs)

**Comment by jordanaustin** [comment]
Thanks @fippo I tried that and still no luck. This seems like a bug within peerjs at this point

**Comment by jordanaustin** [comment]
@webdelin thanks for the gist, and pointing me to `sdp` being overwritten.

This PSA seems to point to this exact problem: https://groups.google.com/g/discuss-webrtc/c/Zrsn2hi8FV0/m/KIbn0EZPBQAJ 

This is definitely a bug here in peerjs code

**Comment by webdelin** [comment]
here you go. Yes this works now with new and old browser versions.

**Comment by jordanaustin** [comment]
@fippo 😅  the fix is in `webrtc-adapter` as you said. Thank you! I'm going to post a PR here to pull in the latest changes to peerjs

**Comment by jordanaustin** [comment]
Hopefully #806 will get merged quickly and a patch version of `peerjs` can be released 🤞

**Comment by FeSeason** [comment]
@purplegend 

Based on this PR, an emergency version was issued, rename `peerjs-patch` 

https://www.npmjs.com/package/peerjs-patch

### Please wait for the official version if it is not urgent. !!!

**Comment by afrokick** [comment]
fixed in 1.3.2
