### ISSUE TITLE
Unable to connect to peer cloud server

### ISSUE THREAD

**Issue by jscott161** [peers/peerjs#805]
I'm getting a connection time out to the default peer cloud server.

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

https://0.peerjs.com/peerjs/id?ts=16153877619780.2194956755253794

**Comment by hjfitz** [comment]
Got a similar issue -

```
peerjs.js:55 WebSocket connection to 'wss://0.peerjs.com/peerjs?key=peerjs&id=[redacted]&token=[redacted]' failed: 
o.start @ peerjs.js:55
```

Firefox: 86.0 (64-bit)
Chromium: 89.0.4389.82
OS: Ubuntu 02.10

**Comment by vinxenz** [comment]
Same problem peerjs.min.js:52 WebSocket connection to 'wss://0.peerjs.com/peerjs?key=peerjs&id=farmaciS123456789&token=0yn60aqw597n' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by KohakuDoig** [comment]
Also having this issue. Noticed that the the examples on PeerJS are currently failing also https://peerjs.com/examples.html

**Comment by mdesilva** [comment]
I am having the same issue as well

**Comment by JonnieHedkvist** [comment]
Same here, watching

**Comment by nurainsyafinaz** [comment]
is everyone still having the problem?

**Comment by JonnieHedkvist** [comment]
Yes:
Here is the errorlog when setting debug level to 3:

peerjs.min.js:52 WebSocket connection to 'wss://0.peerjs.com/peerjs?key=peerjs&id=********&token=vjyu*****' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE

**Comment by nurainsyafinaz** [comment]
same. what can we do now? just wait?

**Comment by nurainsyafinaz** [comment]
this.peer.on('open', () => {
  });

peer are not open. so there is nothing happen

**Comment by JonnieHedkvist** [comment]
I guess one solution is to setup your own peerjs Server? 
https://github.com/peers/peerjs-server

**Comment by nurainsyafinaz** [comment]
have u successfully setup your own serve?

**Comment by JonnieHedkvist** [comment]
Nope, didn't have to until now, but will maybe have to try it tonight if this issue doesn't get resolved

**Comment by nurainsyafinaz** [comment]
okay thankyou!

**Comment by marcustrp** [comment]
Still down for me. I tried to deploy my own server to Google App Engine and got it to work, but only from localhost (which uses ws to connect to the server). From my published site, which uses wss, I get ERR_SSL_PROTOCOL_ERROR

**Comment by willemliufdmg** [comment]
I've managed to deploy it to Azure Web Apps. However I use a free instance so only get 5 ws connections. If you use a paid instance there is no cap beyond what your instance can handle.

It works with wss (secure).

**Comment by MNewbigging** [comment]
@kidandcat @afrokick @ericz @michelle is this on your radar?

**Comment by kidandcat** [comment]
The OVH data center has burnt. We are waiting for next Monday to see if they can recover PeerJS servers. If not we will setup new ones. 

https://www.datacenterdynamics.com/en/news/ovh-fire-update-four-halls-sbg1-destroyed-well-all-sbg2/

**Comment by cryptoboid** [comment]
Hi! Any updates on this?

**Comment by kidandcat** [comment]
Yes, sorry, it should be working since yesterday
