### ISSUE TITLE
Web audio api recieve

### ISSUE THREAD

**Issue by Tuner32** [peers/peerjs#812]
I just used code like below but  there are no sound. How can I solve it?

			 const audio = new Audio();
			 audio.setAttribute('controls', true);
			 audio.srcObject = stream;
			 audioContainer.appendChild(audio);
			 audio.onloadedmetadata = () => {
						const source = audioCtx.createMediaStreamSource(audio.srcObject);
						const gainNode = audioCtx.createGain();;
						audio.play();
						audio.muted = true;
						source.connect(gainNode);
						 gainNode.connect(audioCtx.destination);

			}

**Comment by DanielZambelli** [comment]
Noticed you got a `audio.muted = true;`

**Comment by Tuner32** [comment]
I used audioCtx.destination this to connected. I think it is not wrong. I just tried this based on blew link
https://stackoverflow.com/questions/24287054/chrome-wont-play-webaudio-getusermedia-via-webrtc-peer-js
