### ISSUE TITLE
API for switching streams.

### ISSUE THREAD

**Issue by michelle** [peers/peerjs#82]
Currently you can only do this by creating a new call. Not the best API experience.

**Comment by rmkjr** [comment]
Just wanted to leave a +1 bump for this feature.  I have been thinking about moving video into two one-way streams, and audio in its own two-way stream, to allow camera switching on devices that have more then one without interrupting the other device's video or the call's audio.  This still however requires the signal server to be alive as a new call for that one-way video has to be made.  If there where an API call to replace a stream video and audio tracks with out having to recall or reoffer that would makes things much cleaner, and would remove the signal server dependency when making the switch.

Thanks for all the hard work, one of my favorite libraries :+1:
