### ISSUE TITLE
How can the user connect without a stream?

### ISSUE THREAD

**Issue by smart0120** [peers/peerjs#837]
Sometimes, the user doesn't allow his/her camera and audio.
In that case, we can't get the stream and can't connect to others.

**Comment by Mohammed-Aman-Khan** [comment]
Just pass in an empty MediaStream,

When making a call,
`const call = myPeer.call(otherPeerId, new MediaStream())`

When answering a call,
`myPeer.on('call', call => {
     call.answer(new MediaStream())
})`

**Comment by smart0120** [comment]
@Mohammed-Aman-Khan, thx for your reply.
It's a good solution.

**Comment by Mohammed-Aman-Khan** [comment]
> @Mohammed-Aman-Khan, thx for your reply.
> It's a good solution.
> 
> Could you help me with [this](https://github.com/peers/peerjs/issues/841)?
> and [this one](https://github.com/peers/peerjs/issues/842)

Not sure about those, but I have similar problems when working with Video Calls in Peer.js
1. Video Call in my application works on localhost but not on any other device :-(
2. On localhost, when I test the video call using 2 different browsers, the peer who is being called, receives multiple stream, ( I use React.js and the same person's video is appearing multiple times.
3. After a successful call is connected, the video streams keep increasing in size every few seconds and in some time they are even bigger than the viewport of the screen.

Any Solutions for these will be appreciated.

**Comment by hijulien** [comment]
> 只需在错误处理代码块中传入一个空的 MediaStream，
> 
> 打电话时， `const call = myPeer.call(otherPeerId, new MediaStream())`
> 
> 接听电话时， `myPeer.on('call', call => { call.answer(new MediaStream()) })`

I followed your attempt, but I couldn't receive the stream sent by the other end. What's the matter
