### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by jennifer671** [peers/peerjs#845]
I'm using peerjs in my webRTC videoChat. when I start the demo this is the error. I have the same error on Chrome and Safari too. How can I fix this problem ? 
looking forward to someone reply.
<img width="1440" alt="Schermata 2021-05-14 alle 16 38 37" src="https://user-images.githubusercontent.com/78226051/118294679-43026500-b4db-11eb-9dce-805d16340108.png">
<img width="696" alt="Schermata 2021-05-14 alle 16 37 53" src="https://user-images.githubusercontent.com/78226051/118294693-472e8280-b4db-11eb-8c45-454ce325358d.png">

**Comment by oualid-cher** [comment]
same problem and all what i found till know is how to hide the message(go to inspect->console->settings->selected context only(enbale the box)). hope to get the solution though

**Comment by afrokick** [comment]
Could you please check the beta version? It should has a fix for it.

npm i peerjs@beta

**Comment by carliey** [comment]
have you found a solution?
