### ISSUE TITLE
Is https://0.peerjs.com down ?

### ISSUE THREAD

**Issue by ColleSerre** [peers/peerjs#851]
I've noticed that my requests to the server keep timing out. Therefore, I can't get my peerID which breaks my entire service. I'm not sure why but using gitpod doesn't seem to work either.

**Comment by htcrefactor** [comment]
Same here

**Comment by ColleSerre** [comment]
#846

**Comment by yogesh-1305** [comment]
Gitpod , self hosted servers are also not working, says: Error: Lost connection to server.

**Comment by ZeeshanAhmadKhalil** [comment]
Yes same issue for me, `peerjs cloud sevcer` just stopped working, it was working fine about 10-12 hrs ago.

**Comment by htcrefactor** [comment]
> #693

This worked for the moment, but doesn't work currently.

**Comment by kidandcat** [comment]
Contacted OVH support and it's now up.

**Comment by ian-corales** [comment]
Down again
<img width="717" alt="Screen Shot 2022-07-01 at 1 15 54 PM" src="https://user-images.githubusercontent.com/108352140/176828456-82e802b8-2a99-4b94-8c80-e8ae662875ee.png">
