### ISSUE TITLE
Is it possible to send smooth audio using peer.send()? 

### ISSUE THREAD

**Issue by crupeng-1** [peers/peerjs#867]
Hi,
I know you can create calls using peer.call(), but I want to have the possibility of manipulating the media streams, so for that I want to extract microphone audio, convert it to base64 (where it can be manipulated) and sent it using peer.send() many times a second. My current implimentation leads to understandable (barely), but very choppy audio, with echoes. If it helps, here's my code

```javascript
const audioLatency = 200;

async function startMicrophone() {
  const audioStream = await mediaDevices.getUserMedia({audio: true });
  const mediaRecorder = new MediaRecorder(audioStream);
  let chunks = [];
  mediaRecorder.ondataavailable = function(e) {
    chunks.push(e.data);
  };
  mediaRecorder.onstop = async function () {
    if (microphoneOn) {
      const audioSnapshotBlobCompressed = new Blob(chunks, {"type": "audio/ogg; codecs=opus"});
      const audioSnapshotCompressed = await blobToBase64(audioSnapshotBlobCompressed);
      for (let connection of connections) {
        connection.send([1, audioSnapshotCompressed]);
       };
     };
     chunks = [];
   };
  (async () => {
    while (true) {
      mediaRecorder.start();
      await setTimeoutSync(audioLatency);
      mediaRecorder.stop();
    };
  })();
};

```

**Comment by afrokick** [comment]
A more preferable way is sending the audio as an ArrayBuffer instead of a string via DataConnection.

Close the issue. But if you need any helps please let me know, I'll reopen it.
