### ISSUE TITLE
replaceTrack

### ISSUE THREAD

**Issue by dumshi** [peers/peerjs#870]
Simple-peer.js has this:
**peer.replaceTrack(oldTrack, newTrack, stream)**

Q. How to do same in PeerJS ?

I am trying to control the audio volume of my my localstream and send it over to peer so they don't have to deal with controlling audio levels.

I also saw this  suggestion:
**You can use replaceTrack of RTCRtpSender.
this.call.peerConnection.getSenders()[0].replaceTrack()**

Not sure how to do this following basic examples.
I checked the source code but couldn't find a way to replaceTrack.

Help!!

**Comment by dumshi** [comment]
Hmm,
I thought peer.connect and peer.call returned same object.

peer.connect is for data ( and so we can use conn.send() )

peer.call returns (on success) object which has peerConnection.getSenders()
and [0] is audio track, [1] = video track

so, we can simply do: 
var call = peer.call(id);
call.peerConnection.getSenders()[0].replaceTrack(newTrack)

I will try it out.
Hopefully will replace both audio and video track!!

WebRTC makes us think differently.

**Comment by zerosoul** [comment]
> Hmm,
> I thought peer.connect and peer.call returned same object.
> 
> peer.connect is for data ( and so we can use conn.send() )
> 
> peer.call returns (on success) object which has peerConnection.getSenders()
> and [0] is audio track, [1] = video track
> 
> so, we can simply do:
> var call = peer.call(id);
> call.peerConnection.getSenders()[0].replaceTrack(newTrack)
> 
> I will try it out.
> Hopefully will replace both audio and video track!!
> 
> WebRTC makes us think differently.

thanks! It works!

**Comment by gulabsagevadiya** [comment]
can you please tell me how to get newTrack in peerJs ?

**Comment by see7788** [comment]
琢磨很久，搞定。
const [callLog, callLogSet] = useImmer<Record<string, MediaConnection>>({})
function mediaStreamReplaceTrack(mediaStream: MediaStream) {
        const newTracks = mediaStream.getTracks()
        // Object.values(conns).forEach(({ peerConnection }) => {
        //     peerConnection.getSenders().forEach(({ replaceTrack }, i) => replaceTrack(newTracks[i]))
        // })//解构写法有坑
        Object.values(callLog).forEach(v => {
            v.peerConnection.getSenders().forEach((v1, i) => v1.replaceTrack(newTracks[i]))
        })
    }
async function mediaStreamSet(displayMediaOp?: displayMediaOp_t) {
const mediaStream = await navigator.mediaDevices.getDisplayMedia({
            audio: true,
            video: {
                frameRate: 60,
            }
        })
        mediaStreamReplaceTrack(mediaStream)
}
