### ISSUE TITLE
glitch.com example not working for different devices.

### ISSUE THREAD

**Issue by jegatheesprana** [peers/peerjs#872]
Hi, I wanted to test the working example on [https://glitch.com/~peerjs-video](https://glitch.com/~peerjs-video). It worked well in same device. (From two different taps or browsers). But when I tried to connect two different devices, it froze "with connecting to -peer-id-" message. So can't I use peer js to connect two different devices?

**Comment by afrokick** [comment]
Seems like NAT problem, so you should use a TURN server.
