### ISSUE TITLE
FYI: Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

### ISSUE THREAD

**Issue by newmediacrew** [peers/peerjs#873]
Chrome Version 92.0.4515.131 (Official Build) (x86_64) on Mac Big Sur 11.5.1

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

Note that for performance reasons, only the first access to one of the properties is shown.

**Comment by afrokick** [comment]
Thanks! In the future version we'll remove these calls
