### ISSUE TITLE
Can't play remote stream in Android Webview 92.0.4515.166

### ISSUE THREAD

**Issue by cvalerio** [peers/peerjs#881]
Hello!

I've prepared a small html file ( [peerjstest.zip](https://github.com/peers/peerjs/files/7120704/peerjstest.zip) ) for testing peerjs, that is just adapted from Get Started code.

All works like a charm on desktop environment, but I'm having issues in some mobile devices.
Specifically, here's the list of my test devices:

1) Windows PC + MS Edge + Chrome
2) Windows PC + MS Edge + Chrome
3) Samsung Tab S5e Android 11 tablet (Chrome + MS Edge + custom app with WebView 92.0.4515.166)
4) Oppo Reno4 Android 11 phone (Chrome + MS Edge + custom app with WebView 92.0.4515.166)
5) Xiaomi Redmi Note9 Android 11 phone (Chrome + MS Edge + custom app with WebView 93.0.4577.62)

All devices are up to date with system updates and on same WiFi network.
Working combination: 1 to 2, 1 to 5, 2 to 5 and viceversa
Non working combination: 1 to 3, 1 to 4, 2 to 3, 2 to 4, 3 to 5, 4 to 5 and viceversa

Expected behaviour: after inputting remote peer ID, on the remote peer the video from current device is played on video element

Current behaviour: despite WebRTC connection seems to be working ( call "stream" event is fired correctly, for what I can see), video is not played. Video element is in paused state.

On working devices combinations, video il played correctly, including from desktop to Xiaomi phone (with latest webview).

Thing is that I can't update webview on the other devices (3 and 4) for some Googl-ish reason :\

Console isn't logging any error or anything useful to debug, for what I can see.

**Comment by afrokick** [comment]
Did your try to use the TURN server? Check `Coturn`

**Comment by SujithManjavana** [comment]
Do you have all the required permissions?
`override fun onPermissionRequest(request: PermissionRequest?) {
                runOnUiThread {
                    request?.grant(request.resources)
                }
            }`

Autoplay:
`binding.webView.settings.mediaPlaybackRequiresUserGesture = false`

I had this issue too, but it is fixed after updating chrome and peerjs to the latest version.

**Comment by cvalerio** [comment]
It seems that Oppo crippled WebRTC capability in their Android 11 system image, we managed to have the devices we need downgraded to Android 10.
Closing the issue.
