### ISSUE TITLE
WebSocket connection to 'wss://peer.domain.com/peerjs?key=peerjs&id=123&token=xxx' failed.  (Error code 200)

### ISSUE THREAD

**Issue by vincentsartoko** [peers/peerjs#882]
Hey guys so I am deploying a Peer Server on a VPS. I have **domain.com** which connects to a subdomain **peer.domain.com** like so:
`const peer = new Peer(id, { host: "peer.domain.com", port: "443", path:"/", secure: true});`

The Peer Servers' code is as such:
```
const express = require('express');
const { ExpressPeerServer } = require('peer');
const app = express();
const PORT = 40000;

app.listen(PORT, () => {
  console.log(`Peer server listening on port ${PORT}...`);
});

const peerServer = ExpressPeerServer(app, { path: "/" });
app.use('/', peerServer);
app.use('/', express.static(__dirname + '/none'));
```

This peer.domain.com listens to port 40000 on my VPS, this is the apache configuration:
> ProxyPass /peerjs ws://localhosthost:40000/
> ProxyPass / http://localhost:40000/

Unfortunately, I got this error:
**WebSocket connection to 'wss://peer.domain.com/peerjs?key=peerjs&id=123&token=x0mbdqh0bfr' failed: Error during WebSocket handshake: Unexpected response code: 200**

As a side note, the domain.com is listening to port 50000, and it uses socket.io, which works fine.
If you have any suggestions please let me know :)

**Comment by leminhyen2** [comment]
Sorry for asking you, but I'm in a similar situation as you as I have a custom domain. How did you resolve your issue? Thank you
