### ISSUE TITLE
Multiple PeerServer network?

### ISSUE THREAD

**Issue by AshKmo** [peers/peerjs#885]
Is it possible to have multiple PeerServers in a network so that no matter which one you use you will always be able to connect to the same network of peers?

Example:
1. Alice connects to the PeerServer at example.1.com and receives 123abc as their peer ID
3. Bob connects to the PeerServer at example.2.com and receives 456def as their peer ID
4. Since the network supports multiple PeerServers, Alice can now connect to Bob using his peer ID, which is 123abc
5. Alice and Bob can now talk to each other

**Comment by newmediacrew** [comment]
I don't think this is possible, unless you build your own logic to implement a multiple peer network. Peerjs is nothing else then an easy solution to create a peer to peer network without you have to worry about SDP packages etc. 

Why do you want separate peer servers? If you run one by yourself it should have enough capabilities.

**Comment by afrokick** [comment]
Yeah, you should do it by yourself with custom peerjs server to supports multi server setup.
