### ISSUE TITLE
Peer connection not triggering event "open"

### ISSUE THREAD

**Issue by vincentsartoko** [peers/peerjs#886]
Hey guys, so I have a peer object, successfully connected to my VPS, but sometimes it doesn't trigger "open" event. Here i smy code snippet:

```
const id = RandomID(size=24);
const p = new Peer(id, {host: "domain.com});
p.on("open", () => console.log("Opened!");
```

Sometimes "Opened!" is printed, sometimes not, do u know why?

**Comment by Hashen110** [comment]
p.on("error", (err) => console.log(err);

use error event to check whether there is an error
