### ISSUE TITLE
Peer behind VPN not able to send messages

### ISSUE THREAD

**Issue by crosstreesuser** [peers/peerjs#888]
Hi.

First of all thank you to the people who created (and maintain) PeerJs, it really seems like a very awesome library.

I have just started to experiment with PeerJs for the first time myself and have hit an issue that I was wondering if anybody else has experienced. I have created a web app where a peer connection is established and a message is send between two devices. However when I open the web app on a device behind VPN it seems like a connection is made (connection open event is triggered and the id of the connecting peer is received) but messages cannot be send? 

Actually both devices are behind VPN but the Javascript console on the device attempting to send a message throws an error “ WebRTC: ICE failed, your TURN server appears to be broken […]”. If I turn off the VPN only on the device attempting to send a message everything works as expected.

Is there anything one can do to make a web app able to send messages also when behind a VPN? And is there any resources where I can read up on what to do (if anything)?

**Comment by maxpavlov** [comment]
In my setup, when one of the peers is connected to the internet only via OpenVPN, that peer is unable to establish direct connection with another peer on the internet, unless a valid TURN server (like coturn) is specified in the peer config. Then the relay connectivity is being established regardless of the network setup, albeit the connection is slower obviously. I suspected it could be faster if TURN is on a fast connection, but in my observations relaid connection is always slower then the direct P2P connection.

**Comment by afrokick** [comment]
Just use the TURN service
