### ISSUE TITLE
Black screen in remote video stream using peerjs Library

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#889]
Hi,

I have successfully made connection but my connection is not working sometimes. sometimes its not connecting. Its so dynamic. But even, if connected also I'm getting black video on remote side. May I know the cause or idea to resolve this issue? Kindly help on this on priority.

@afrokick @kidandcat

**Comment by ddtch** [comment]
@dackom I pointed my turn server in config but it not helped me (

**Comment by diivi** [comment]
@dackom could you provide a snippet with the Peer() constructor?

**Comment by dackom** [comment]
I gave up on peerjs, and did all in native webrtc, so I don't remember how exactly should it be in peerjs. 

But with native javascript and webrtc configuring peer connection looks like this:

```
const servers = {
  iceServers: [
    { url: "stun:stun.l.google.com:19302" },
    { url: "stun:stun1.l.google.com:19302" },
    { url: "stun:stun2.l.google.com:19302" },
    { url: "stun:stun3.l.google.com:19302" },
    { url: "stun:stun4.l.google.com:19302" },
    {
      url: "turn:YOURTURNSERVER.com",
      credential: "CREDENTIAL",
      username: "USERNAME",
    },
  ],
};


const pc = new RTCPeerConnection(servers);
```

Keep in mind that you need to find one or more turn servers, and to change them in config.

**Comment by xandao6** [comment]
It got this problem a while ago, It's happening because of the Turn server. 
I solved it with a paid ice server: https://xirsys.com/
I'm going to use this one until my own ice server is ready.

**Comment by ddtch** [comment]
@xandao6  I also used this service and yes it helped
