### ISSUE TITLE
PeerJs call on stream function not working on safari iOS

### ISSUE THREAD

**Issue by deeb-looper** [peers/peerjs#893]
![onstream](https://user-images.githubusercontent.com/89902221/140404638-22ba71c7-c70c-45d7-b0de-3ed127790c17.png)

Works fine on chrome mobile and PC. 
But does not work on the iOS Safari browser does not even log the `connect to new user` 

Does somebody have any idea or that can help me with this problem?

Really stuck on this part.

**Comment by ddtch** [comment]
Even on Android, and in Chrome, I see incoming stream but when I apply it on `<video>` tag, it doesn't show ((

**Comment by rushglen** [comment]
I have a similar problem: works fine on chrome mobile and PC but not iOS Safari.
Have you tried a data connection? dataConnection = peer.connect(id, [options]); 
With Safari the options.serialization should be "json" (default is binary).

**Comment by ddtch** [comment]
@deeb-looper So for me I solved the problem. It depends on how you define `call` variable. And it works in safari/chrome/mozilla/ios/android browsers

**Comment by Mohagames205** [comment]
@ddtch how should you define the call variable? Because iirc you don't even have to define it.

**Comment by ddtch** [comment]
I have global variable in my service class like
```
clientsCall: MediaConnection;

...
this.peer.on('call', async (mediaCon) => {
	console.log('incoming call from CLIENT');
	console.log(mediaCon);

	// Allow only a single media
	if (this.clientsCall && this.clientsCall.open) {
		mediaCon.close();
	}

        // i listen the call here but it could be also used later
	mediaCon.on('stream', (streamFromClient: MediaStream) => {
		console.log('stream from client ', streamFromClient);
	});
	mediaCon.on('close', () => {
		console.log('client closed connections');
	});
	this.clientsCall = mediaCon;
});

After it you can also use 

```
this.clientsCall.answer(stream);
// or 
this.clietnsCall.on('stream', () => {//do some});
```

```

**Comment by Mohagames205** [comment]
I actually fixed my issue by updating to the latest version of peerJS which
is 1.3.2. The version provided on the website is outdated.

**Comment by afrokick** [comment]
@deeb-looper try to use the latest version `npm i peerjs@1.3.2`.

If the problem still exists, we will reopen the issue.

**Comment by MikeyA-yo** [comment]
The problem exists for me on version 1.5.4
