### ISSUE TITLE
Peerjs for Deploy

### ISSUE THREAD

**Issue by mn9142001** [peers/peerjs#895]
I'm new to RTC protocols, can peerjs be used to host 10k users? Just one is streaming and rest are receiving the stream, is it done by connecting them to the same peer of streamer or i should make a peer for each user and another peer for the streamer
A streaming
B join, A has peer, b makes one they both connect
C join the room, A creates another peer and c creates new one

Or A will only use one peer?
Should it be host on a paid server or the free one is enough, it doesn't affect the website host transfer or storage does it?

**Comment by afrokick** [comment]
No sorry, for 10k your should use something more powerful like MediaSoup.
