### ISSUE TITLE
closing connection to specific peer id without destroying the peer connection

### ISSUE THREAD

**Issue by Hretic** [peers/peerjs#900]
im trying to write a random p2p video chat app , 2 online users are selected randomly and they start to chat (with option to invite a friend so it might be 3 person in the chat total ) ... i want them to be able to skip their partner and chat with another random user instead  if they want

so here is the problem , when users press the skip chat button and basically wants to chat with another online user instead of the current one   ,  my nodejs server  will emit to both parties that the chat is over , both users will receive `remove_peer` from server with the peer_id of the other user 

    io.on('remove_peer' , function(data){

        console.log(`removing peer ${data.remote_peer_id}`);
    })

and they will receive a different user peer_id  (new `incoming_chat` event )

im very new to peerjs and webrtc in general , but i assume somehow i need to close the peer connection between these two users ... the current code will automatically add the new incoming user to the chat that's not a problem ... i just dont know how to remove the old (skipped)peer 

there is a `peer.destroy()` method in the documentation 

but it seems to be destroying the peer connection all together , which is not good cuz i need the peer connection for the next incoming chat also i dont want to lose the connection to the 3rd person (invited guest) , i just need to remove a specific peer_id from my connection something like

    peer.closeRemotePeer( remote_peer_id) 

in order to stop the current connection from wasting resources and bandwidth   , or maybe it's not important and just removing their stream and adding new user stream would be ok (which i doubt ) ... maybe i need to generate new peer connection all together after each chat is ending ?

im very lost and any help is appreciated

**Comment by mariavaghani** [comment]
Have you tried closing the call with that peer? When you open connection and use call.answer(), you save the call in an object, and use call.close when you want to cut the connection

**Comment by afrokick** [comment]
Just call `call.close()` or `connection.close()` to cleanup resources for it. You can reuse Peer object as much as possible. The Peer object represents a connection from You browser to server and it can handle more than one call at once.

**Comment by marcelocassar** [comment]
afrokick, but when i use call.close(), in peer.connections, still existis the id of a quiter participant.
