### ISSUE TITLE
Option for video codecs or quality settings?

### ISSUE THREAD

**Issue by lslzl3000** [peers/peerjs#901]
Is there an api / option to set preferred video codecs, e.g. vp9, av1 ? and maybe set video quality as well

If not, we should do that, vp8/h264 is not a good choice

**Comment by afrokick** [comment]
You can provide `sdpTransform` to call/answer function to modify `sdp` message:

https://github.com/peers/peerjs/blob/e4446018169962fb529b7fd30b5a30c045817da2/lib/negotiator.ts#L197
https://github.com/peers/peerjs/blob/e4446018169962fb529b7fd30b5a30c045817da2/lib/negotiator.ts#L254

We use `sdp-transform` library to manipulate on the `sdp` string. So, it is our utils method:

```typescript
import transform, { SessionDescription } from 'sdp-transform';

export const transformSdp = (sdp: string): string => {
  const parsed = transform.parse(sdp);

  parsed.media.forEach(media => {
    if (media.type === 'audio') {
      transformAudio(media);
    } else {
      transformVideo(media);
    }
  });

  return transform.write(parsed);
};

const getPayloads = (payloads: string | undefined, codecs: number[]) => {
  return payloads
    ?.split(' ')
    .filter(value => codecs.includes(+value))
    .join(' ');
};

const transformAudio = (media: SessionDescription['media'][0]): void => {
  /*
   * 111 - opus 48000, encoding - 2
   * 103 - isac 16000
   * 63 - red 48000, encoding - 2
   */

  const audioCodecs = [111, 103, 63];

  media.payloads = getPayloads(media.payloads, audioCodecs);
  media.rtp = media.rtp.filter(({ payload }) => audioCodecs.includes(payload));
};

const transformVideo = (media: SessionDescription['media'][0]): void => {
  /*
   * 96 - VP8
   * 98 - VP9
   * 102 - H264
   */
  const videoCodecs = [96, 97];

  media.payloads = getPayloads(media.payloads, videoCodecs);
  media.rtp = media.rtp.filter(({ payload }) => videoCodecs.includes(payload));
  media.rtcpFb = media.rtcpFb?.filter(({ payload }) => videoCodecs.includes(payload));
  media.fmtp = media.fmtp.filter(({ config }) => videoCodecs.includes(Number(config.split('=')[1])));
};

```

And the usage:
```typescript
...

this.mediaConnection.answer(localStream, { sdpTransform: transformSdp })

...
```

**Comment by SujithManjavana** [comment]
@afrokick Could you please help me with this? I'm new to webRTC and peer.js. I want to modify SDP to enable DTX audio for my native android app(https://www.youtube.com/watch?v=JVAj7TawpGs). Currently, I'm facing a 1-6 seconds delay in the audio calls. I also want to know the best constraint values (Audio & Video) to minimize network latency without compromising a lot on quality.

Here is my code,
`let localStream;
function listen() {
  peer.on("call", (call) => {
    navigator.mediaDevices
      .getUserMedia(constraints)
      .then(function (stream) {
        localVideo.srcObject = stream;
        localStream = stream;
        call.answer(stream);
        call.on("stream", (remoteStream) => {
          Android.onPeerStream();
          remoteVideo.srcObject = remoteStream;
        });
      })
      .catch(function (err) {
        Android.logEvent("getUserMedia error: " + err);
      });
  });
}

function startCall(otherUserId) {
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then(function (stream) {
      localVideo.srcObject = stream;
      localStream = stream;
      const call = peer.call(otherUserId, stream);
      call.on("stream", (remoteStream) => {
        Android.onPeerStream();
        remoteVideo.srcObject = remoteStream;
      });
    })
    .catch(function (err) {
      Android.logEvent("getUserMedia error: " + err);
    });
}`
Thank you.

**Comment by timotheeg** [comment]
Thanks for that @afrokick ! But so what is codec `97`? And does that mean that constraining the video codecs to `[96, 97]` automatically make the video quality better?

If yes why doesn't peerjs automatically pick the best codec offered?

**Comment by ThanhQuang1410** [comment]
Hi @afrokick . I have tried your solution but it ends up I can not receive any call. Is there any update on this? Here is my code:
`peer.on('open', async function (id) {
      console.log('Connected to ' + id)
      const conn = peer.connect('giam-sat-vien');
      conn.on('open', async function () {
        let captureStream = await me.captureScreen();
        if (captureStream) {
          peer.call('giam-sat-vien', captureStream, { sdpTransform: (sdp) => transformSdp(sdp) });
        }
      })
    })`

**Comment by Hinashou** [comment]
@afrokick 
Is it possible to use this since since it is supported by browsers now? If so, where would this fit in the peerjs flow?
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences
