### ISSUE TITLE
Create conference

### ISSUE THREAD

**Issue by A2DNEW** [peers/peerjs#902]
I use peerjs for video call
My conference work for 5 users
But after add another user to conference ( up 10 users ), video calls are hanging and bad rendering!
How I can fix it for 10 users?
My server:
8gig ram
cpu 2vCore

**Comment by newmediacrew** [comment]
Hello,

The problem is not the server. But the individual connection used. If you have a conference with 10 people. Someone must have sufficient bandwidth to actually broadcast the video 10 times to each other client. The server is only a broker to tell what connection should join what video call.

**Comment by A2DNEW** [comment]
> Hello,
> 
> The problem is not the server. But the individual connection used. If you have a conference with 10 people. Someone must have sufficient bandwidth to actually broadcast the video 10 times to each other client. The server is only a broker to tell what connection should join what video call. For example a 2 core with 2 gig's of ram should be enough to start a video conversation with 10 people in one conference.
> 
> Of you are looking for some scalability, as I am at the moment. Project janus looks promising. https://janus.conf.meetecho.com

Thank you
So, Ho can I fix it?
I want to create video conference like google meet for 10 users.

**Comment by afrokick** [comment]
You should adopt you quality/bandwidth with sdp message. Take a look at this https://github.com/peers/peerjs/issues/901#issuecomment-1046230997
