### ISSUE TITLE
Canvas capture stream

### ISSUE THREAD

**Issue by tienbui2307** [peers/peerjs#903]
I have a problem with stream of captureStream() in canvas. When i use captureStream() at present page, it's ok. But when i transfer to other peer, there's nothing happen. I saw that CanvasCaptureMediaStreamTrack was changed to MediaStreamTrack after transfer to other peer. So is there any solution for this? Thanks.

**Comment by afrokick** [comment]
Sorry, but it looks like not peerjs issue but browser specific. I'll close the issue. But if anyone has a solution, please, share with us.
