### ISSUE TITLE
peerjs.min.js:52 WebSocket connection to 'ws://localhost:3000/peerjs/peerjs?key=peerjs&id=APPID&token=TOKEN' failed:

### ISSUE THREAD

**Issue by ArhumTheDeveloper** [peers/peerjs#905]
peerjs.min.js:52 WebSocket connection to 'ws://localhost:3000/peerjs/peerjs?key=peerjs&id=APPID&token=TOKEN' failed: 
There is NO ERROR at the 'failed:' area
Using v1.3.1

Script.js

`const socket = io("http://localhost:3000");
const videoGrid = document.getElementById("video-grid");
const myVideo = document.createElement("video");
const showChat = document.querySelector("#showChat");
const backBtn = document.querySelector(".header__back");
myVideo.muted = true;
const user = prompt("Enter your name");

var peer = new Peer(undefined, {
  path: "/",
  host: "localhost",
  port: "3001",
});

navigator.mediaDevices
  .getUserMedia({
    audio: true,
    video: true,
  })

  .then((stream) => {
    let myVideoStream
    myVideoStream = stream;
    addVideoStream(myVideo, stream);

    peer.on("call", (call) => {
      call.answer(stream);
      const video = document.createElement("video");
      call.on("stream", (userVideoStream) => {
        addVideoStream(video, userVideoStream);
      });

    });

    socket.on("user-connected", (userId) => {
      connectToNewUser(userId, stream);
    });

  });

const connectToNewUser = (userId, stream) => {
  const call = peer.call(userId, stream);
  const video = document.createElement("video");
  call.on("stream", (userVideoStream) => {
    addVideoStream(video, userVideoStream);

  });

};

peer.on("open", (id) => {
  socket.emit("join-room", ROOM_ID, id, user);
});

const addVideoStream = (video, stream) => {
  video.srcObject = stream;
  video.addEventListener("loadedmetadata", () => {
    video.play();
    videoGrid.append(video);

  });
};`

**Comment by afrokick** [comment]
Please, reopen if it still exists

**Comment by ArhumTheDeveloper** [comment]
Ok, I will
