### ISSUE TITLE
Peer js call.on('stream', ...) is undefined after calling peer.call 

### ISSUE THREAD

**Issue by harsh317** [peers/peerjs#907]
I am making a group video call app and I have been stuck here for a long time.

See like I have this small function:

```
  const connectToNewUser = (id, stream) => {
    const call = peerServer.call(id, stream);
    call.on("stream", (userVideoStream) => {
      if (userVideoStream) {
        setremoteStream(...remoteStream, userVideoStream);
      }
    });
  };
```

And It is simply being called here:

```
    socket.on("user-connected", (id) => {
      connectToNewUser(id, MyStream);
    });
```

And listening for the event as follows:
```
    peerServer.on("call", (call) => {
      call.answer(MyStream);
      call.on("stream", (remoteUserStream) => {
        setstreams(...streams, remoteUserStream);
      });
    });
```

But I am getting this error:

### **ERROR [TypeError: undefined is not an object (evaluating 'call.on')]**
What Should I do? I have made a same app in web with the code exactly the same as this but then y I am getting this error?

**Comment by afrokick** [comment]
Please, provide a test repo to reproduce your issue. I close the issue. If it still exists just let me known, I'll reopen it.

**Comment by Naveen562117** [comment]
Hi , 
` socket.on("init-call", (peerId) => {
    try {
      if (peerId) {
        var call = peerServer.call(peerId, mystream)
        call.on("stream", (remoteStream) => {
          setRemoteStream(remoteStream)
        });
      }
    } catch (error) {
      console.log('Calling error', error);
    }
  })`

this is my code and 
 LOG  Calling error [TypeError: undefined is not an object (evaluating 'call.on')]
 this is the error I am getting on catch block 


any help ??

**Comment by NumairAwan** [comment]
@harsh317 getting the same issue, how did you fixed it?

**Comment by angelopedroso** [comment]
> @harsh317 getting the same issue, how did you fixed it?

Do you find?
