### ISSUE TITLE
got unexpected 404 response

### ISSUE THREAD

**Issue by arcahyadi** [peers/peerjs#911]
Could not read source map for https://unpkg.com/@popperjs/core@2: Unexpected 404 response from https://unpkg.com/@popperjs/popper.min.js.map: Cannot find package @popperjs/popper.min.js.map@latest
Could not read source map for https://unpkg.com/tippy.js@6: Unexpected 404 response from https://unpkg.com/tippy-bundle.umd.min.js.map: Cannot find package tippy-bundle.umd.min.js.map@latest

**Comment by arcahyadi** [comment]
![image](https://user-images.githubusercontent.com/76746019/146334658-2d806d43-37cb-44b3-a72f-a3eaad9c5f1c.png)
![image](https://user-images.githubusercontent.com/76746019/146334695-566c4cbb-3d43-4b55-8ecb-748cc35b0b61.png)

**Comment by PoppyDev** [comment]
Hi @arcahyadi did you find a solution for this? I am getting this error when using tippy.js in Oxygen Builder.

Can't find a solution for these warning. Mine are exactly the same. Oddly enough the tool tip function still works as expected.

Thanks
