### ISSUE TITLE
this.mediaCall.on('stream', (remoteStream) => {this.remoteStreamBs.next(remoteStream);}); is only being called first time in safari, other browsers are working fine.

### ISSUE THREAD

**Issue by Koushik-Sarker-Seemanto** [peers/peerjs#921]
The code is working in all browser, only safari mac and safari ios is not working. 

in safari first time works,

       this.mediaCall.on('stream',
        (remoteStream) => {
          console.log('================> establishMediaCall ON_STREAM');
          this.remoteStreamBs.next(remoteStream);
        });
 or,
 
        call.on('stream', (remoteStream) => {
          console.log('================> enableCallAnswer ON_STREAM');
          this.remoteStreamBs.next(remoteStream);
        });

is being called and remote stream is coming. but, in second time when i am without refreshing the page trying to call, it shows black screen.

### But the interesting fact, when i am running in local it is also working in safari.

same as this issue may be: https://github.com/peers/peerjs/issues/893#issue-1045115190
Please somebody help me. I tried a lot, but it is not working in any way.

<img width="855" alt="Screenshot 2022-02-07 at 8 47 50 PM" src="https://user-images.githubusercontent.com/43277186/152812151-d7c5cc9c-af6f-4a1a-ba49-7a459dba91f2.png">
<img width="701" alt="Screenshot 2022-02-07 at 8 48 41 PM" src="https://user-images.githubusercontent.com/43277186/152812204-0876249d-348e-4b9d-a686-34a725d6a1d9.png">
<img width="673" alt="Screenshot 2022-02-07 at 8 51 02 PM" src="https://user-images.githubusercontent.com/43277186/152812246-16185865-7cf2-4477-bfdf-147cb0886165.png">
<img width="645" alt="Screenshot 2022-02-07 at 8 52 28 PM" src="https://user-images.githubusercontent.com/43277186/152812290-a6eae09c-c243-4086-9ae4-46cbdd3c91d7.png">
<img width="500" alt="Screenshot 2022-02-07 at 8 52 53 PM" src="https://user-images.githubusercontent.com/43277186/152812328-e25b7734-60b8-49ad-84fb-fb8d3118c9f4.png">

**Comment by pepijndevos** [comment]
no

**Comment by Koushik-Sarker-Seemanto** [comment]
> no

What is the issue here? What approach should i try?

**Comment by fresheneesz** [comment]
I think [pepijndevos](https://github.com/pepijndevos) might be reacting to confusion around why you're asking us to take a look. I'm not a maintainer of this library, nor an active user of it. I assume something similar might be true of pepijndevos.

**Comment by afrokick** [comment]
@Koushik-Sarker-Seemanto which version of `peerjs` are you using? Please, provide working example from jsfiddle or similar service to reproduce your issue.
