### ISSUE TITLE
Replace Track or disconnect call and reconnect call not finding proper solution or function for this

### ISSUE THREAD

**Issue by gulabsagevadiya** [peers/peerjs#934]
```
function changeCamera(isFrontCamera, isAudio) {
    try {
        var thisUserId = peer.id
        var mOtherUserId = call.peer
        try {
            call.close();
        } catch(error) {
            Android.onError(err)
        }
        call = undefined;
        navigator.getUserMedia({
                audio: true,
                video: getVideoSelection(isFrontCamera),
            }, (stream) => {
                localVideo.srcObject = stream
                localStream = stream
                localStream.getAudioTracks()[0].enabled = isAudio == "true"
                call = peer.call(mOtherUserId, stream)
                call.on('stream', (remoteStream) => {
                    remoteVideo.srcObject = remoteStream
                    remoteVideo.className = "primary-video"
                    localVideo.className = "secondary-video"
                })
        })

    } catch(err) {
        Android.onError(err)
    }
}
```

I have tried to disconnect the call and reconnect call again but in android 9 and android 10 don't know why the second call is not working also not found any track replacement method to change video source from android side

**Comment by gulabsagevadiya** [comment]
[calljs.txt](https://github.com/peers/peerjs/files/8259768/calljs.txt)

here is my call.js file which i am using in android studio for video call using peerjs

please let me know if something can be changed or implementeded

**Comment by gulabsagevadiya** [comment]
somehow I have managed to disconnect call and reconnect with the new media stream but still, I am looking to switch the media stream without cutting call if this is possible.

also If anyone can answer me about how many calls can answer by one peer at once 
for this, my meaning is I want to stream media from one peer to other N numbers of peers by simply calling them with streamer peer and another peers will answer with empty stream

**Comment by andrecj93** [comment]
If you store each peer call connection you can then get the peerConnection and use the method getSenders(). For each sender you should use replaceTrack().

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getSenders
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

You can also get the peer connection by storing the peer call reference when you receive the stream of the other person.

**Comment by gulabsagevadiya** [comment]
there is no information available that how to get peerConnection from the call object there is info that how to get peerConnection from DataConnection

**Comment by gulabsagevadiya** [comment]
> If you store each peer call connection you can then get the peerConnection and use the method getSenders(). For each sender you should use replaceTrack().
> 
> https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getSenders https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack
> 
> You can also get the peer connection by storing the peer call reference when you receive the stream of the other person.

Can you please help me how to get peerConnection Object from Call which I am saving already

**Comment by gulabsagevadiya** [comment]
`call.peerConnection.getSenders()[1].replaceTrack(localStream.getVideoTracks()[0])`

Yes this worked finally....

**Comment by andrecj93** [comment]
Yes, that is it, dont forget that replaceTrack is a Promise. You should also check the sender track. Here's how I do it.

```
    async replaceStream = (mediaStream) => {
      this.calls.forEach((call) => {
        const peerConnection = call.peerConnection;
        if (peerConnection) {
          for (const sender of peerConnection.getSenders()) {
            if (sender.track.kind == "audio") {
              if (mediaStream.getAudioTracks().length > 0) {
                sender.replaceTrack(mediaStream.getAudioTracks()[0]);
              }
            }
            if (sender.track.kind == "video") {
              if (mediaStream.getVideoTracks().length > 0) {
                sender.replaceTrack(mediaStream.getVideoTracks()[0]);
              }
            }
          }
        }
      });
    }
```

**Comment by rishabhjainfinal** [comment]
> somehow I have managed to disconnect call and reconnect with the new media stream but still, I am looking to switch the media stream without cutting call if this is possible.
> 
> also If anyone can answer me about how many calls can answer by one peer at once for this, my meaning is I want to stream media from one peer to other N numbers of peers by simply calling them with streamer peer and another peers will answer with empty stream

can you please share how you achieve that

**Comment by see7788** [comment]
琢磨很久，搞定。
const [callLog, callLogSet] = useImmer<Record<string, MediaConnection>>({})
function mediaStreamReplaceTrack(mediaStream: MediaStream) {
        const newTracks = mediaStream.getTracks()
        // Object.values(conns).forEach(({ peerConnection }) => {
        //     peerConnection.getSenders().forEach(({ replaceTrack }, i) => replaceTrack(newTracks[i]))
        // })//解构写法有坑
        Object.values(callLog).forEach(v => {
            v.peerConnection.getSenders().forEach((v1, i) => v1.replaceTrack(newTracks[i]))
        })
    }
async function mediaStreamSet(displayMediaOp?: displayMediaOp_t) {
const mediaStream = await navigator.mediaDevices.getDisplayMedia({
            audio: true,
            video: {
                frameRate: 60,
            }
        })
        mediaStreamReplaceTrack(mediaStream)
}
