### ISSUE TITLE
Do I need a turn/stun/ice server in order to use peerjs correctly if I'm using peerjs-server?

### ISSUE THREAD

**Issue by eko234** [peers/peerjs#935]

**Comment by SinisterSpatula** [comment]
No, not usually.  You only need ice/stun/turn servers if you have some client devices that aren't able to connect the normal way, if they are behind certain restrictive NAT firewalls or using certain VPN's.  It should be pretty rare to need those additional servers.

**Comment by jonasgloning** [comment]
No, probably not.

`peerjs-server` is an ICE relay server.
STUN is covered by a public google instance https://github.com/peers/peerjs/blob/cfc37c7988d8ef3d2c1d7b6123562dd2af59defc/lib/util.ts#L7
We do not offer a TURN server for cost reasons, but that is rarely needed anyway. Monitor your user base for connection failures. If it is necessary you can still roll your own.
