### ISSUE TITLE
peerjs cdn Error: Could not get an ID from the server

### ISSUE THREAD

**Issue by Rajcbe** [peers/peerjs#937]
Using Peerjs cdn.It stopped working suddenly from today in my project.Cannot generate any id using it.

**Comment by xerosanyam** [comment]
+1, no error, no logs. just stops working

same for you @Rajcbe ?

**Comment by Rajcbe** [comment]
@xerosanyam yes

**Comment by xerosanyam** [comment]
@Rajcbe but this one https://glitch.com/~peerjs-video seems to work fine 🤔

**Comment by Rajcbe** [comment]
@xerosanyam for above application seperate node server is configured.But i need to use cdn peerjs cloud server

**Comment by andrecj93** [comment]
Hello, I have the same problem. Any ideas when will this be available?

**Comment by topheman** [comment]
I have the same problem: https://topheman.github.io/webrtc-experiments/

**Comment by SinisterSpatula** [comment]
+1 also seeing a problem with the 0.peerjs.com server.  We're unable to get an ID.  The peer-to-peer cue system demo also shows "unable to get ID".

**Comment by marcomow** [comment]
I solved hosting my own service, it's unexpectedly easy!

Just deploy using this button https://elements.heroku.com/buttons/peers/peerjs-server, it's really straight-forward. Once the deployment is running, use the app's url in the config like this

```javascript
const myPeer = new Peer( {
     secure:true,
     host: 'my-peerjs-server-name.herokuapp.com', // change here the herokuapp name
     port: 443
})
```

And everything just works!

**Comment by julienreszka** [comment]
@marcomow Thank you it was surprisingly easy indeed. I could do it in less than 10 minutes.

**Comment by kunalkashyap855** [comment]
Thank you for the alternative @marcomow. I'd still like to know if anyone knows till when we can expect `0.peerjs.com` server to be back up?

**Comment by kidandcat** [comment]
Hi guys, public server is down, it looks like it has been cracked into by a botnet by looking at the resource monitors. It just need to be reinstalled and configured with a PeerServer instance.

I'm not sure I can spend more time to this project, so I think this is a good chance to let the maintenance of this ecosystem to other person. I'll open an issue to search for volunteers.

**Comment by andrecj93** [comment]
Well this made me do something that I should have done it in a while. And that is to configure my own PeerServer instance. Thanks for your work.

**Comment by I-Chandana** [comment]
Thank You  @marcomow  
It works for me.

**Comment by Rajcbe** [comment]
Thank You @marcomow .Working after creating separate server instance

**Comment by kenfouo** [comment]
that's it I modified my client and it works.

my client:

_FM_Peer_Object = new Peer({
secure : true,
host : 'myserve.com/', // remove https://
port : port
});

bingo!!!!

**Comment by jsProj** [comment]
Yeah had to host my own heroku instance, kinda fucky altogether, but it works for now, hopefully someone can take over the project and get 0.peerjs.com working again

**Comment by ClintonWeeYuan** [comment]
Hi everyone. For some reason. My own peer server works perfectly when run on the localhost. However, once I launch to herokuapp, it fails to connect. I get the following error message.

![image](https://user-images.githubusercontent.com/26379973/160963547-3dad9e4e-0183-46f8-97ca-01375e0526b9.png)


I suspect it has something to do with how i call the server in my client:
const peer = new Peer(userId, {
          host: 'videocall-peer-server.herokuapp.com',
          port: 9000,
          debug: 2,
          path: '/peerjs/myapp'
        });

**Comment by julienreszka** [comment]
@ClintonWeeYuan you also need to pass an array of ice servers (stun and turn servers) in your config option.

https://peerjs.com/docs.html#peer-options-config

**Comment by ClintonWeeYuan** [comment]
@julienreszka Thanks for that. But does that mean I need to set up my own STUN & TURN servers?

**Comment by SinisterSpatula** [comment]
@ClintonWeeYuan try removing the path option, and change port to 443.  That is how mine is and it works.  I also do no use any ice/stun servers it's working for me on heroku without those, but that probably will depend on your client devices and if they are behind restrictive NAT firewalls/vpns etc.

**Comment by ClintonWeeYuan** [comment]
@SinisterSpatula  Thanks for that. However, it still doesn't work. I think the path option is correct, because when I run the server on localhost it works, it just doesn't work when i run the server on herokuapp. How did you set up your peer server?

**Comment by SinisterSpatula** [comment]
@ClintonWeeYuan I did it exactly how Marcomow says above: https://github.com/peers/peerjs/issues/937#issuecomment-1077712367 no path needs to be specified, set secure to true and port to 443 and just single click deploy on heroku, should be easy as that.

**Comment by ClintonWeeYuan** [comment]
@SinisterSpatula Ohh yes it works now! Thank you =)

**Comment by timotheeg** [comment]
> PD: Expect maybe a couple of days of downtime, as I want to take advantage of the issue to move the servers to the new maintaner's preferred location.

Hi there 👋 , so any update as to when `0.peerjs.com` might be back?

**Comment by jsProj** [comment]
I have an alternative to 0.peer.js, ```js
const serverOptions = {
	host: "peerturn.herokuapp.com",
	path: "/",
	port: 443,
	secure: true,
};
```

**Comment by timotheeg** [comment]
That works! Thanks @jsProj 🙏 

My project is very *very* light, so I don't expect to create much load onto your server at all, and I will shift to the official server when it is back up.

**Comment by jonasgloning** [comment]
> Hi there 👋 , so any update as to when `0.peerjs.com` might be back?

The new server is already up and running. But we are still in the process of transferring the domain. This may take a few days, as there seems to be no early release option at the current registrar OVH.
We started on Tuesday, maybe two more days? I'm afraid we can't do anything to speed it up, and there's no reliable ETA from the registrars.
