### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by kidandcat** [peers/peerjs#938]
We are looking for maintainers for the peerjs services, they are, the github repo, the open collective org, and the public PeerServer + the website.

Usually, the open collective budget is more than enough to pay for the servers and domain, so it is just a matter of management (paying the servers, sending invoices to open collective, etc)

If you want to step in and take it, just comment here or contact me by email.

PD: This is more of a management role (only take care of website and server availability, and pay and send bills to opencollective monthly), the development is already being driven by @afrokick 
Also I need yet to confirm with him.

**Comment by kidandcat** [comment]
We are still looking for someone to get over the project.

**Comment by kidandcat** [comment]
Bump

**Comment by jonasgloning** [comment]
I've sent you an email, @kidandcat

**Comment by digitaltim-de** [comment]
I can sponsor you, if it helps.

**Comment by jonasgloning** [comment]
I guess we can close this. I’ve joined the team. Excited for the journey.
If there are more people who would like to take a more active role, feel free to comment here.
