### ISSUE TITLE
"peerjs: command not found" issue

### ISSUE THREAD

**Issue by greybuz** [peers/peerjs#947]
I followed the instructions listed on your page:
 npm install peer -g
peerjs --port 9000 --key peerjs --path /myapp

and i keep getting an "peerjs: command not found" error.
How do I fix this? What am I doing wrong?

**Comment by jonasgloning** [comment]
This is not an issue with PeerJS. Looks like the global npm modules directory is not in your `PATH`.

My guess: you're running windows and missed the "add to your PATH" check mark in the Node installer?

This out of scope for the project, but you may find a solution on Stackoverflow or by reinstalling the package. Good Luck.
