### ISSUE TITLE
v1.4.2: Cannot read properties of undefined (reading 'browser')

### ISSUE THREAD

**Issue by jonasgloning** [peers/peerjs#954]
I have upgraded peerjs to version 1.4.2 then another issue hits me: 

Uncaught TypeError: Cannot read properties of undefined (reading 'browser')
    at class_1.push../node_modules/peerjs/dist/bundler.mjs.class_1.getBrowser (supports.ts:32:1)
    at new Util (util.ts:51:1)
    at Module../node_modules/peerjs/dist/bundler.mjs (util.ts:182:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)

_Originally posted by @ckqbao in https://github.com/peers/peerjs/issues/761#issuecomment-1125798535_

**Comment by ckqbao** [comment]
@jonasgloning 

The envinfo is: 
`
## System:
 - OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
 - CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
 - Memory: 16.35 GB / 24.93 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
 - Yarn: 1.22.18 - ~/.yarn/bin/yarn
 - npm: 8.9.0 - ~/.nvm/versions/node/v14.18.0/bin/npm
## Browsers:
 - Chrome: 99.0.4844.74
## npmPackages:
 - peerjs: ^1.4.3 => 1.4.3
 - react: ^17.0.2 => 17.0.2
 - typescript: ^4.5.2 => 4.6.4
`
I use wsl2

Peerjs is imported by using es6 syntax: import { Peer } from 'peerjs'

My package.json:
`
{
  "name": "web_react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@date-io/moment": "^2.11.0",
    "@devbookhq/splitter": "^1.3.2",
    "@devexpress/dx-react-core": "^3.0.2",
    "@devexpress/dx-react-scheduler": "^3.0.2",
    "@devexpress/dx-react-scheduler-material-ui": "^3.0.2",
    "@emotion/react": "^11.7.0",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.2.1",
    "@mui/lab": "^5.0.0-alpha.59",
    "@mui/material": "^5.2.3",
    "@mui/system": "^5.6.1",
    "@react-keycloak/web": "^3.4.0",
    "@reduxjs/toolkit": "^1.6.2",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^16.11.11",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-table": "^7.7.9",
    "amazon-chime-sdk-component-library-react": "^3.0.0",
    "amazon-chime-sdk-js": "^3.0.0",
    "axios": "^0.24.0",
    "blob-util": "^2.0.2",
    "dayjs": "^1.11.0",
    "file-saver": "^2.0.5",
    "formik": "^2.2.9",
    "html2canvas": "^1.3.3",
    "i18next": "^21.5.4",
    "i18next-browser-languagedetector": "^6.1.2",
    "jspdf": "^2.5.1",
    "jszip": "^3.7.1",
    "keycloak-js": "^16.0.0",
    "lodash": "^4.17.21",
    "markerjs2": "^2.19.0",
    "material-ui-popup-state": "^2.0.1",
    "moment": "^2.29.1",
    "moment-duration-format": "^2.3.2",
    "network-speed": "^2.1.1",
    "notistack": "^2.0.3",
    "pdfjs-dist": "^2.12.313",
    "peerjs": "^1.4.3",
    "qrcode.react": "^3.0.1",
    "qs": "^6.10.1",
    "react": "^17.0.2",
    "react-device-detect": "^2.2.2",
    "react-dom": "^17.0.2",
    "react-file-viewer": "^1.2.1",
    "react-i18next": "^11.15.3",
    "react-input-verification-code": "^1.0.0",
    "react-material-file-upload": "^0.0.4",
    "react-papaparse": "^3.18.2",
    "react-pdf": "^5.6.0",
    "react-phone-number-input": "^3.1.44",
    "react-redux": "^7.2.6",
    "react-resize-detector": "^7.0.0",
    "react-router-dom": "^6.0.2",
    "react-scripts": "4.0.3",
    "react-signature-canvas": "^1.0.5",
    "react-table": "^7.7.0",
    "recordrtc": "^5.6.2",
    "redux": "^4.1.2",
    "redux-saga": "^1.1.3",
    "socket.io-client": "^4.4.1",
    "styled-components": "^5.3.3",
    "styled-system": "^5.1.5",
    "typescript": "^4.5.2",
    "use-debounce": "^7.0.1",
    "wavesurfer.js": "^5.2.0",
    "web-vitals": "^1.0.1",
    "yup": "^0.32.11",
    "yup-locales": "^1.2.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "overrides": [
      {
        "files": [
          "**/*.stories.*"
        ],
        "rules": {
          "import/no-anonymous-default-export": "off"
        }
      }
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.4.13",
    "@storybook/addon-essentials": "^6.4.13",
    "@storybook/addon-links": "^6.4.13",
    "@storybook/node-logger": "^6.4.13",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.4.13",
    "@types/file-saver": "^2.0.4",
    "@types/lodash": "^4.14.177",
    "@types/moment-duration-format": "^2.2.3",
    "@types/qs": "^6.9.7",
    "@types/react-pdf": "^5.0.9",
    "@types/react-signature-canvas": "^1.0.2",
    "@types/react-table": "^7.7.9",
    "@types/recordrtc": "^5.6.8",
    "@types/styled-components": "^5.1.17",
    "@types/w3c-image-capture": "^1.0.6",
    "@types/wavesurfer.js": "^5.2.2",
    "@types/webpack-env": "^1.16.3",
    "@typescript-eslint/typescript-estree": "^5.6.0",
    "prettier": "2.6.2",
    "react-error-overlay": "6.0.9",
    "sass": "^1.44.0"
  },
  "optionalDependencies": {
    "babel-loader": "8.1.0"
  },
  "resolutions": {
    "react-error-overlay": "6.0.9",
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2"
  }
}
`

**Comment by ckqbao** [comment]
@jonasgloning 
Your repository works fine but there are somes warnings:

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/api.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/api.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/baseconnection.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/baseconnection.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/dataconnection.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/dataconnection.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/encodingQueue.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/encodingQueue.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/enums.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/enums.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/exports.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/exports.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/logger.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/logger.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/mediaconnection.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/mediaconnection.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/negotiator.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/negotiator.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/peer.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/peer.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/socket.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/socket.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/supports.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/supports.ts'

WARNING in ./node_modules/peerjs/dist/bundler.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/util.ts' file: Error: ENOENT: no such file or directory, open '/home/crow/projects/test-peerjs/node_modules/peerjs/lib/util.ts'

And I tried to delete node_modules, package-lock.json and yarn.lock then reinstalled, but the error is still there. Anyway thanks for your time for this issue, Im downgrading to version 1.3.2 for a stable version.

**Comment by ckqbao** [comment]
@jonasgloning I realised that you have changed react-script from v4.0.3 to v5.0.1. I tested it and if a CRA project uses v4, we got this error from webrtc-adapter
