### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by strukturart** [peers/peerjs#955]
when trying to connect to the peerJS server I get the following error message:

`ERROR PeerJS:  Error retrieving ID (TypeError) 'referrerPolicy' member of RequestInit 'strict-origin-when-cross-origin' is not a valid value for enumeration ReferrerPolicy.`

**Comment by franci2000** [comment]
Hey @strukturart,
thanks for your report!

Could you tell us:
- which Browser are you using? 
- do you host the server yourself?
- does the request fail or is it just a warning?

**Comment by strukturart** [comment]
**which Browser are you using?**
KaiOs 2.5.1
**do you host the server yourself?**
no
**does the request fail or is it just a warning?**
request fail

**Comment by franci2000** [comment]
I’m sorry, but we probably won’t fix this if it’s not an issue with other - more common - browsers too.
With an estimated global usage of only [0.07%](https://caniuse.com/mdn-http_headers_referrer-policy_strict-origin-when-cross-origin), KaiOS 2.5 is strictly out of scope for us. The browser engine was released almost 6 years ago! 

If you need to support KaiOS 2.5, PeerJS v1.3 or below are still an option. They don’t use this policy.

**Comment by strukturart** [comment]
Is the problem on the client side or on the server side? then I would adjust the version.

**Comment by franci2000** [comment]
Just the client.

**Comment by strukturart** [comment]
Thank you!
