### ISSUE TITLE
Javascript library

### ISSUE THREAD

**Issue by Txori** [peers/peerjs#960]
Hello, are you going to release the new version as Javascript library such as https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js
or will it be only npm from now on?

**Comment by Praveenjana20** [comment]
The latest version 1.4.4 is available in this link. 

https://unpkg.com/peerjs@1.4.4/dist/peerjs.min.js

NPM Package: https://www.npmjs.com/package/peerjs

**Comment by Txori** [comment]
Thanks. Transition from 1.3.2 to 1.4.4 worked like a charm!
