### ISSUE TITLE
SSL for peerjs.com

### ISSUE THREAD

**Issue by michaelmior** [peers/peerjs#97]
Perhaps this is not the right place for this, but I'm wondering why http://peerjs.com doesn't support SSL.

GlobalSign now offers free wildcard certificates to open source projects, so it seems like this wouldn't be too tough to manage.

https://www.globalsign.com/ssl/ssl-open-source/

Thanks for listening :)

**Comment by szimek** [comment]
@michelle Any updates on this? It looks like you already got a certificate from GlobalSign some time ago, but like others mentioned, it's also possible to get a free one from StartSSL or you could even use CloudFlare, as they do support websockets.

**Comment by sblaurock** [comment]
Checking in - any luck getting this set up?

**Comment by ddehghan** [comment]
+1 Any status on this would be appreciated.

**Comment by wtip** [comment]
Was watching the Krankygeek webrtc talks and Justin was mentioning that starting with Chrome 47? getusermedia will only work on https sites

**Comment by viktorstrate** [comment]
SSL for peerjs.com, would really solve alot of issues.

If you have not heard of [Let's Encrypt](https://letsencrypt.org/), it is really great. It lets you encrypt websites extremly easy, using automated tools, besides that it is completely free. I have used it multiple times, and it just works!
