### ISSUE TITLE
How to get remote label?

### ISSUE THREAD

**Issue by hy-net** [peers/peerjs#972]
peer.connections['remote_peer_id'][0].options.label

Why am I getting the options from the Host?

**Comment by jonasgloning** [comment]
I don’t think you can access the remote label, but you can use
```ts
peer.connect(session, { metadata: { label: "yourLabelHere" } })
```
and access it on the receiving peer with
```ts
peer.on('connection', (conn) => {
 console.log(conn.metadata.label)
})
```

Does that solve your problem?

**Comment by hy-net** [comment]
Yes thanks @jonasgloning
