### ISSUE TITLE
Peer server connection issue

### ISSUE THREAD

**Issue by SujithManjavana** [peers/peerjs#977]
Peer server is down?? How can I test the availability of peer server?

**Comment by SujithManjavana** [comment]
Thank you for the quick fix. I'm planning to host my own peer server. Could
you please help me to select a server configuration for handling around
1000 concurrent connections? Also, is there any plan to make a peer.js
android client?

**Comment by SujithManjavana** [comment]
Does peer server cloud have built-in TURN server?

**Comment by SujithManjavana** [comment]
Should I include these lines in my code? Is it safe to remove the TURN servers I'm currently using?

**Comment by SujithManjavana** [comment]
Sure, I'll definitely donate once my app gets released and starts making a profit.

**Comment by SujithManjavana** [comment]
@jonasgloning Sorry to bother you again, But I'm having some issues with peer.js calls. In some networks, there is a 3-5 second delay in audio and video. Both the clients reside in India. I thought it was because of wifi and turn server delay, so I tried calling on mobile data and the result was the same. Is there anything I can do to fix this? Could you please help me to set media constraints that use the minimum amount of data while providing a decent call quality?

**Comment by SujithManjavana** [comment]
Currently, I'm using only TRUE for audio and video constraints.

**Comment by SujithManjavana** [comment]
I'm planning to host my own peer server. But I have a few concerns. 
Can I continue using your TURN servers ("turn:eu-0.turn.peerjs.com:3478") with my own peer server? Can I implement the peer server code in my existing express server (which has socket.io with Cluster adapter for multi-threading)? How many peers can connect at a time?

**Comment by Ravindu007** [comment]
I have implemented my own peer server and sometimes when some users connect they can't get other's stream, is this happen due to using default STUN TURN servers provided with Peer JS.

**Comment by SujithManjavana** [comment]
@Ravindu007 You have to host your own TURN server.

**Comment by SujithManjavana** [comment]
@Ravindu007 I'm using COTURN on an Ubuntu server. You can use any cloud provider of your choice. I use linode. A single core server with 1 gb ram is more than enough for a small app. Make sure to use proper firewall rules for COTURN to work.

**Comment by Ravindu007** [comment]
@SujithManjavana Thank you so much for the information
