### ISSUE TITLE
TypeError: Illegal invocation when using Media calls demo

### ISSUE THREAD

**Issue by fraserxu** [peers/peerjs#98]
Hi @peers @michellebu I'm trying to use [peerjs](https://github.com/peers/peerjs) in my angularjs application. While trying to use the code for media call in your example,

``` javascript
var getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
getUserMedia({video: true, audio: true}, function(stream) {
  var call = peer.call('another-peers-id', stream);
  call.on('stream', function(remoteStream) {
    // Show stream in some <video> element.
  });
}, function(err) {
  console.log('Failed to get local stream' ,err);
});
```

I got an error message like this: `TypeError: Illegal invocation...`

But if I try to use it like this, it works just fine.

``` javascript
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
navigator.getUserMedia({video: true, audio: true}, function(stream) {
  var call = peer.call('another-peers-id', stream);
  call.on('stream', function(remoteStream) {
    // Show stream in some <video> element.
  });
}, function(err) {
  console.log('Failed to get local stream' ,err);
});
```

Not sure if this is related to the browser `navigator` api or just an `angularjs` issues. Do you have any idea? Thanks.

**Comment by JasonFang93** [comment]
I have the same problem, and the version of peerjs is 0.3.14, by the way, could you tell me how to fix this bug

**Comment by ocolot** [comment]
By the way, this issue is still in the media section of http://peerjs.com

**Comment by souravndp** [comment]
still not fixed

**Comment by digitalgarage** [comment]
Hi @souravndp  is this only when trying to access the remote stream on a call?  I was getting this same error at one point -- only on media stream but plain old data connection between peers was working fine.

When I increased the debug level there was additional messages about an incorrect channel.

Adding STUN and TURN servers seemed to resolve this for me so possibly it was due to connectivity between the two peers?

**Comment by souravndp** [comment]
@digitalgarage , as the OP mentioned, replacing `getUserMedia` with `navigator.getUserMedia` solved my problem. @michelle posted on 2013 about fixing the example on peerjs website but the old example is still there. In their [github example](https://github.com/peers/peerjs/blob/master/examples/videochat/index.html), they used `navigator.getUserMedia` and it works fine.

**Comment by hasangilak** [comment]
these sort of function needs navigator as its context. so with bind we can simply solve the problem. 
```
  var getUserMedia = (function () {
    if(navigator.getUserMedia) {
        return navigator.getUserMedia.bind(navigator)
    }
    if(navigator.webkitGetUserMedia) {
      return navigator.webkitGetUserMedia.bind(navigator)
    }
    if(navigator.mozGetUserMedia) {
      return navigator.mozGetUserMedia.bind(navigator)
    }
  })();
```
