### ISSUE TITLE
Peerjs Server Issue

### ISSUE THREAD

**Issue by devthisath** [peers/peerjs#985]
Hey There,
I'Ve Deployed My Own Peerjs Server But When I Close The Terminal (Putty) The Server Has Been Stopped,
How Can I Run It Forever , I Tried Many Solutions But Nothing Worked. Please Help With This Issue.

**Comment by SujithManjavana** [comment]
For a production environment you should use a process manager. Like pm2 for NodeJS apps.

**Comment by devthisath** [comment]
> For a production environment you should use a process manager. Like pm2 for NodeJS apps.

It's Work Without SSL,
In Ubuntu We Need To Run The pm2 start peerjs --name mypeerjs -- --port 9000 --path /myapp --key peerjs --sslkey /etc/ssl/private/ssl-cert-snakeoil.key --sslcert /etc/ssl/certs/ssl-cert-snakeoil.pem As Sudo How Can I Do That?

**Comment by SujithManjavana** [comment]
It's better to use nginx as reverse proxy to manage all the incoming connections. So that you can have multiple apps running on the same port with SSL.

**Comment by devthisath** [comment]
> It's better to use nginx as reverse proxy to manage all the incoming connections. So that you can have multiple apps running on the same port with SSL.

No You Didn't Get That,
 I Want To Use SSL On My Peerjs Server ,
But To Read .key file The Command Must Use 'sudo'
How Can I Use sudo in pm2  ?

**Comment by devthisath** [comment]
Issue Has Been Fixed

**Comment by SujithManjavana** [comment]
You may ask this question on stackovrrflow. I've never used peerjs with SSL.

**Comment by devthisath** [comment]
No You Didn't Get That,
 I Want To Use SSL On My Peerjs Server ,
But To Read .key file The Command Must Use 'sudo'
How Can I Use sudo in pm2  ?
